import { Service } from '@/types'

export const services: Service[] = [
  // ─── ТОПОВЫЕ (featured) ────────────────────────────────
  {
    slug: '1xbet', name: '1xBet', logo: '1️⃣',
    tagline: 'Крупнейший международный букмекер с казино',
    description: '1xBet — один из крупнейших букмекеров мира: 40+ видов спорта, 1000+ live-событий и огромное казино. Бонус 100% до 32 500 ₽.',
    fullDescription: `1xBet основан в 2007 году. Один из крупнейших операторов мира по количеству событий и вариантов ставок. 40+ видов спорта, 1000+ live-событий с трансляциями, тысячи слотов в казино.\n\nПриветственный пакет: 100% до 32 500 ₽ на спорт + казино-пакет до €1950 + 150 фриспинов за первые депозиты.`,
    rating: 4.6, userRating: 4.4, reviewCount: 18420, type: 'both', founded: 2007,
    license: 'Curaçao eGaming (1668/JAZ)', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100% до 32 500 ₽ + €1950 в казино',
    bonuses: [
      { type: 'deposit', title: 'Бонус на спорт', description: '100% на первый депозит', amount: '100% до 32 500 ₽', wagering: '5x экспресс (3+ события кф 1.4+)', validDays: 30 },
      { type: 'freespins', title: 'Пакет казино', description: 'До €1950 + 150 фриспинов', amount: '€1950 + 150 FS', wagering: '35x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 100,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Бонус 100% до 32 500 ₽', '40+ видов спорта, 1000+ live', 'Огромное казино', 'Депозит от 100 ₽'],
    cons: ['Зарубежная лицензия', 'Сложный вейджер', 'Задержки выплат у некоторых'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 300000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 100, maxWithdrawal: 1000000, time: '1-2 часа' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 1000000, time: '1-2 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [],
    faq: [{ question: 'Как получить бонус?', answer: 'Зарегистрируйтесь и пополните счёт от 100 ₽. Бонус начислится автоматически.' }],
    reviews: [{ author: 'Алексей М.', rating: 5, date: '2026-02-20', text: 'Самый большой выбор событий. Бонус получил без проблем.', avatar: 'АМ' }],
    featured: true, popular: true, badge: 'Мировой лидер', accentColor: '#3b82f6',
  },
  {
    slug: '1win', name: '1Win', logo: '🏅',
    tagline: 'Мегабонус 500% на первые 4 депозита',
    description: '1Win — 500% суммарно до 200 000 ₽ на первые 4 депозита. Казино + спорт, Авиатор, 1Win Games.',
    fullDescription: `1Win основан в 2016 году. Пакет на 4 депозита: 200%+150%+100%+50%, суммарно до 200 000 ₽ (до 50 000 ₽ на каждый). Казино с тысячами слотов, Авиатор, уникальные быстрые игры 1Win Games.`,
    rating: 4.5, userRating: 4.3, reviewCount: 12350, type: 'both', founded: 2016,
    license: 'Curaçao eGaming (8048/JAZ)', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '500% до 200 000 ₽ на 4 депозита',
    bonuses: [
      { type: 'deposit', title: 'Мегапакет', description: '200%+150%+100%+50% на первые 4 депозита', amount: 'до 200 000 ₽', wagering: 'ординар кф 3.0+, 5% за выигрыш', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек казино', description: 'Еженедельный кэшбек', amount: 'до 30%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 100,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['500% до 200 000 ₽ — лучший на рынке', 'Авиатор и 1Win Games', 'Депозит от 100 ₽'],
    cons: ['Вейджер кф от 3.0', 'Зарубежная лицензия'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 100000, time: '2-4 часа' },
    ],
    screenshots: [],
    faq: [{ question: 'Как работает бонус 500%?', answer: '200% за первый депозит, 150% за второй, 100% за третий, 50% за четвёртый. Максимум 50 000 ₽ на каждый.' }],
    reviews: [{ author: 'Дмитрий С.', rating: 5, date: '2026-03-01', text: 'Бонус 500% — реально лучшее предложение на рынке.', avatar: 'ДС' }],
    featured: true, popular: true, badge: 'Лучший бонус', accentColor: '#a855f7',
  },
  {
    slug: 'fonbet', name: 'Fonbet', logo: '🦅',
    tagline: 'Легальный букмекер №1 в России с фрибетом до 15 000 ₽',
    description: 'Fonbet работает с 1994 года. Лицензия ФНС. Бездепозитный фрибет до 15 000 ₽ за регистрацию, лучшие коэффициенты на РПЛ и КХЛ.',
    fullDescription: `Fonbet — старейший и крупнейший легальный букмекер России с 1994 года. Лицензия ФНС, член СРО. Бездепозитный фрибет до 15 000 ₽ — просто за верификацию. Лучшие коэффициенты на РПЛ, КХЛ. Live 500+ событий с трансляциями. Кэшбек 20% на киберспорт.`,
    rating: 4.5, userRating: 4.4, reviewCount: 21300, type: 'betting', founded: 1994,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет до 15 000 ₽ без депозита',
    bonuses: [
      { type: 'registration', title: 'Бездепозитный фрибет', description: 'Фрибет за регистрацию и верификацию', amount: 'до 15 000 ₽', wagering: '1x (ординар кф до 3.0)', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек на киберспорт', description: '20% еженедельно', amount: 'до 50 000 ₽', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС — максимальная надёжность', 'Фрибет до 15 000 ₽ без депозита', 'Работает с 1994 года', 'Лучшие кэфы на РПЛ/КХЛ'],
    cons: ['Нет казино', 'Обязательный KYC'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-4 часа' },
      { name: 'ЮMoney', icon: '💰', minDeposit: 100, maxWithdrawal: 100000, time: '1-3 часа' },
    ],
    screenshots: [],
    faq: [{ question: 'Как получить фрибет до 15 000 ₽?', answer: 'Зарегистрируйтесь и пройдите верификацию. Через 48 часов фрибет придёт автоматически.' }],
    reviews: [{ author: 'Владимир Н.', rating: 5, date: '2026-03-05', text: 'Самый честный букмекер России. 5 лет без проблем.', avatar: 'ВН' }],
    featured: true, popular: true, badge: 'Легальный №1', accentColor: '#f97316',
  },
  {
    slug: 'winline', name: 'Winline', logo: '🎯',
    tagline: 'Фрибет 3 000 ₽ за регистрацию + программа Priority',
    description: 'Winline — официальный российский букмекер. Фрибет 3 000 ₽ за депозит от 500 ₽. Программа Priority с ежедневными бонусами и кэшбеком до 100%.',
    fullDescription: `Winline работает с 2009 года, лицензия ФНС. Гарантированный фрибет 3 000 ₽ за депозит от 500 ₽. Программа Priority: ежедневные бонусы, кэшбек до 100%, ежемесячный фрибет до 50 000 ₽.`,
    rating: 4.4, userRating: 4.3, reviewCount: 15780, type: 'betting', founded: 2009,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет 3 000 ₽ за регистрацию',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: '3 000 ₽ за депозит от 500 ₽', amount: '3 000 ₽', wagering: '1x кф от 1.3', validDays: 30 },
      { type: 'cashback', title: 'Priority кэшбек', description: 'До 100% для активных', amount: 'до 100%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Гарантированный фрибет 3 000 ₽', 'Кэшбек до 100%', 'Сильная линия на РПЛ'],
    cons: ['Нет казино', 'Нужно приложение для бонуса'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 500, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 500, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [],
    faq: [{ question: 'Как получить фрибет 3 000 ₽?', answer: 'Скачайте приложение, зарегистрируйтесь и внесите депозит от 500 ₽.' }],
    reviews: [{ author: 'Сергей Л.', rating: 5, date: '2026-03-08', text: 'Лучший для ставок на РПЛ. Приложение стабильное.', avatar: 'СЛ' }],
    featured: true, popular: true, badge: 'Легальный', accentColor: '#4ade80',
  },

  // ─── ПОПУЛЯРНЫЕ ──────────────────────────────────────
  {
    slug: 'mostbet', name: 'MostBet', logo: '⚽',
    tagline: '125% + 250 фриспинов на первый депозит',
    description: 'MostBet — 125% до 25 000 ₽ + 250 фриспинов. Программа лояльности 10 уровней, реферальная программа 15%.',
    fullDescription: `MostBet работает с 2009 года. Приветственный бонус 125% до 25 000 ₽ + 250 FS. Бонусы на 4 первых депозита. 10-уровневая программа лояльности. Реферальная программа до 15%.`,
    rating: 4.4, userRating: 4.2, reviewCount: 9870, type: 'both', founded: 2009,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '125% до 25 000 ₽ + 250 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '125% + 250 FS', amount: '125% до 25 000 ₽', wagering: '5x спорт / 60x казино', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['125% + 250 фриспинов', 'Бонусы на 4 депозита', 'Программа лояльности'],
    cons: ['Вейджер казино x60', 'Зарубежная лицензия'],
    paymentMethods: [{ name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-5 дней' }],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#38bdf8',
  },
  {
    slug: 'betcity', name: 'Бетсити', logo: '🏙️',
    tagline: 'До 200 000 ₽ бонуса по промокоду 200BONUS',
    description: 'Бетсити — один из лидеров легального рынка РФ. Бонус до 200% за первый депозит по промокоду 200BONUS. Лицензия ФНС.',
    fullDescription: `Бетсити — крупный российский легальный букмекер с лицензией ФНС. По промокоду 200BONUS при регистрации доступен бонус до 200% на первый депозит. Акция действует до 31 декабря 2026 года. Широкая линия, Live с трансляциями, сильная киберспортивная линия.`,
    rating: 4.4, userRating: 4.2, reviewCount: 13500, type: 'betting', founded: 2003,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'До 200% за первый депозит',
    bonuses: [
      { type: 'deposit', title: 'Бонусный плей-офф', description: 'До 200% за первый депозит по промокоду 200BONUS', amount: 'до 200%', wagering: '5x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Лицензия ФНС', 'Бонус до 200% за первый депозит', 'Сильная линия и Live', 'Топовые коэффициенты'],
    cons: ['Нет казино', 'Нужен промокод для макс. бонуса'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#f59e0b',
  },
  {
    slug: 'leon', name: 'Leon', logo: '🦁',
    tagline: 'Фрибет до 25 000 ₽ + лучшая линия на киберспорт',
    description: 'Leon — топовый легальный букмекер. Фрибет до 25 000 ₽ за регистрацию. Лучший в России по линии киберспорта, низкая маржа 5–7%.',
    fullDescription: `Леон работает с 2007 года, лицензия ФНС. Приветственный фрибет до 25 000 ₽ за первую проигравшую ставку с промокодом STRAHOVKA. Программа лояльности Leon Family с кэшбеком до 15%. Уникальный раздел «Киберфутбол» с 4 лигами. Минимальная маржа 5–7% на топовые события.`,
    rating: 4.5, userRating: 4.3, reviewCount: 11200, type: 'betting', founded: 2007,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет до 25 000 ₽',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: 'Фрибет до 25 000 ₽ за первую проигрышную ставку', amount: 'до 25 000 ₽', wagering: '1x кф от 1.7', validDays: 30 },
      { type: 'cashback', title: 'Leon Family кэшбек', description: 'Кэшбек до 15% ежемесячно', amount: 'до 15%', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Лучший киберспорт в России', 'Маржа 5–7%', 'Фрибет до 25 000 ₽'],
    cons: ['Нет казино', 'Фрибет только за проигрыш'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Топ киберспорт', accentColor: '#eab308',
  },
  {
    slug: 'betboom', name: 'BetBoom', logo: '💥',
    tagline: 'Фрибет 10 000 ₽ + агрессивная бонусная политика',
    description: 'BetBoom (ранее BingoBoom) — легальный букмекер с лицензией ФНС. Фрибет 10 000 ₽ за регистрацию. Лидер по кибеспорту и маркетинговым акциям 2026 года.',
    fullDescription: `BetBoom (BingoBoom) — один из самых быстрорастущих легальных букмекеров России 2026 года. Агрессивная маркетинговая политика и акцент на киберспортивной линии. Приветственный фрибет 10 000 ₽ за регистрацию. Широкая линия по CS2, Dota 2, LoL, Valorant.`,
    rating: 4.3, userRating: 4.2, reviewCount: 8900, type: 'betting', founded: 2010,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет 10 000 ₽',
    bonuses: [
      { type: 'registration', title: 'Фрибет за регистрацию', description: 'Фрибет 10 000 ₽ новым игрокам', amount: '10 000 ₽', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Фрибет 10 000 ₽', 'Лучшая линия CS2 и Dota 2', 'Быстрый рост 2026'],
    cons: ['Нет казино', 'Слабая техподдержка'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#ef4444',
  },
  {
    slug: 'olimpbet', name: 'OlimpBet', logo: '🏛️',
    tagline: 'Фрибет до 15 000 ₽ по промокоду TGBONUS',
    description: 'OlimpBet — легальный букмекер, работающий с 2004 года. Фрибет до 15 000 ₽ за первый депозит по промокоду TGBONUS. Программа лояльности с кэшбеком до 20%.',
    fullDescription: `OlimpBet (Олимп) работает с 2004 года, лицензия ФНС с 2012 года. Приветственный фрибет: 50% от суммы первого депозита от 1 000 ₽ — до 15 000 ₽ по промокоду TGBONUS. Программа лояльности с кэшбеком до 20%, удвоение коэффициента экспресса.`,
    rating: 4.2, userRating: 4.1, reviewCount: 7600, type: 'betting', founded: 2004,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет до 15 000 ₽',
    bonuses: [
      { type: 'deposit', title: 'Приветственный фрибет', description: '50% от первого депозита', amount: 'до 15 000 ₽', wagering: '1x', validDays: 7 },
      { type: 'cashback', title: 'Программа лояльности', description: 'Кэшбек до 20% + удвоение кэфа экспресса', amount: 'до 20%', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 1000,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Лицензия ФНС', 'С 2004 года', 'Кэшбек до 20%', 'Удвоение кэфа экспресса'],
    cons: ['Мин. депозит 1 000 ₽', 'Нет казино'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 1000, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 1000, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#06b6d4',
  },
  {
    slug: 'pari', name: 'PARI', logo: '🎪',
    tagline: '5 фрибетов по 1 000 ₽ или до 20 000 ₽ по промокоду',
    description: 'PARI (экс-Parimatch, ребрендинг 2026) — легальный букмекер с 1994 года. 5 фрибетов по 1 000 ₽ или до 20 000 ₽ по промокоду SPORTS20. Лучшая линия на теннис.',
    fullDescription: `PARI (ранее Parimatch) работает с 1994 года, лицензия ФНС. Ребрендинг в марте 2026 года. Для новых игроков: 5 фрибетов по 1 000 ₽ или по промокоду LUXURY — 9 999 ₽, по промокоду SPORTS20 — 100% до 20 000 ₽. Лучшие коэффициенты на теннис, UFC. Live 800+ событий.`,
    rating: 4.3, userRating: 4.2, reviewCount: 11200, type: 'betting', founded: 1994,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '5 фрибетов по 1 000 ₽',
    bonuses: [
      { type: 'freespins', title: '5 фрибетов', description: 'Пять фрибетов по 1 000 ₽ за депозит и ставки', amount: '5 × 1 000 ₽', wagering: '1x', validDays: 30 },
      { type: 'deposit', title: 'По промокоду SPORTS20', description: '100% на первый депозит', amount: 'до 20 000 ₽', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['Лицензия ФНС', 'С 1994 года', 'Лучший теннис и UFC', 'Быстрые выплаты СБП'],
    cons: ['Нет казино', 'Ребрендинг — часть функций дорабатывается'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 150000, time: '30 мин — 2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Ребрендинг 2026', accentColor: '#fbbf24',
  },
  {
    slug: 'melbet', name: 'MelBet', logo: '🌐',
    tagline: '100% до 35 000 ₽ по промокоду + VIP-кэшбек 20%',
    description: 'MelBet — 50+ видов спорта, бонус до 35 000 ₽ по промокоду. VIP-кэшбек до 20%, Гранд Экспресс.',
    fullDescription: `MelBet работает с 2012 года. По промокоду LEGALBET — 100% до 35 000 ₽ на первый депозит. VIP-кэшбек до 20% ежемесячно. Гранд Экспресс — повышение итогового коэффициента. Еженедельный джекпот до 50 000 ₽. Казино с тысячами игр.`,
    rating: 4.3, userRating: 4.1, reviewCount: 8940, type: 'both', founded: 2012,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100% до 35 000 ₽ по промокоду',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% по промокоду LEGALBET', amount: '100% до 35 000 ₽', wagering: 'x25 кф 1.5+', validDays: 30 },
      { type: 'cashback', title: 'VIP-кэшбек', description: 'До 20% ежемесячно', amount: 'до 20%', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 1000,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['35 000 ₽ по промокоду', 'VIP-кэшбек 20%', '50+ видов спорта'],
    cons: ['Вейджер x25', 'Мин. депозит 1 000 ₽', 'Нет российской лицензии'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 1000, maxWithdrawal: 200000, time: '2-5 дней' },
      { name: 'USDT', icon: '💱', minDeposit: 1000, maxWithdrawal: 500000, time: '2-4 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#e879f9',
  },
  {
    slug: 'marathon', name: 'Марафон', logo: '🏃',
    tagline: 'Фрибет до 21 500 ₽ за экспрессы + VIP для крупных игроков',
    description: 'Марафон — старейший легальный букмекер с 1997 года. Фрибет до 21 500 ₽ за экспресс-ставки. VIP-клуб с персональными бонусами для крупных игроков.',
    fullDescription: `Марафон (Marathon) работает с 1997 года, лицензия ФНС. Фрибет до 21 500 ₽ за экспресс-ставки новым игрокам. Фрибет 11 111 ₽ за регистрацию через приложение и ставки. Фрибет 5 000 ₽ за первый депозит в мобильном приложении. VIP-клуб для крупных игроков с персональными предложениями.`,
    rating: 4.2, userRating: 4.0, reviewCount: 9300, type: 'betting', founded: 1997,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет до 21 500 ₽',
    bonuses: [
      { type: 'registration', title: 'Фрибет за экспрессы', description: 'До 21 500 ₽ за экспресс-ставки новым игрокам', amount: 'до 21 500 ₽', wagering: '1x', validDays: 30 },
      { type: 'deposit', title: 'Фрибет за депозит в приложении', description: '5 000 ₽ за первый депозит в приложении', amount: '5 000 ₽', wagering: '1x', validDays: 14 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['Лицензия ФНС', 'С 1997 года', 'Фрибет до 21 500 ₽', 'VIP для крупных игроков'],
    cons: ['Нет казино', 'Слабые бонусы для мелких игроков'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 500, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#84cc16',
  },
  {
    slug: 'liga-stavok', name: 'Лига Ставок', logo: '🏆',
    tagline: 'Фрибет 7 777 ₽ за регистрацию + страховка экспресса',
    description: 'Лига Ставок — старейший легальный букмекер. Фрибет 7 777 ₽ за регистрацию. Страховка экспресса до 18 000 000 ₽. Офисы по всей России.',
    fullDescription: `Лига Ставок работает с 2008 года, лицензия ФНС. Приветственный фрибет 7 777 ₽ за регистрацию. Уникальная акция «Страховка экспресса» — до 18 000 000 ₽ при ставке от 6 событий. Акция «0:0 в вашу пользу» — возврат при нулевой ничьей. Розыгрыш 30 000 ₽ за оборот 1 000 000 ₽.`,
    rating: 4.2, userRating: 4.1, reviewCount: 12400, type: 'betting', founded: 2008,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет 7 777 ₽',
    bonuses: [
      { type: 'registration', title: 'Фрибет за регистрацию', description: 'Фрибет 7 777 ₽ за регистрацию', amount: '7 777 ₽', wagering: '1x кф от 1.5', validDays: 30 },
      { type: 'deposit', title: 'Страховка экспресса', description: 'До 18 000 000 ₽ страховка экспресса от 6 событий', amount: 'до 18 000 000 ₽', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Фрибет 7 777 ₽', 'Страховка экспресса', 'Офисы по всей России'],
    cons: ['Нет казино', 'Средний уровень коэффициентов'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#8b5cf6',
  },
  {
    slug: 'tennisi', name: 'Tennisi', logo: '🎾',
    tagline: 'Бессрочный бонус + специализация на теннисе',
    description: 'Tennisi — легальный букмекер с уникальным бессрочным бонусом при депозите от 50 ₽. Специализация на теннисе и теннисных трансляциях.',
    fullDescription: `Tennisi (Тенниси) — легальный букмекер с уникальным бессрочным бонусом: минимальный депозит всего 50 ₽. Специализация на теннисе — лучшая роспись на ATP, WTA, ITF. VIP-кэшбек для игроков с оборотом от 1 000 000 ₽. Бонус до 20 000 ₽ на три первых депозита по промокоду VBRSPORT.`,
    rating: 4.1, userRating: 4.0, reviewCount: 5400, type: 'betting', founded: 2014,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Бессрочный бонус + до 20 000 ₽',
    bonuses: [
      { type: 'registration', title: 'Бессрочный бонус', description: 'Уникальный бессрочный бонус при депозите от 50 ₽', amount: 'бессрочно', wagering: '1x', validDays: 0 },
      { type: 'deposit', title: 'Бонус по промокоду', description: 'До 20 000 ₽ на три первых депозита', amount: 'до 20 000 ₽', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 50,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['Лицензия ФНС', 'Депозит от 50 ₽', 'Лучший теннис', 'Бессрочный бонус'],
    cons: ['Нет казино', 'Небольшое количество видов спорта'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 50, maxWithdrawal: 200000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 50, maxWithdrawal: 100000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Теннис #1', accentColor: '#10b981',
  },
  {
    slug: 'baltbet', name: 'БалтБет', logo: '⚓',
    tagline: 'Фрибет 8 000 ₽ + розыгрыши для активных',
    description: 'БалтБет — легальный букмекер с 1994 года. Фрибет 8 000 ₽ за регистрацию. 9 акций для постоянных игроков, розыгрыши призов.',
    fullDescription: `БалтБет работает с 1994 года, лицензия ФНС. Один из старейших букмекеров России. Приветственный фрибет 8 000 ₽ за регистрацию. 9 бонусных акций для постоянных игроков включая розыгрыши призов, фрибеты за ставки на олимпийские виды спорта. VIP-кэшбек до 8%.`,
    rating: 4.1, userRating: 4.0, reviewCount: 6700, type: 'betting', founded: 1994,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет 8 000 ₽',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: 'Фрибет 8 000 ₽ за регистрацию', amount: '8 000 ₽', wagering: '1x', validDays: 30 },
      { type: 'cashback', title: 'VIP-кэшбек', description: 'До 8% кэшбека в программе лояльности', amount: 'до 8%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'С 1994 года', 'Фрибет 8 000 ₽', 'Розыгрыши призов'],
    cons: ['Нет казино', 'Устаревший интерфейс'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 200000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 100000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#0ea5e9',
  },
  {
    slug: 'zenit', name: 'Зенит', logo: '⚡',
    tagline: 'Фрибет 35 000 ₽ — один из крупнейших в РФ',
    description: 'Зенит — легальный букмекер с одним из крупнейших приветственных фрибетов в России — 35 000 ₽. Лицензия ФНС, качественная live-линия.',
    fullDescription: `БК Зенит — официальный легальный букмекер с лицензией ФНС. Предлагает один из крупнейших приветственных фрибетов в России — 35 000 ₽ за регистрацию и первые ставки. Качественная live-линия, хорошая роспись на футбол и хоккей.`,
    rating: 4.1, userRating: 4.0, reviewCount: 5200, type: 'betting', founded: 2007,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Фрибет 35 000 ₽',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: 'Фрибет 35 000 ₽ за регистрацию', amount: '35 000 ₽', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Фрибет 35 000 ₽', 'Хорошая live-линия'],
    cons: ['Нет казино', 'Среднее приложение'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#6366f1',
  },
  {
    slug: 'bettery', name: 'Bettery', logo: '🔋',
    tagline: 'Новый легальный букмекер с фокусом на удобстве',
    description: 'Bettery — один из новых легальных букмекеров России с лицензией ФНС. Современный интерфейс, удобное приложение, конкурентные коэффициенты.',
    fullDescription: `Bettery — один из новых игроков на легальном российском рынке. Лицензия ФНС. Современный дизайн платформы, удобное приложение для iOS и Android. Конкурентные коэффициенты, растущая линия событий.`,
    rating: 4.0, userRating: 3.9, reviewCount: 2800, type: 'betting', founded: 2020,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный фрибет',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: 'Фрибет новым игрокам за регистрацию', amount: 'уточняйте на сайте', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Современный интерфейс', 'Удобное приложение'],
    cons: ['Нет казино', 'Небольшая история', 'Развивающаяся линия'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 200000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 100000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: 'Новинка', accentColor: '#14b8a6',
  },
  {
    slug: 'sportbet', name: 'СпортБет', logo: '🥇',
    tagline: 'Легальный букмекер с акцентом на спорт',
    description: 'СпортБет — легальный российский букмекер с лицензией ФНС. Широкая линия на спортивные события, удобный интерфейс.',
    fullDescription: `СпортБет — легальная букмекерская контора с лицензией ФНС России. Специализация на спортивных ставках, хорошая роспись на футбол, хоккей, баскетбол. Приложения для iOS и Android.`,
    rating: 4.0, userRating: 3.9, reviewCount: 3200, type: 'betting', founded: 2015,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'registration', title: 'Приветственный бонус', description: 'Бонус новым игрокам за регистрацию', amount: 'уточняйте на сайте', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Широкая линия', 'Удобное приложение'],
    cons: ['Нет казино', 'Небольшой бренд'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 200000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 100000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#d97706',
  },
  {
    slug: '1xstavka', name: '1хСтавка', logo: '🎲',
    tagline: 'Российский аналог 1xBet с лицензией ФНС',
    description: '1хСтавка — легальная версия 1xBet для российского рынка с лицензией ФНС. Широкая линия, Live с трансляциями, приветственный бонус.',
    fullDescription: `1хСтавка — официальная российская компания группы 1xBet, работающая по лицензии ФНС. Обеспечивает доступ к широкой линии и live-ставкам на законных основаниях в России. Все функции 1xBet доступны в легальном формате.`,
    rating: 4.2, userRating: 4.0, reviewCount: 8700, type: 'betting', founded: 2016,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный фрибет',
    bonuses: [
      { type: 'registration', title: 'Приветственный фрибет', description: 'Фрибет за регистрацию и первую ставку', amount: 'уточняйте на сайте', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Широкая линия как у 1xBet', 'Live с трансляциями'],
    cons: ['Нет казино (легальная версия)', 'Менее широкий охват чем оффшорная 1xBet'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 300000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 200000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#3b82f6',
  },
  {
    slug: 'bet-m', name: 'Бет-М', logo: '🅜',
    tagline: 'Новый легальный букмекер 2025–2026',
    description: 'Бет-М — один из новейших легальных букмекеров России с лицензией ФНС. Современная платформа, конкурентные условия.',
    fullDescription: `Бет-М (Bet-M) — один из новых участников легального российского рынка букмекерских услуг. Получил лицензию ФНС и активно развивает платформу. Современный интерфейс, мобильное приложение для iOS и Android.`,
    rating: 3.9, userRating: 3.8, reviewCount: 1200, type: 'betting', founded: 2022,
    license: 'Российская лицензия ФНС, член СРО', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'registration', title: 'Приветственный бонус', description: 'Бонус новым игрокам', amount: 'уточняйте на сайте', wagering: '1x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Лицензия ФНС', 'Современная платформа', 'Мобильное приложение'],
    cons: ['Нет казино', 'Очень маленькая история', 'Небольшая линия'],
    paymentMethods: [
      { name: 'МИР', icon: '🏦', minDeposit: 100, maxWithdrawal: 200000, time: '1-2 дня' },
      { name: 'СБП', icon: '📱', minDeposit: 100, maxWithdrawal: 100000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: 'Новинка', accentColor: '#6b7280',
  },

  // ─── МЕЖДУНАРОДНЫЕ КАЗИНО ────────────────────────────
  {
    slug: 'vulkan-russia', name: 'Вулкан', logo: '🌋',
    tagline: 'Легендарное казино с бонусом 150 000 ₽',
    description: 'Вулкан — одно из самых известных онлайн-казино в России. Приветственный пакет до 150 000 ₽ + фриспины. Тысячи слотов, live-казино.',
    fullDescription: `Вулкан — легендарный бренд российского онлайн-гемблинга. Приветственный пакет до 150 000 ₽ на первые депозиты + до 200 фриспинов. Тысячи слотов от ведущих провайдеров, live-казино с реальными дилерами, быстрые игры.`,
    rating: 4.2, userRating: 4.0, reviewCount: 22000, type: 'casino', founded: 2009,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'До 150 000 ₽ + 200 фриспинов',
    bonuses: [
      { type: 'deposit', title: 'Приветственный пакет', description: 'До 150 000 ₽ + 200 фриспинов за первые депозиты', amount: '150 000 ₽ + 200 FS', wagering: '40x', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек', description: 'Еженедельный кэшбек для активных', amount: 'до 15%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Легендарный бренд', 'До 150 000 ₽ бонус', '1000+ слотов', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Легенда', accentColor: '#dc2626',
  },
  {
    slug: 'joycasino', name: 'JoyCasino', logo: '🎉',
    tagline: '100% до 50 000 ₽ + 100 фриспинов',
    description: 'JoyCasino — международное казино с бонусом 100% до 50 000 ₽ + 100 фриспинов. Live-казино, лотереи, программа лояльности.',
    fullDescription: `JoyCasino работает с 2014 года по лицензии Curaçao. Приветственный бонус 100% до 50 000 ₽ + 100 фриспинов. Тысячи слотов от NetEnt, Microgaming, Play'n GO. Live-казино с реальными дилерами, лотереи, виртуальный спорт.`,
    rating: 4.1, userRating: 4.0, reviewCount: 11300, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100% до 50 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 50 000 ₽ + 100 фриспинов', amount: '100% до 50 000 ₽', wagering: '45x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Бонус до 50 000 ₽', 'Тысячи слотов', 'Live-казино', 'Работает с 2014'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Вейджер x45'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#f43f5e',
  },
  {
    slug: 'frank-casino', name: 'Frank Casino', logo: '🎩',
    tagline: 'Элитное казино: 150% до 100 000 ₽',
    description: 'Frank Casino — элитное онлайн-казино с бонусом 150% до 100 000 ₽. Эксклюзивные провайдеры, высокие лимиты, VIP-программа.',
    fullDescription: `Frank Casino работает с 2014 года по лицензии Curaçao. Приветственный бонус 150% до 100 000 ₽ + 250 фриспинов. Эксклюзивные провайдеры, высокие лимиты на вывод. VIP-программа с персональным менеджером. Идеально для высоких ставок.`,
    rating: 4.3, userRating: 4.1, reviewCount: 8700, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '150% до 100 000 ₽ + 250 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '150% + 250 FS', amount: '150% до 100 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'cashback', title: 'VIP-кэшбек', description: 'Персональный кэшбек для VIP', amount: 'до 25%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 1000,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['150% до 100 000 ₽', 'VIP-программа', 'Высокие лимиты', 'Эксклюзивные провайдеры'],
    cons: ['Зарубежная лицензия', 'Мин. депозит 1 000 ₽'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 1000, maxWithdrawal: 500000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 1000, maxWithdrawal: 1000000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'VIP', accentColor: '#92400e',
  },
  {
    slug: 'slotv', name: 'SlotV', logo: '🎰',
    tagline: '100% до 25 000 ₽ + 100 фриспинов',
    description: 'SlotV — казино с акцентом на слоты. Бонус 100% до 25 000 ₽ + 100 фриспинов. Еженедельные турниры, кэшбек.',
    fullDescription: `SlotV — онлайн-казино с акцентом на слоты от топовых провайдеров. Лицензия Curaçao. Бонус 100% до 25 000 ₽ + 100 фриспинов за первый депозит. Еженедельные слот-турниры с призовыми фондами. Кэшбек до 10% для постоянных игроков.`,
    rating: 4.1, userRating: 4.0, reviewCount: 6400, type: 'casino', founded: 2016,
    license: 'Curaçao eGaming', website: 'https://slotv.com',
    mainBonus: '100% до 25 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% + 100 фриспинов', amount: '100% до 25 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Огромный выбор слотов', 'Турниры с призовыми', 'Кэшбек'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#7c3aed',
  },
  {
    slug: 'casino-x', name: 'Casino-X', logo: '✖️',
    tagline: 'Пакет до 300 000 ₽ на 4 депозита',
    description: 'Casino-X — международное казино с пакетом до 300 000 ₽ на 4 депозита. Более 3000 слотов, live-казино, эксклюзивные игры.',
    fullDescription: `Casino-X работает с 2012 года по лицензии Curaçao. Приветственный пакет до 300 000 ₽ на первые 4 депозита. Более 3000 слотов от 60+ провайдеров. Live-казино с русскоязычными дилерами. Эксклюзивные игры и turbo-режим.`,
    rating: 4.2, userRating: 4.0, reviewCount: 9100, type: 'casino', founded: 2012,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'До 300 000 ₽ на 4 депозита',
    bonuses: [
      { type: 'deposit', title: 'Пакет на 4 депозита', description: 'Суммарно до 300 000 ₽', amount: 'до 300 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['До 300 000 ₽ пакет', '3000+ слотов', 'Русскоязычные дилеры'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#1d4ed8',
  },
  {
    slug: 'pin-up', name: 'Pin-Up Casino', logo: '📌',
    tagline: 'Бонус 120% до 100 000 ₽ + 250 фриспинов',
    description: 'Pin-Up Casino — популярное казино с бонусом 120% до 100 000 ₽ + 250 фриспинов. Авиатор, краш-игры, слоты, живое казино.',
    fullDescription: `Pin-Up Casino работает с 2016 года по лицензии Curaçao. Приветственный бонус 120% до 100 000 ₽ + 250 фриспинов за первый депозит. Авиатор, краш-игры, тысячи слотов. Живое казино с реальными дилерами. Быстрые игры для любителей динамики.`,
    rating: 4.3, userRating: 4.2, reviewCount: 14200, type: 'casino', founded: 2016,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '120% до 100 000 ₽ + 250 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '120% + 250 фриспинов', amount: '120% до 100 000 ₽', wagering: '50x', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек', description: 'Еженедельный кэшбек', amount: 'до 10%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['120% до 100 000 ₽', '250 фриспинов', 'Авиатор', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Вейджер x50'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#ec4899',
  },
  {
    slug: 'vavada', name: 'Vavada', logo: '🌀',
    tagline: '100 фриспинов без депозита + бонус 100%',
    description: 'Vavada — казино с бездепозитным бонусом 100 фриспинов за регистрацию. Бонус 100% до 50 000 ₽ за первый депозит.',
    fullDescription: `Vavada работает с 2017 года по лицензии Curaçao. Уникальное предложение: 100 фриспинов без депозита просто за регистрацию. Плюс приветственный бонус 100% до 50 000 ₽ за первый депозит. Тысячи слотов, live-казино, программа лояльности с 12 уровнями.`,
    rating: 4.4, userRating: 4.2, reviewCount: 10500, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100 FS без депозита + 100%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Бесплатные спины за регистрацию', amount: '100 фриспинов', wagering: '60x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 50 000 ₽ за первый депозит', amount: '100% до 50 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', 'Бонус 100%', '12 уровней лояльности', 'Тысячи слотов'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Вейджер x60 на бездеп'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Без депозита', accentColor: '#7c3aed',
  },
  {
    slug: 'cat-casino', name: 'Cat Casino', logo: '🐱',
    tagline: '100% до 30 000 ₽ + 100 фриспинов',
    description: 'Cat Casino — уютное онлайн-казино с кошачьей тематикой. Бонус 100% до 30 000 ₽ + 100 фриспинов. Удобное приложение.',
    fullDescription: `Cat Casino работает с 2020 года по лицензии Curaçao. Приветственный бонус 100% до 30 000 ₽ + 100 фриспинов за первый депозит. Уникальный дизайн, большой выбор слотов, live-казино. Программа лояльности с наградами.`,
    rating: 4.1, userRating: 4.0, reviewCount: 5600, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100% до 30 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% + 100 фриспинов', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Уникальный дизайн', 'Бонус 100% + FS', 'Удобное приложение'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 300000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#f97316',
  },
  {
    slug: 'loki-casino', name: 'Loki Casino', logo: '🐍',
    tagline: '100% до 50 000 ₽ + 200 фриспинов на 4 депозита',
    description: 'Loki Casino — казино с бонусом на 4 депозита: суммарно до 50 000 ₽ + 200 фриспинов. Live-казино, турниры.',
    fullDescription: `Loki Casino работает с 2017 года по лицензии Curaçao. Бонус на 4 первых депозита: суммарно до 50 000 ₽ + 200 фриспинов. Ежедневные турниры слотов с призовыми фондами. Live-казино с реальными дилерами. Программа лояльности.`,
    rating: 4.0, userRating: 3.9, reviewCount: 4800, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'До 50 000 ₽ + 200 FS',
    bonuses: [
      { type: 'deposit', title: 'Пакет на 4 депозита', description: 'До 50 000 ₽ + 200 FS суммарно', amount: 'до 50 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Бонус на 4 депозита', 'Ежедневные турниры', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#065f46',
  },
  {
    slug: 'fresh-casino', name: 'Fresh Casino', logo: '🍋',
    tagline: '150% до 75 000 ₽ + 200 фриспинов',
    description: 'Fresh Casino — свежее онлайн-казино с бонусом 150% до 75 000 ₽ + 200 фриспинов. Программа лояльности, кэшбек до 15%.',
    fullDescription: `Fresh Casino работает по лицензии Curaçao. Приветственный бонус 150% до 75 000 ₽ + 200 фриспинов за первый депозит. Программа лояльности с 6 уровнями. Кэшбек до 15% для постоянных игроков. Еженедельные турниры.`,
    rating: 4.1, userRating: 3.9, reviewCount: 4300, type: 'casino', founded: 2019,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '150% до 75 000 ₽ + 200 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '150% + 200 фриспинов', amount: '150% до 75 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек', description: 'До 15% кэшбека', amount: 'до 15%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['150% + 200 фриспинов', 'Кэшбек до 15%', 'Программа лояльности'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#65a30d',
  },
  {
    slug: 'riobet', name: 'Riobet', logo: '🎭',
    tagline: '100 фриспинов без депозита за регистрацию',
    description: 'Riobet — одно из первых казино СНГ с бездепозитным бонусом 100 фриспинов. Работает с 2014 года, тысячи слотов.',
    fullDescription: `Riobet работает с 2014 года по лицензии Curaçao. Один из пионеров рынка СНГ. Уникальный бездепозитный бонус: 100 фриспинов просто за регистрацию. Тысячи слотов, live-казино. Программа лояльности Riobet Club.`,
    rating: 4.0, userRating: 3.9, reviewCount: 8900, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: '100 FS без депозита',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Бесплатные спины за регистрацию', amount: '100 фриспинов', wagering: '30x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['100 FS без депозита', 'С 2014 года', 'Riobet Club'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#b91c1c',
  },
  {
    slug: 'bet365', name: 'Bet365', logo: '🌍',
    tagline: 'Крупнейший букмекер мира с прямыми трансляциями',
    description: 'Bet365 — крупнейший мировой букмекер. Прямые трансляции 140 000+ событий в год. Широкая линия на все виды спорта.',
    fullDescription: `Bet365 — крупнейший в мире букмекер по объёму ставок. Более 140 000 прямых спортивных трансляций в год. Ставки на 30+ видов спорта, live-казино, покер. Мобильное приложение признано лучшим в индустрии. Работает по лицензии Мальты и Гибралтара.`,
    rating: 4.5, userRating: 4.3, reviewCount: 35000, type: 'both', founded: 2000,
    license: 'Malta Gaming Authority, Gibraltar', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['140 000+ прямых трансляций', 'Крупнейший в мире', 'Лучшее приложение', 'Все виды спорта'],
    cons: ['Ограниченная доступность в РФ', 'Нет русскоязычной поддержки'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 500000, time: '1-3 дня' },
      { name: 'PayPal', icon: '💸', minDeposit: 300, maxWithdrawal: 500000, time: '1-2 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Мировой №1', accentColor: '#15803d',
  },
  {
    slug: 'betway', name: 'Betway', logo: '🎯',
    tagline: 'Международный букмекер — спорт и казино',
    description: 'Betway — крупный международный оператор. Спортивные ставки + казино. Лицензии Malta и UK Gambling Commission.',
    fullDescription: `Betway работает с 2006 года. Один из крупнейших европейских операторов. Ставки на 30+ видов спорта, live-казино, слоты. Лицензии Malta Gaming Authority и UK Gambling Commission. Спонсор крупных спортивных событий.`,
    rating: 4.2, userRating: 4.0, reviewCount: 18000, type: 'both', founded: 2006,
    license: 'Malta Gaming Authority', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Международный оператор', 'Лицензии Malta + UK', 'Спорт + казино', 'Спонсор топ-событий'],
    cons: ['Ограниченная доступность в РФ', 'Нет русского языка'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 500000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#0e4d92',
  },
  {
    slug: 'william-hill', name: 'William Hill', logo: '🎩',
    tagline: 'Один из старейших букмекеров мира с 1934 года',
    description: 'William Hill работает с 1934 года — один из старейших и авторитетнейших букмекеров мира. Широкая линия, Live-казино.',
    fullDescription: `William Hill — легенда мировой индустрии ставок с 1934 года. Один из крупнейших операторов Великобритании. Ставки на все виды спорта, live-казино, бинго, покер. Лицензия UK Gambling Commission.`,
    rating: 4.1, userRating: 3.9, reviewCount: 22000, type: 'both', founded: 1934,
    license: 'UK Gambling Commission', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['С 1934 года', 'Легенда индустрии', 'Широкая линия', 'Лицензия UK'],
    cons: ['Ограниченная доступность в РФ', 'Только английский'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 500000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#065f46',
  },
  {
    slug: 'bwin', name: 'Bwin', logo: '🏋️',
    tagline: 'Один из первых онлайн-букмекеров мира с 1997 года',
    description: 'Bwin работает с 1997 года. Спонсор Реал Мадрид и других топ-клубов. Ставки на спорт, покер, казино.',
    fullDescription: `Bwin — один из пионеров онлайн-беттинга с 1997 года. Спонсор Реал Мадрид, Байер, Атлетико. Широкая спортивная линия, покер-рум, онлайн-казино. Лицензии Malta Gaming Authority и Gibraltar. Один из брендов GVC/Entain Group.`,
    rating: 4.1, userRating: 3.9, reviewCount: 16000, type: 'both', founded: 1997,
    license: 'Malta Gaming Authority', website: 'https://1wfypv.com/casino/list?open=register&p=q4lj',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '5x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['С 1997 года', 'Спонсор топ-клубов', 'Казино + покер + спорт'],
    cons: ['Ограниченная доступность в РФ', 'Нет русского языка'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 300000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#1e3a5f',
  },
  {
    slug: 'betfair', name: 'Betfair', logo: '♟️',
    tagline: 'Крупнейшая биржа ставок в мире',
    description: 'Betfair — крупнейшая в мире биржа ставок. Игроки делают ставки друг против друга, а не против букмекера. Максимальные коэффициенты.',
    fullDescription: `Betfair — крупнейшая в мире биржа ставок, основанная в 2000 году. Уникальная модель: игроки ставят против друг друга, а не против букмекера. Это обеспечивает значительно более высокие коэффициенты, чем у классических букмекеров. Лицензия UK Gambling Commission и Malta.`,
    rating: 4.4, userRating: 4.2, reviewCount: 25000, type: 'betting', founded: 2000,
    license: 'UK Gambling Commission', website: 'https://betfair.com',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'registration', title: 'Приветственный бонус', description: 'Бонус за первые ставки', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['Биржа ставок — макс. коэффициенты', 'С 2000 года', 'Лицензия UK', 'Уникальная модель'],
    cons: ['Сложно для новичков', 'Ограниченная доступность в РФ'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 500000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: 'Биржа ставок', accentColor: '#ffd700',
  },
  {
    slug: 'unibet', name: 'Unibet', logo: '🦄',
    tagline: 'Европейский букмекер-казино с 1997 года',
    description: 'Unibet — один из крупнейших европейских операторов с 1997 года. Ставки на спорт, онлайн-казино, покер, живое казино.',
    fullDescription: `Unibet работает с 1997 года как часть Kindred Group. Один из крупнейших европейских онлайн-операторов. Ставки на 30+ видов спорта, live-казино с эксклюзивными играми, онлайн-покер. Лицензии Malta, UK, Швеция.`,
    rating: 4.2, userRating: 4.0, reviewCount: 19000, type: 'both', founded: 1997,
    license: 'Malta Gaming Authority', website: 'https://unibet.com',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['С 1997 года', 'Kindred Group', 'Казино + спорт + покер'],
    cons: ['Ограниченная доступность в РФ', 'Нет русского языка'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 400000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#059669',
  },
  {
    slug: 'parimatch-int', name: 'Parimatch Int', logo: '🌐',
    tagline: 'Оригинальный Parimatch для международного рынка',
    description: 'Parimatch — оригинальный международный бренд. Ставки на спорт, казино, Live. Работает на рынках СНГ и мира (кроме РФ после ребрендинга PARI).',
    fullDescription: `Parimatch International — международный бренд, работающий в странах СНГ (кроме РФ, где ребрендировался в PARI) и на мировом рынке. Широкая линия на спорт, live-казино, слоты. Лицензия Curaçao.`,
    rating: 4.2, userRating: 4.0, reviewCount: 14000, type: 'both', founded: 1994,
    license: 'Curaçao eGaming', website: 'https://parimatch.com',
    mainBonus: 'Приветственный бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус за первый депозит', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 300,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['С 1994 года', 'Известный бренд СНГ', 'Казино + спорт'],
    cons: ['В РФ ребрендировался в PARI', 'Зарубежная лицензия'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 300, maxWithdrawal: 300000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#dc2626',
  },
  {
    slug: 'ggbet', name: 'GGbet', logo: '🎮',
    tagline: 'Лучшие ставки на киберспорт + казино',
    description: 'GGbet — специалист по киберспорту. CS2, Dota 2, LoL, Valorant. Бонус 100% до 50 000 ₽. Официальный партнёр крупных киберспортивных организаций.',
    fullDescription: `GGbet — ведущий оператор по ставкам на киберспорт. Официальный партнёр NaVi, FaZe Clan, Astralis. Отличная линия на CS2, Dota 2, LoL, Valorant, Overwatch. Бонус 100% до 50 000 ₽ за первый депозит. Казино с популярными слотами.`,
    rating: 4.3, userRating: 4.2, reviewCount: 12400, type: 'both', founded: 2016,
    license: 'Curaçao eGaming', website: 'https://ggbet.com',
    mainBonus: '100% до 50 000 ₽',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 50 000 ₽', amount: '100% до 50 000 ₽', wagering: '5x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Лучший киберспорт в мире', 'Партнёр NaVi, FaZe', 'Широкая линия CS2/Dota2', 'Казино'],
    cons: ['Зарубежная лицензия', 'Сложный вейджер'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Киберспорт Pro', accentColor: '#7c3aed',
  },
  {
    slug: 'sportsbet-io', name: 'Sportsbet.io', logo: '₿',
    tagline: 'Криптовалютный букмекер — Bitcoin, ETH, USDT',
    description: 'Sportsbet.io — ведущий крипто-букмекер. Ставки за Bitcoin, Ethereum, USDT. Мгновенные выплаты, анонимность.',
    fullDescription: `Sportsbet.io — один из ведущих криптовалютных букмекеров. Ставки и выплаты в Bitcoin, Ethereum, Litecoin, USDT и других криптовалютах. Мгновенные выплаты без верификации. Широкая спортивная линия, live-казино, быстрые краш-игры.`,
    rating: 4.2, userRating: 4.0, reviewCount: 8700, type: 'both', founded: 2016,
    license: 'Curaçao eGaming', website: 'https://sportsbet.io',
    mainBonus: 'Крипто-бонус',
    bonuses: [
      { type: 'deposit', title: 'Крипто-бонус', description: 'Бонус за первый депозит в крипте', amount: 'уточняйте на сайте', wagering: '3x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Только криптовалюта', 'Мгновенные выплаты', 'Анонимность', 'Широкая линия'],
    cons: ['Зарубежная лицензия', 'Только крипто — нет рублей'],
    paymentMethods: [
      { name: 'Bitcoin', icon: '₿', minDeposit: 100, maxWithdrawal: 1000000, time: '15 мин' },
      { name: 'Ethereum', icon: '⟠', minDeposit: 100, maxWithdrawal: 1000000, time: '15 мин' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 1000000, time: '15 мин' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: 'Крипто', accentColor: '#f7931a',
  },
  {
    slug: 'stake', name: 'Stake', logo: '💎',
    tagline: 'Топовое крипто-казино с Авиатором и Crash',
    description: 'Stake — крупнейшее крипто-казино мира. Авиатор, Dice, Crash, тысячи слотов. Ставки в Bitcoin, ETH, USDT. Официальный партнёр Drake.',
    fullDescription: `Stake — одно из крупнейших криптовалютных казино мира. Официальный партнёр Drake. Широкий выбор: авиатор, Dice, Crash, Mines, тысячи слотов. Ставки в 20+ криптовалютах. Огромные розыгрыши и VIP-программа.`,
    rating: 4.4, userRating: 4.2, reviewCount: 31000, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming', website: 'https://stake.com',
    mainBonus: 'VIP-программа + ежедневные бонусы',
    bonuses: [
      { type: 'cashback', title: 'Rakeback', description: 'Ежедневный, еженедельный, ежемесячный кэшбек', amount: 'до 15%', wagering: '1x', validDays: 1 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: false,
    pros: ['Крупнейшее крипто-казино', 'Партнёр Drake', 'Авиатор, Crash, Dice', 'Мгновенные выплаты'],
    cons: ['Только криптовалюта', 'Зарубежная лицензия'],
    paymentMethods: [
      { name: 'Bitcoin', icon: '₿', minDeposit: 100, maxWithdrawal: 1000000, time: '5-15 мин' },
      { name: 'Ethereum', icon: '⟠', minDeposit: 100, maxWithdrawal: 1000000, time: '5-15 мин' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 1000000, time: '5-15 мин' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Крипто топ', accentColor: '#10b981',
  },
  {
    slug: 'bc-game', name: 'BC.Game', logo: '🎮',
    tagline: 'Крипто-казино с уникальными играми и NFT',
    description: 'BC.Game — инновационное крипто-казино с NFT и уникальными играми. Авиатор, Crash, 50+ криптовалют, огромное комьюнити.',
    fullDescription: `BC.Game — инновационное крипто-казино с большим комьюнити. Поддержка 50+ криптовалют. Уникальные игры: BC Originals. NFT-компоненты. Ставки на спорт, слоты, live-казино. Активные чат-боты и розыгрыши для комьюнити.`,
    rating: 4.1, userRating: 4.0, reviewCount: 9200, type: 'both', founded: 2019,
    license: 'Curaçao eGaming', website: 'https://bc.game',
    mainBonus: 'Приветственный крипто-бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: 'Бонус на первый криптодепозит', amount: 'уточняйте на сайте', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['50+ криптовалют', 'NFT-элементы', 'Большое комьюнити', 'BC Originals'],
    cons: ['Только криптовалюта', 'Зарубежная лицензия'],
    paymentMethods: [
      { name: 'Bitcoin', icon: '₿', minDeposit: 100, maxWithdrawal: 1000000, time: '5-15 мин' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 1000000, time: '5-15 мин' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#f59e0b',
  },
  {
    slug: 'cazino-kosmos', name: 'Казино Космос', logo: '🚀',
    tagline: '100% до 50 000 ₽ + бесплатные спины',
    description: 'Казино Космос — популярное русскоязычное онлайн-казино. Бонус 100% до 50 000 ₽ + бесплатные спины. Слоты, live-казино.',
    fullDescription: `Казино Космос — популярное русскоязычное онлайн-казино с лицензией Curaçao. Приветственный бонус 100% до 50 000 ₽ + фриспины. Широкий выбор слотов от топовых провайдеров. Live-казино. Программа лояльности.`,
    rating: 4.0, userRating: 3.9, reviewCount: 6300, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming', website: 'https://casinokosmos.com',
    mainBonus: '100% до 50 000 ₽',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% + фриспины', amount: '100% до 50 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Русский язык', 'Бонус до 50 000 ₽', 'Слоты и live'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#1e3a8a',
  },
  {
    slug: 'legzo', name: 'Legzo Casino', logo: '🎭',
    tagline: '100 фриспинов без депозита',
    description: 'Legzo Casino — современное казино с бездепозитным бонусом 100 фриспинов за регистрацию. Тысячи слотов, быстрые выплаты.',
    fullDescription: `Legzo Casino работает по лицензии Curaçao. Уникальное предложение: 100 фриспинов без депозита за регистрацию. Тысячи слотов от топовых провайдеров. Live-казино. Программа лояльности с наградами. Быстрые выплаты.`,
    rating: 4.0, userRating: 3.9, reviewCount: 3800, type: 'casino', founded: 2021,
    license: 'Curaçao eGaming', website: 'https://legzo.casino',
    mainBonus: '100 FS без депозита',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '60x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: false,
    pros: ['100 FS без депозита', 'Тысячи слотов', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Молодая платформа', 'Высокий вейджер x60'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#9333ea',
  },
  {
    slug: 'brillx', name: 'Brillx', logo: '💎',
    tagline: '200% до 80 000 ₽ + кэшбек 15%',
    description: 'Brillx — казино с бонусом 200% до 80 000 ₽ за первый депозит. Кэшбек до 15%. Слоты, рулетка, live-казино.',
    fullDescription: `Brillx работает по лицензии Curaçao. Приветственный бонус 200% до 80 000 ₽ за первый депозит. Кэшбек до 15% еженедельно. Слоты от Pragmatic Play, NetEnt, Evolution Gaming. Live-казино с реальными дилерами.`,
    rating: 4.0, userRating: 3.9, reviewCount: 4100, type: 'casino', founded: 2019,
    license: 'Curaçao eGaming', website: 'https://brillx.casino',
    mainBonus: '200% до 80 000 ₽',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '200% до 80 000 ₽', amount: '200% до 80 000 ₽', wagering: '50x', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек', description: 'До 15% еженедельно', amount: 'до 15%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['200% до 80 000 ₽', 'Кэшбек 15%', 'Топовые провайдеры'],
    cons: ['Зарубежная лицензия', 'Вейджер x50'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#0284c7',
  },
  {
    slug: 'goxbet', name: 'GoxBet', logo: '🌊',
    tagline: '100% до 50 000 ₽ + ставки на спорт',
    description: 'GoxBet — казино и букмекер. Бонус 100% до 50 000 ₽ + ставки на спорт. Live-казино, авиатор, слоты.',
    fullDescription: `GoxBet — оператор с казино и спортивными ставками в одном. Лицензия Curaçao. Приветственный бонус 100% до 50 000 ₽. Авиатор, краш-игры, тысячи слотов. Спортивная линия на 20+ видов спорта.`,
    rating: 4.0, userRating: 3.8, reviewCount: 3600, type: 'both', founded: 2018,
    license: 'Curaçao eGaming', website: 'https://goxbet.com',
    mainBonus: '100% до 50 000 ₽',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 50 000 ₽', amount: '100% до 50 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Казино + спорт', 'Авиатор', 'Широкая линия'],
    cons: ['Зарубежная лицензия', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#0e7490',
  },
  {
    slug: 'casinooon', name: 'Casinooon', logo: '🎪',
    tagline: '150% до 60 000 ₽ + 200 фриспинов',
    description: 'Casinooon — казино с бонусом 150% до 60 000 ₽ + 200 фриспинов. Live-казино, слоты, ежедневные турниры.',
    fullDescription: `Casinooon работает по лицензии Curaçao. Приветственный бонус 150% до 60 000 ₽ + 200 фриспинов за первый депозит. Ежедневные слот-турниры. Live-казино с Evolution Gaming. Кэшбек до 10%.`,
    rating: 4.0, userRating: 3.8, reviewCount: 4700, type: 'casino', founded: 2018,
    license: 'Curaçao eGaming', website: 'https://casinooon.com',
    mainBonus: '150% до 60 000 ₽ + 200 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '150% + 200 FS', amount: '150% до 60 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['150% + 200 FS', 'Evolution Gaming', 'Ежедневные турниры'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#c026d3',
  },
  {
    slug: 'hotslots', name: 'HotSlots', logo: '🔥',
    tagline: '100% до 40 000 ₽ + 150 FS',
    description: 'HotSlots — казино с акцентом на горячие слоты. Бонус 100% до 40 000 ₽ + 150 фриспинов. Ежедневные турниры.',
    fullDescription: `HotSlots работает по лицензии Curaçao. Бонус 100% до 40 000 ₽ + 150 фриспинов за первый депозит. Более 2000 слотов от 30+ провайдеров. Ежедневные турниры. Кэшбек по программе лояльности.`,
    rating: 3.9, userRating: 3.8, reviewCount: 3400, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://hotslots.com',
    mainBonus: '100% до 40 000 ₽ + 150 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% + 150 FS', amount: '100% до 40 000 ₽', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['2000+ слотов', '150 фриспинов', 'Ежедневные турниры'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 150000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#ef4444',
  },
  {
    slug: 'bitstarz', name: 'BitStarz', logo: '⭐',
    tagline: 'Лучшее биткоин-казино 2026 — 5 BTC + 180 FS',
    description: 'BitStarz — многократный победитель награды "Лучшее биткоин-казино". Бонус 5 BTC + 180 фриспинов. Мгновенные выплаты в крипте и рублях.',
    fullDescription: `BitStarz работает с 2014 года по лицензии Curaçao. Многократный обладатель награды "Лучшее криптовалютное казино мира". Приветственный пакет 5 BTC + 180 фриспинов на 4 первых депозита. Мгновенные выплаты в Bitcoin, ETH и рублях. Более 3600 слотов.`,
    rating: 4.5, userRating: 4.3, reviewCount: 21000, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://bitstarz.com',
    mainBonus: '5 BTC + 180 FS',
    bonuses: [
      { type: 'deposit', title: 'Пакет 5 BTC + 180 FS', description: 'На первые 4 депозита', amount: '5 BTC + 180 фриспинов', wagering: '40x', validDays: 30 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 200,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Лучшее биткоин-казино', '5 BTC + 180 FS', 'Мгновенные выплаты', '3600+ слотов'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Bitcoin', icon: '₿', minDeposit: 200, maxWithdrawal: 1000000, time: '5-15 мин' },
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 200, maxWithdrawal: 200000, time: '1-3 дня' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Крипто топ', accentColor: '#f59e0b',
  },
  {
    slug: 'pokerdom', name: 'PokerDom', logo: '🃏',
    tagline: 'Крупнейший покер-рум СНГ + казино и букмекер',
    description: 'PokerDom — крупнейший покер-рум в странах СНГ. Также казино и ставки на спорт. Бонус 100% до 100 000 ₽ + 50 000 ₽ на покер.',
    fullDescription: `PokerDom — крупнейший покер-рум в странах СНГ с аудиторией сотни тысяч игроков. Также предлагает казино и ставки на спорт. Приветственный бонус 100% до 100 000 ₽ в казино + бонус до 50 000 ₽ на покер. Лицензия Curaçao.`,
    rating: 4.2, userRating: 4.0, reviewCount: 14500, type: 'both', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://pokerdom.com',
    mainBonus: '100% до 100 000 ₽ + покер-бонус',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 100 000 ₽ в казино', amount: '100% до 100 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'registration', title: 'Покерный бонус', description: 'До 50 000 ₽ на покерные столы', amount: 'до 50 000 ₽', wagering: 'обороты', validDays: 30 },
    ],
    hasLiveBetting: true, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['Крупнейший покер СНГ', 'Казино + спорт + покер', 'Бонус до 100 000 ₽'],
    cons: ['Зарубежная лицензия', 'Сложный вейджер'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 300000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Покер #1', accentColor: '#7c3aed',
  },
  {
    slug: 'ggpoker', name: 'GGPoker', logo: '♠️',
    tagline: 'Крупнейший покер-рум мира + казино',
    description: 'GGPoker — крупнейший покер-рум мира. Миллионные турниры, казино. Официальный спонсор WSOP.',
    fullDescription: `GGPoker — крупнейший онлайн-покер-рум мира. Официальный спонсор WSOP (World Series of Poker). Регулярные турниры с призовыми миллионы долларов. Уникальные форматы покера. Казино с тысячами слотов.`,
    rating: 4.3, userRating: 4.1, reviewCount: 42000, type: 'casino', founded: 2014,
    license: 'Malta Gaming Authority', website: 'https://ggpoker.com',
    mainBonus: 'Покерный бонус 100%',
    bonuses: [
      { type: 'deposit', title: 'Покерный бонус', description: '100% на первый депозит', amount: 'уточняйте на сайте', wagering: 'обороты', validDays: 90 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: false, hasCashback: false, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Крупнейший покер-рум мира', 'Спонсор WSOP', 'Миллионные турниры'],
    cons: ['В основном покер', 'Ограниченная доступность в РФ'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 1000000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: 'Покер мира', accentColor: '#15803d',
  },
]

export const getFeatured = () => services.filter(s => s.featured)
export const getPopular = () => services.filter(s => s.popular)
export const getBySlug = (slug: string) => services.find(s => s.slug === slug)
export const getCasinos = () => services.filter(s => s.type === 'casino' || s.type === 'both')
export const getBetting = () => services.filter(s => s.type === 'betting' || s.type === 'both')
