import { Service } from '@/types'

export const services: Service[] = [
  {
    slug: 'jozz', name: 'Jozz Casino', logo: '🃏',
    tagline: '100% до 30 000 ₽ + 100 фриспинов за первый депозит',
    description: 'Jozz Casino — современное онлайн-казино с бонусом 100% до 30 000 ₽ + 100 фриспинов. Слоты, live-казино, быстрые выплаты.',
    fullDescription: `Jozz Casino работает по лицензии Curaçao. Приветственный бонус 100% до 30 000 ₽ + 100 фриспинов за первый депозит. Более 2000 слотов от Pragmatic Play, NetEnt, BGaming. Live-казино с реальными дилерами. Программа лояльности с наградами.`,
    rating: 4.47, userRating: 4.3, reviewCount: 5800, type: 'casino', founded: 2019,
    license: 'Curaçao eGaming', website: 'https://jozz.com',
    refUrl: 'https://jozz-promo1.com/alt/jozz/registration?bbb519bee13dc37a3b95625adb955eb3',
    mainBonus: '100% до 30 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 30 000 ₽ + 100 фриспинов', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'Фриспины за депозит', description: '100 фриспинов за первый депозит', amount: '100 фриспинов', wagering: '40x', validDays: 5 },
      { type: 'cashback', title: 'Кэшбек', description: 'Еженедельный кэшбек до 10%', amount: 'до 10%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'Reload пятница', description: 'Бонус на пополнение по пятницам', amount: 'до 25%', wagering: '5x', validDays: 3 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['100% + 100 фриспинов', 'Быстрые выплаты', 'Кэшбек до 10%', '2000+ слотов'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#6366f1',
  },
  {
    slug: 'booi', name: 'Booi Casino', logo: '🐯',
    tagline: '100 фриспинов без депозита + 100% на первый',
    description: 'Booi Casino — казино с бездепозитным бонусом 100 фриспинов за регистрацию и 100% до 30 000 ₽ на первый депозит.',
    fullDescription: `Booi Casino работает по лицензии Curaçao. Бездепозитный бонус 100 фриспинов просто за регистрацию. Плюс 100% до 30 000 ₽ за первый депозит. Слоты, live-казино, программа лояльности. Поддержка 24/7 на русском языке.`,
    rating: 4.44, userRating: 4.2, reviewCount: 6200, type: 'casino', founded: 2018,
    license: 'Curaçao eGaming', website: 'https://booi.com',
    refUrl: 'https://booi-promo.com/alt/booi/sign-up?0d4942b3a7705181eff163bbd56a31d1',
    mainBonus: '100 FS без депозита + 100%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Бесплатные спины за регистрацию', amount: '100 фриспинов', wagering: '50x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 30 000 ₽', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'Фриспины за депозит', description: '50 фриспинов за каждое пополнение от 500 ₽', amount: '50 фриспинов', wagering: '30x', validDays: 3 },
      { type: 'reload', title: 'Пятничный бонус', description: 'Бонус на пополнение по пятницам', amount: 'до 30%', wagering: '5x', validDays: 3 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', 'Бонус 100%', 'Поддержка на русском', 'Быстрые выплаты'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Без депозита', accentColor: '#f59e0b',
  },
  {
    slug: 'fugu', name: 'FUGU Casino', logo: '🐡', logoUrl: 'https://s3-eu-west-1.amazonaws.com/tpd/logos/69848d4c2706dd2e7b43d60f/0x0.png',
    tagline: '200% до 50 000 ₽ + 200 фриспинов на первый депозит',
    description: 'FUGU Casino — динамичное онлайн-казино с щедрым бонусом 200% до 50 000 ₽ + 200 фриспинов. Слоты, live-казино, быстрые выплаты.',
    fullDescription: `FUGU Casino работает по лицензии Curaçao. Щедрый приветственный бонус 200% до 50 000 ₽ + 200 фриспинов за первый депозит. Тысячи слотов от ведущих провайдеров. Live-казино с реальными дилерами. Кэшбек до 20%, программа лояльности.`,
    rating: 4.41, userRating: 4.2, reviewCount: 7200, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://fuguway65.com/cebe2a83e',
    refUrl: 'https://fuguway65.com/cebe2a83e',
    mainBonus: '200% до 50 000 ₽ + 200 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус 200%', description: '200% до 50 000 ₽ + 200 фриспинов', amount: '200% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: '200 фриспинов', description: '200 фриспинов за первый депозит', amount: '200 фриспинов', wagering: '40x', validDays: 7 },
      { type: 'cashback', title: 'FUGU кэшбек', description: 'Еженедельный кэшбек до 20%', amount: 'до 20%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'FUGU Reload', description: 'Еженедельный бонус на пополнение', amount: 'до 35%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['200% + 200 фриспинов', 'Кэшбек до 20%', 'Быстрые выплаты', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'ТОП', accentColor: '#f97316',
  },
  {
    slug: '1win', name: '1Win', logo: '🏅',
    tagline: 'Мегабонус 500% на первые 4 депозита',
    description: '1Win — 500% суммарно до 200 000 ₽ на первые 4 депозита. Казино + спорт, Авиатор, 1Win Games.',
    fullDescription: `1Win основан в 2016 году. Пакет на 4 депозита: 200%+150%+100%+50%, суммарно до 200 000 ₽ (до 50 000 ₽ на каждый). Казино с тысячами слотов, Авиатор, уникальные быстрые игры 1Win Games.`,
    rating: 4.5, userRating: 4.3, reviewCount: 12350, type: 'casino', founded: 2016,
    license: 'Curaçao eGaming (8048/JAZ)', website: 'https://1win.com',
    refUrl: 'https://1wguup.com/casino/list?open=register&p=q4lj',
    mainBonus: '500% до 200 000 ₽ на 4 депозита',
    bonuses: [
      { type: 'deposit', title: 'Мегапакет', description: '200%+150%+100%+50% на первые 4 депозита', amount: 'до 200 000 ₽', wagering: 'ординар кф 3.0+, 5% за выигрыш', validDays: 30 },
      { type: 'cashback', title: 'Кэшбек казино', description: 'Еженедельный кэшбек', amount: 'до 30%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'Бонус на пополнение', description: 'Еженедельный бонус для постоянных игроков', amount: 'до 50%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 100,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['500% до 200 000 ₽ — лучший на рынке', 'Авиатор и 1Win Games', 'Депозит от 100 ₽'],
    cons: ['Вейджер кф от 3.0', 'Зарубежная лицензия'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 100000, time: '2-4 часа' },
    ],
    screenshots: [],
    faq: [{ question: 'Как работает бонус 500%?', answer: '200% за первый депозит, 150% за второй, 100% за третий, 50% за четвёртый. Максимум 50 000 ₽ на каждый.' }],
    reviews: [{ author: 'Дмитрий С.', rating: 5, date: '2026-03-01', text: 'Бонус 500% — реально лучшее предложение на рынке.', avatar: 'ДС' }],
    featured: true, popular: true, badge: 'Лучший бонус', accentColor: '#a855f7',
  },
  {
    slug: 'vavada', name: 'Vavada', logo: '🌀',
    tagline: '100 фриспинов без депозита + бонус 100%',
    description: 'Vavada — казино с бездепозитным бонусом 100 фриспинов за регистрацию. Бонус 100% до 50 000 ₽ за первый депозит.',
    fullDescription: `Vavada работает с 2017 года по лицензии Curaçao. Уникальное предложение: 100 фриспинов без депозита просто за регистрацию. Плюс приветственный бонус 100% до 50 000 ₽ за первый депозит. Тысячи слотов, live-казино, программа лояльности с 12 уровнями.`,
    rating: 4.4, userRating: 4.2, reviewCount: 10500, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming', website: 'https://vavada.com',
    refUrl: 'https://gate707.com/?promo=01ab618f-1b7a-420f-8614-0b959ba0482b&target=register',
    mainBonus: '100 FS без депозита + 100%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Бесплатные спины за регистрацию', amount: '100 фриспинов', wagering: '60x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 50 000 ₽ за первый депозит', amount: '100% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'Фриспины за депозит', description: '100 фриспинов за депозит от 500 ₽', amount: '100 фриспинов', wagering: '40x', validDays: 5 },
      { type: 'reload', title: 'Reload-бонус', description: 'Еженедельный бонус до 40% на пополнение', amount: 'до 40%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: false, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', 'Бонус 100%', '12 уровней лояльности', 'Тысячи слотов'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Вейджер x60 на бездеп'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: 'Без депозита', accentColor: '#7c3aed',
  },
  {
    slug: 'ramenbet', name: 'RamenBet', logo: '🍜',
    tagline: '150 фриспинов без депозита за регистрацию',
    description: 'RamenBet — необычное казино с азиатским стилем и бездепозитным бонусом 150 фриспинов. Огромный выбор слотов, кэшбек.',
    fullDescription: `RamenBet работает по лицензии Curaçao. Оригинальное казино с азиатской тематикой. Бездепозитный бонус 150 фриспинов за регистрацию. Бонус 100% до 50 000 ₽ за первый депозит. Кэшбек до 15%, программа лояльности.`,
    rating: 4.85, userRating: 4.7, reviewCount: 5400, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://ramenbet.com',
    refUrl: 'https://52377.call2me.xyz/ru/registration?partner=p52377p3327389pe482',
    mainBonus: '150 FS без депозита',
    bonuses: [
      { type: 'registration', title: '150 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '150 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 50 000 ₽', amount: '100% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'Фриспины за депозит', description: '50 фриспинов за каждый депозит от 500 ₽', amount: '50 фриспинов', wagering: '35x', validDays: 3 },
      { type: 'cashback', title: 'Кэшбек RamenBet', description: 'Еженедельный кэшбек до 15%', amount: 'до 15%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'Азиатский reload', description: 'Еженедельный бонус на пополнение', amount: 'до 30%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['150 FS без депозита', 'Оригинальный дизайн', 'Кэшбек до 15%', 'Быстрые выплаты'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: true, popular: true, badge: 'Без депозита', accentColor: '#dc2626',
  },
  {
    slug: 'casino-x', name: 'Casino-X', logo: '✖️', logoUrl: '/logos/casino-x.png',
    tagline: 'Пакет до 300 000 ₽ на 4 депозита',
    description: 'Casino-X — международное казино с пакетом до 300 000 ₽ на 4 депозита. Более 3000 слотов, live-казино, эксклюзивные игры.',
    fullDescription: `Casino-X работает с 2012 года по лицензии Curaçao. Приветственный пакет до 300 000 ₽ на первые 4 депозита. Более 3000 слотов от 60+ провайдеров. Live-казино с русскоязычными дилерами. Эксклюзивные игры и turbo-режим.`,
    rating: 4.8, userRating: 4.6, reviewCount: 9100, type: 'casino', founded: 2012,
    license: 'Curaçao eGaming', website: 'https://casino-x.com',
    refUrl: 'https://52377.gameshere.xyz/ru/registration?partner=p52377p3327388p963f',
    mainBonus: 'До 300 000 ₽ на 4 депозита',
    bonuses: [
      { type: 'deposit', title: 'Пакет на 4 депозита', description: 'Суммарно до 300 000 ₽', amount: 'до 300 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'Фриспины за депозит', description: '75 фриспинов за депозит от 500 ₽', amount: '75 фриспинов', wagering: '40x', validDays: 5 },
      { type: 'cashback', title: 'Кэшбек', description: 'Еженедельный кэшбек до 15%', amount: 'до 15%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'Reload Casino-X', description: 'Бонус на пополнение по выходным', amount: 'до 35%', wagering: '5x', validDays: 3 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['До 300 000 ₽ пакет', '3000+ слотов', 'Русскоязычные дилеры'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: true, popular: true, badge: 'ТОП', accentColor: '#1d4ed8',
  },
  {
    slug: 'joycasino', name: 'Joy Casino', logo: '🎉',
    tagline: '100% до 50 000 ₽ + 100 фриспинов',
    description: 'Joy Casino — международное казино с бонусом 100% до 50 000 ₽ + 100 фриспинов. Live-казино, лотереи, программа лояльности.',
    fullDescription: `Joy Casino работает с 2014 года по лицензии Curaçao. Приветственный бонус 100% до 50 000 ₽ + 100 фриспинов. Тысячи слотов от NetEnt, Microgaming, Play'n GO. Live-казино с реальными дилерами, лотереи, виртуальный спорт.`,
    rating: 4.9, userRating: 4.8, reviewCount: 11300, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://joycasino.com',
    refUrl: 'https://52377.call2me.pro/ru/registration?partner=p52377p3327387pf2ab',
    mainBonus: '100% до 50 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 50 000 ₽ + 100 фриспинов', amount: '100% до 50 000 ₽', wagering: '45x', validDays: 30 },
      { type: 'freespins', title: '100 фриспинов за депозит', description: '100 фриспинов за первый депозит', amount: '100 фриспинов', wagering: '45x', validDays: 5 },
      { type: 'cashback', title: 'Joy кэшбек', description: 'Еженедельный кэшбек для постоянных игроков', amount: 'до 12%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'Joy Reload', description: 'Бонус на пополнение по средам', amount: 'до 25%', wagering: '5x', validDays: 3 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: false, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['Бонус до 50 000 ₽', 'Тысячи слотов', 'Live-казино', 'Работает с 2014'],
    cons: ['Зарубежная лицензия', 'Нет букмекера', 'Вейджер x45'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: true, popular: true, badge: 'ТОП', accentColor: '#f43f5e',
  },
  {
    slug: 'riobet', name: 'RioBet', logo: '🎰',
    tagline: '100% до 30 000 ₽ + 100 фриспинов за первый депозит',
    description: 'RioBet — надёжное онлайн-казино с бонусом 100% до 30 000 ₽ + 100 фриспинов. Слоты, live-казино, быстрые выплаты.',
    fullDescription: `RioBet работает по лицензии Curaçao. Приветственный бонус 100% до 30 000 ₽ + 100 фриспинов за первый депозит. Широкий выбор слотов от ведущих провайдеров. Live-казино с реальными дилерами. Кэшбек, программа лояльности.`,
    rating: 4.2, userRating: 4.0, reviewCount: 4100, type: 'casino', founded: 2014,
    license: 'Curaçao eGaming', website: 'https://riobet.com',
    refUrl: 'https://tracker.referislinks.com/link?btag=104352448_486116',
    mainBonus: '100% до 30 000 ₽ + 100 FS',
    bonuses: [
      { type: 'deposit', title: 'Приветственный бонус', description: '100% до 30 000 ₽ + 100 фриспинов', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: '100 фриспинов', description: '100 фриспинов за первый депозит', amount: '100 фриспинов', wagering: '40x', validDays: 5 },
      { type: 'cashback', title: 'RioBet кэшбек', description: 'Кэшбек до 15% еженедельно', amount: 'до 15%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'RioBet Reload', description: 'Еженедельный бонус на пополнение', amount: 'до 30%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: true,
    pros: ['100% + 100 фриспинов', 'Кэшбек до 15%', 'Быстрые выплаты', 'Live-казино'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#e11d48',
  },
  {
    slug: 'monro', name: 'MONRO Casino', logo: '🎬',
    tagline: '100 фриспинов без депозита + 100% на первый',
    description: 'MONRO Casino — элегантное казино с кинематографическим стилем, 100 FS без депозита и 100% до 30 000 ₽.',
    fullDescription: `MONRO Casino работает по лицензии Curaçao. Элегантный кинематографический стиль. Бездепозитный бонус 100 фриспинов за регистрацию. Приветственный бонус 100% до 30 000 ₽. Слоты, live-казино, программа лояльности.`,
    rating: 4.1, userRating: 4.0, reviewCount: 3400, type: 'casino', founded: 2021,
    license: 'Curaçao eGaming', website: 'https://monro.casino',
    refUrl: 'https://mnr-blse21.com/c580ddf65',
    mainBonus: '100 FS без депозита + 100%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 30 000 ₽', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'MONRO фриспины', description: '50 фриспинов за депозит от 500 ₽', amount: '50 фриспинов', wagering: '40x', validDays: 3 },
      { type: 'cashback', title: 'MONRO кэшбек', description: 'Кэшбек до 10% еженедельно', amount: 'до 10%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'MONRO Reload', description: 'Еженедельный бонус на пополнение', amount: 'до 25%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', 'Элегантный дизайн', 'Live-казино', 'Быстрые выплаты'],
    cons: ['Зарубежная лицензия', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#9333ea',
  },
  {
    slug: 'starda', name: 'STARDA Casino', logo: '⭐',
    tagline: '100 фриспинов без депозита + 100% на первый',
    description: 'STARDA Casino — звёздное казино с бездепозитным бонусом 100 фриспинов и 100% до 30 000 ₽ за первый депозит.',
    fullDescription: `STARDA Casino работает по лицензии Curaçao. Бездепозитный бонус 100 фриспинов за регистрацию. Приветственный бонус 100% до 30 000 ₽. Слоты, live-казино, краш-игры Aviator. Кэшбек до 10%.`,
    rating: 4.1, userRating: 4.0, reviewCount: 4800, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://starda.casino',
    refUrl: 'https://stardaway2.com/c3b4d2ce8',
    mainBonus: '100 FS без депозита + 100%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: 'Бонус 100%', description: '100% до 30 000 ₽', amount: '100% до 30 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'STARDA фриспины', description: '50 фриспинов за депозит от 500 ₽', amount: '50 фриспинов', wagering: '40x', validDays: 3 },
      { type: 'cashback', title: 'STARDA кэшбек', description: 'Кэшбек до 10% еженедельно', amount: 'до 10%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'STARDA Reload', description: 'Звёздный бонус на пополнение', amount: 'до 25%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', 'Aviator', 'Кэшбек до 10%', 'Быстрые выплаты'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#f59e0b',
  },
  {
    slug: 'jet', name: 'JET Casino', logo: '✈️',
    tagline: '100 фриспинов без депозита + 150% на первый',
    description: 'JET Casino — стремительное казино с бездепозитным бонусом 100 фриспинов и 150% до 50 000 ₽ за первый депозит.',
    fullDescription: `JET Casino работает по лицензии Curaçao. Бездепозитный бонус 100 фриспинов за регистрацию. Приветственный бонус 150% до 50 000 ₽. Слоты от ведущих провайдеров, live-казино. Быстрые выплаты, программа лояльности.`,
    rating: 4.2, userRating: 4.0, reviewCount: 5200, type: 'casino', founded: 2021,
    license: 'Curaçao eGaming', website: 'https://jet.casino',
    refUrl: 'https://jetb-intsemed3.com/c0d583288',
    mainBonus: '100 FS без депозита + 150%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: '150% бонус', description: '150% до 50 000 ₽', amount: '150% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'JET фриспины', description: '75 фриспинов за депозит от 500 ₽', amount: '75 фриспинов', wagering: '40x', validDays: 3 },
      { type: 'cashback', title: 'JET кэшбек', description: 'Кэшбек до 10% еженедельно', amount: 'до 10%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'JET Reload', description: 'Бонус на пополнение по понедельникам', amount: 'до 30%', wagering: '5x', validDays: 3 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', '150% бонус', 'Быстрые выплаты', 'Кэшбек'],
    cons: ['Зарубежная лицензия', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#06b6d4',
  },
  {
    slug: 'rox', name: 'ROX Casino', logo: '🪨', logoUrl: '/logos/rox.png',
    tagline: '100 фриспинов без депозита + 150% на первый',
    description: 'ROX Casino — надёжное казино с бездепозитным бонусом 100 фриспинов и 150% до 50 000 ₽ за первый депозит.',
    fullDescription: `ROX Casino работает по лицензии Curaçao. Бездепозитный бонус 100 фриспинов за регистрацию. Приветственный бонус 150% до 50 000 ₽. Слоты, live-казино, Aviator, Crash-игры. Программа лояльности с ежедневными бонусами.`,
    rating: 4.2, userRating: 4.1, reviewCount: 6700, type: 'casino', founded: 2020,
    license: 'Curaçao eGaming', website: 'https://rox.casino',
    refUrl: 'https://rox-media4.com/c54f8969b',
    mainBonus: '100 FS без депозита + 150%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: '150% бонус', description: '150% до 50 000 ₽', amount: '150% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'ROX фриспины', description: '75 фриспинов за депозит от 500 ₽', amount: '75 фриспинов', wagering: '40x', validDays: 3 },
      { type: 'cashback', title: 'ROX кэшбек', description: 'Кэшбек до 10% еженедельно', amount: 'до 10%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'ROX Reload', description: 'Еженедельный бонус на пополнение', amount: 'до 30%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', '150% бонус', 'Aviator', 'Программа лояльности'],
    cons: ['Зарубежная лицензия', 'Нет букмекера'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'USDT', icon: '💱', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: true, badge: undefined, accentColor: '#78716c',
  },
  {
    slug: 'martin', name: 'MARTIN Casino', logo: '🎩',
    tagline: '100 фриспинов без депозита + 150% на первый',
    description: 'MARTIN Casino — элегантное казино в стиле джентльмена, 100 FS без депозита и 150% до 50 000 ₽.',
    fullDescription: `MARTIN Casino работает по лицензии Curaçao. Элегантный стиль. Бездепозитный бонус 100 фриспинов за регистрацию. Приветственный бонус 150% до 50 000 ₽. Слоты, live-казино, краш-игры. Программа лояльности.`,
    rating: 4.1, userRating: 4.0, reviewCount: 3700, type: 'casino', founded: 2021,
    license: 'Curaçao eGaming', website: 'https://martin.casino',
    refUrl: 'https://martin-route-two.com/ce6c79d66',
    mainBonus: '100 FS без депозита + 150%',
    bonuses: [
      { type: 'registration', title: '100 фриспинов без депозита', description: 'Фриспины за регистрацию', amount: '100 фриспинов', wagering: '45x', validDays: 7 },
      { type: 'deposit', title: '150% бонус', description: '150% до 50 000 ₽', amount: '150% до 50 000 ₽', wagering: '40x', validDays: 30 },
      { type: 'freespins', title: 'MARTIN фриспины', description: '75 фриспинов за депозит от 500 ₽', amount: '75 фриспинов', wagering: '40x', validDays: 3 },
      { type: 'cashback', title: 'MARTIN кэшбек', description: 'Кэшбек до 12% для джентльменов', amount: 'до 12%', wagering: '1x', validDays: 7 },
      { type: 'reload', title: 'MARTIN Reload', description: 'Джентльменский бонус на пополнение', amount: 'до 30%', wagering: '5x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 500,
    hasFreeSpins: true, hasCashback: true, hasRegistrationBonus: true, hasDepositBonus: true,
    pros: ['100 FS без депозита', '150% бонус', 'Элегантный дизайн', 'Быстрые выплаты'],
    cons: ['Зарубежная лицензия', 'Молодая платформа'],
    paymentMethods: [
      { name: 'Visa/Mastercard', icon: '💳', minDeposit: 500, maxWithdrawal: 200000, time: '1-3 дня' },
      { name: 'Bitcoin', icon: '₿', minDeposit: 500, maxWithdrawal: 500000, time: '1-3 часа' },
      { name: 'СБП', icon: '🏦', minDeposit: 300, maxWithdrawal: 150000, time: '1-2 часа' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: false, popular: false, badge: undefined, accentColor: '#1e293b',
  },
  {
    slug: 'stake', name: 'Stake', logo: '🎲',
    tagline: 'Криптоказино №1 в мире — слоты, live, спорт',
    description: 'Stake — крупнейшее криптоказино в мире с мгновенными выплатами, 3000+ играми и встроенным букмекером.',
    fullDescription: `Stake — мировой лидер среди криптоказино с лицензией Curaçao. Более 3000 слотов от лучших провайдеров, расширенное live-казино с реальными дилерами, встроенный букмекер с Live-ставками. Мгновенные выплаты в криптовалюте. Уникальные оригинальные игры: Crash, Dice, Mines, Plinko. Программа VIP с персональным менеджером.`,
    rating: 4.35, userRating: 4.3, reviewCount: 28000, type: 'casino', founded: 2017,
    license: 'Curaçao eGaming (8048/JAZ)', website: 'https://stake.com/?c=FF7nk5KX',
    refUrl: 'https://stake.com/?c=FF7nk5KX',
    mainBonus: 'VIP-программа + ежедневные бонусы',
    bonuses: [
      { type: 'cashback', title: 'Rakeback', description: 'Ежедневный рейкбек до 10%', amount: 'до 10%', wagering: '1x', validDays: 1 },
      { type: 'reload', title: 'Weekly Boost', description: 'Еженедельный бустер для активных игроков', amount: 'до 15%', wagering: '1x', validDays: 7 },
    ],
    hasLiveBetting: false, hasMobileApp: true, hasFastWithdrawal: true, minDeposit: 100,
    hasFreeSpins: false, hasCashback: true, hasRegistrationBonus: false, hasDepositBonus: false,
    pros: ['Мгновенные крипто-выплаты', 'Оригинальные игры', 'VIP-программа', 'Признанный мировой бренд'],
    cons: ['Только крипта', 'Нет приветственного бонуса'],
    paymentMethods: [
      { name: 'Bitcoin', icon: '₿', minDeposit: 100, maxWithdrawal: 10000000, time: 'мгновенно' },
      { name: 'Ethereum', icon: '⟠', minDeposit: 100, maxWithdrawal: 10000000, time: 'мгновенно' },
      { name: 'USDT', icon: '💱', minDeposit: 100, maxWithdrawal: 10000000, time: 'мгновенно' },
    ],
    screenshots: [], faq: [], reviews: [],
    featured: true, popular: true, badge: 'ТОП', accentColor: '#00d4a8',
  },
]

export const getFeatured = () => services.filter(s => s.featured)
export const getPopular = () => services.filter(s => s.popular)
export const getBySlug = (slug: string) => services.find(s => s.slug === slug)
export const getCasinos = () => services.filter(s => s.type === 'casino' || s.type === 'both')
export const getBetting = () => services.filter(s => s.type === 'betting' || s.type === 'both')
