export interface Game {
  slug: string
  name: string
  provider: string
  providerSlug: string
  rtp: string
  type: 'slot' | 'crash' | 'live' | 'card' | 'instant'
  icon: string
  color: string
  volatility: 'low' | 'medium' | 'high' | 'very-high'
  description: string
  metaDesc: string
  longDesc: string
  features: string[]
  maxWin: string
  minBet: string
  casinoSlugs: string[] // казино где есть эта игра
  faqs: { q: string; a: string }[]
  popular?: boolean
  isNew?: boolean
}

// Казино где доступны игры провайдеров
const ALL_CASINO = ['1win', 'vavada', 'stake', 'jozz', 'booi', 'playfortuna', 'ramenbet', 'casino-x', 'joycasino', 'winity', 'monro', 'starda', 'jet', 'rox', 'martin']
const PRAGMATIC_CASINOS = ['1win', 'vavada', 'jozz', 'booi', 'playfortuna', 'joycasino', 'casino-x', 'starda', 'rox', 'martin']
const EVOLUTION_CASINOS = ['1win', 'vavada', 'joycasino', 'stake', 'playfortuna', 'winity', 'jet']
const SPRIBE_CASINOS = ['1win', 'vavada', 'booi', 'joycasino', 'ramenbet', 'starda', 'jet', 'rox']
const NOVOMATIC_CASINOS = ['joycasino', 'casino-x', 'rox', 'monro', 'martin']
const NETENT_CASINOS = ['joycasino', 'vavada', 'casino-x', 'playfortuna', 'starda', 'winity']
const HACKSAW_CASINOS = ['1win', 'vavada', 'joycasino', 'jet', 'rox']
const BGAMING_CASINOS = ['1win', 'vavada', 'joycasino', 'playfortuna', 'booi']
const PUSH_CASINOS = ['1win', 'vavada', 'joycasino', 'starda', 'jet', 'winity']
const NOLIMIT_CASINOS = ['vavada', 'joycasino', 'rox', 'jet', 'stake']
const PLAYNGO_CASINOS = ['1win', 'vavada', 'joycasino', 'playfortuna', 'casino-x', 'booi', 'monro']
const REDTIGER_CASINOS = ['1win', 'vavada', 'joycasino', 'starda', 'ramenbet']
const YGGDRASIL_CASINOS = ['vavada', 'joycasino', 'casino-x', 'winity']

export const games: Game[] = [
  // ── PRAGMATIC PLAY ──
  {
    slug: 'gates-of-olympus',
    name: 'Gates of Olympus',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.5%',
    type: 'slot',
    icon: '⚡',
    color: '#a855f7',
    volatility: 'very-high',
    description: 'Слот с Зевсом, множителями до x500 и механикой Tumble. Максимальный выигрыш 5 000x.',
    metaDesc: 'Gates of Olympus играть онлайн 2026. Казино с Гейтс оф Олимпус. RTP 96.5%, макс. выигрыш 5000x.',
    longDesc: 'Gates of Olympus от Pragmatic Play — один из самых популярных слотов 2021–2026. Решётка 6×5, без линий — победные кластеры от 8 символов. Множители накапливаются при бесплатных спинах, достигая x500. Buy Feature стоит 100x ставки.',
    features: ['RTP 96.5%', 'Tumble механика', 'Множители до ×500', 'Buy Feature', '15 бесплатных спинов'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Что такое Buy Feature в Gates of Olympus?', a: 'Покупка 15 бесплатных спинов за 100x ставки. RTP вырастает до 98.2%.' },
      { q: 'Как получить максимальный выигрыш?', a: 'Нужно накопить множители x500 во время бесплатных спинов при полном выигрышном кластере.' },
    ],
  },
  {
    slug: 'sweet-bonanza',
    name: 'Sweet Bonanza',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '🍭',
    color: '#e879f9',
    volatility: 'very-high',
    description: 'Сладкий слот с конфетами и бомбами-множителями. Tumble механика, бесплатные спины.',
    metaDesc: 'Sweet Bonanza играть онлайн 2026. Казино со Sweet Bonanza. RTP 96.51%, макс. выигрыш 21175x.',
    longDesc: 'Sweet Bonanza — яркий слот 6×5 без линий. Tumble: выигрышные символы исчезают, новые падают сверху. В бонусных спинах появляются бомбы-множители ×2 до ×100. Максимальный выигрыш 21 175x ставки.',
    features: ['RTP 96.51%', 'Tumble механика', 'Бомбы ×2–×100', 'Buy Bonus', 'Макс. 21 175×'],
    maxWin: '21 175x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Сколько стоит Buy Bonus в Sweet Bonanza?', a: '100× ставки. При ставке 10₽ покупка бонуса = 1000₽.' },
      { q: 'Какой символ самый ценный?', a: 'Сердечко — самый дорогой символ. 8+ сердечек дают 50× ставки.' },
    ],
  },
  {
    slug: 'dog-house',
    name: 'The Dog House',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '🐕',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Слот с собаками, Sticky Wilds и мультиплаерами до ×3 в бесплатных спинах.',
    metaDesc: 'The Dog House играть онлайн 2026. Казино с Дог Хаус. RTP 96.51%, Sticky Wilds, фриспины.',
    longDesc: 'The Dog House — популярный слот 5×3, 20 линий. Во время фриспинов Wilds становятся "липкими" и накапливают множители ×2 или ×3. При полном экране Wilds выигрыш достигает 6 750× ставки.',
    features: ['RTP 96.51%', 'Sticky Wilds', 'Множители ×2–×3', '7 бесплатных спинов', 'Макс. 6 750×'],
    maxWin: '6 750x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Чем Dog House отличается от Dog House Megaways?', a: 'Megaways версия имеет до 117 649 линий и более высокую волатильность.' },
      { q: 'Как увеличить выигрыш в бесплатных спинах?', a: 'Все Wilds накапливают множители. Чем больше Wilds на экране — тем выше умножение.' },
    ],
  },
  {
    slug: 'big-bass-bonanza',
    name: 'Big Bass Bonanza',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.71%',
    type: 'slot',
    icon: '🎣',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Рыбалка и большие выигрыши! Рыбак-Wild собирает деньги с экрана в бесплатных спинах.',
    metaDesc: 'Big Bass Bonanza играть онлайн 2026. Казино с Биг Басс. RTP 96.71%, макс. выигрыш 2 100x.',
    longDesc: 'Big Bass Bonanza — рыболовный слот 5×3, 10 линий. Рыбак-Wild в бонусе собирает денежные призы со всех рыб на экране. Чем больше рыбаков — тем больше собранная сумма.',
    features: ['RTP 96.71%', 'Рыбак-Wild', '10 бесплатных спинов', 'Денежные символы', 'Макс. 2 100×'],
    maxWin: '2 100x',
    minBet: '0.10 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    faqs: [
      { q: 'Что делает рыбак в бесплатных спинах?', a: 'Рыбак-Wild собирает все денежные символы (рыбы) на экране и суммирует их стоимость.' },
      { q: 'Есть ли Buy Bonus?', a: 'Да, стоит 100× ставки и сразу запускает бонусные спины.' },
    ],
  },
  {
    slug: 'starlight-princess',
    name: 'Starlight Princess',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.5%',
    type: 'slot',
    icon: '⭐',
    color: '#f472b6',
    volatility: 'very-high',
    description: 'Аниме-принцесса и множители до ×500. Механика аналогична Gates of Olympus.',
    metaDesc: 'Starlight Princess играть онлайн 2026. Казино с Старлайт Принцесс. RTP 96.5%, макс. 5000x.',
    longDesc: 'Starlight Princess от Pragmatic Play — аниме-слот 6×5, кластерные выигрыши. Механика почти идентична Gates of Olympus, но с другой тематикой. Множители до ×500, Buy Feature, 15 фриспинов.',
    features: ['RTP 96.5%', 'Кластеры 8+', 'Множители до ×500', 'Buy Feature', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [
      { q: 'Чем Starlight Princess отличается от Gates of Olympus?', a: 'Та же механика, другая тема. У Starlight чуть другие частоты попадания бонуса.' },
    ],
  },
  {
    slug: 'sugar-rush',
    name: 'Sugar Rush 1000',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.53%',
    type: 'slot',
    icon: '🍬',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Конфетный слот 7×7 с множителями во всём поле. Максимум 5 000x.',
    metaDesc: 'Sugar Rush 1000 играть онлайн 2026. RTP 96.53%, решётка 7×7, множители везде.',
    longDesc: 'Sugar Rush 1000 — расширенная версия Sugar Rush. Решётка 7×7, множители могут появиться на любой ячейке. В бонусе множители накапливаются и суммируются.',
    features: ['RTP 96.53%', 'Решётка 7×7', 'Множители везде', 'Авто-множитель 1000x', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── SPRIBE ──
  {
    slug: 'aviator',
    name: 'Aviator',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'crash',
    icon: '✈️',
    color: '#ef4444',
    volatility: 'high',
    description: 'Самолёт взлетает, коэффициент растёт — успей забрать до крэша. RTP 97%.',
    metaDesc: 'Aviator играть онлайн 2026. Казино с Авиатор от Spribe. RTP 97%, стратегии, лучшие казино.',
    longDesc: 'Aviator от Spribe — краш-игра нового поколения. Самолёт взлетает, множитель растёт от 1.00×. Нужно успеть нажать "Вывести" до крэша. RTP 97%, провабли фэйр. Можно ставить 2 ставки одновременно.',
    features: ['RTP 97%', 'Множители до 1000×', 'Авто-вывод', 'Чат игроков', '2 ставки одновременно'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Какова лучшая стратегия в Aviator?', a: 'Стратегия двойной ставки: одна на ×1.5 (безопасная), вторая на ×5–×10 (рисковая). Но результаты случайны.' },
      { q: 'Можно ли обмануть Aviator?', a: 'Нет. Игра использует провабли-фэйр алгоритм — каждый раунд случаен и верифицирован.' },
    ],
  },
  {
    slug: 'mines',
    name: 'Mines',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '💣',
    color: '#f97316',
    volatility: 'medium',
    description: 'Поле с минами — открывай клетки и забирай выигрыш. Чем дальше — тем выше множитель.',
    metaDesc: 'Mines игра 2026. Казино с Майнс от Spribe. Играть в мины онлайн. RTP 97%.',
    longDesc: 'Mines — простая но захватывающая игра. Выберите количество мин (1–24) и открывайте клетки 5×5. Каждая безопасная клетка увеличивает множитель. В любой момент можно забрать выигрыш.',
    features: ['RTP 97%', '1–24 мины', 'Авто-пик', 'Провабли фэйр', 'Настраиваемый риск'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Сколько мин лучше ставить?', a: '3 мины — хороший баланс риска и награды. При 1 мине низкие множители, при 24 — почти невозможно.' },
    ],
  },
  {
    slug: 'plinko',
    name: 'Plinko',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '🎯',
    color: '#22c55e',
    volatility: 'medium',
    description: 'Шарик падает по пирамиде пинов — куда упадёт, такой множитель получите.',
    metaDesc: 'Plinko играть онлайн 2026. Казино с Плинко. Spribe Plinko RTP 97%.',
    longDesc: 'Plinko — виральная игра по мотивам известного шоу. Шарик падает через пирамиду из штырьков и попадает в одну из ячеек с множителями. Можно настроить риск (низкий/средний/высокий) и количество рядов.',
    features: ['RTP 97%', '8–16 рядов', '3 уровня риска', 'Авто-игра', 'До 1000×'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как увеличить шанс на большой выигрыш?', a: 'Высокий риск + больше рядов = редкие, но огромные выигрыши. Низкий риск = стабильные небольшие призы.' },
    ],
  },
  {
    slug: 'dice',
    name: 'Dice',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '🎲',
    color: '#6366f1',
    volatility: 'medium',
    description: 'Классический кубик с настраиваемыми шансами. Ставь выше или ниже определённого числа.',
    metaDesc: 'Dice игра онлайн 2026. Spribe Dice — настраиваемые ставки, RTP 97%.',
    longDesc: 'Dice — минималистичная игра с кубиком. Вы сами выбираете диапазон победы: чем меньше шанс — тем выше множитель. Мгновенные результаты, провабли-фэйр.',
    features: ['RTP 97%', 'Настраиваемый шанс', 'Авто-игра', 'Провабли фэйр', 'Моментальный результат'],
    maxWin: '9 900x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    faqs: [],
  },

  // ── 1WIN GAMES ──
  {
    slug: 'lucky-jet',
    name: 'Lucky Jet',
    provider: '1Win Games',
    providerSlug: '1win-games',
    rtp: '97%',
    type: 'crash',
    icon: '🚀',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Лаки взлетает на реактивном ранце — множитель растёт, успей забрать!',
    metaDesc: 'Lucky Jet играть онлайн 2026. Казино с Лаки Джет. RTP 97%, стратегии и советы.',
    longDesc: 'Lucky Jet — краш-игра от 1Win Games. Персонаж Лаки летит на ракетном ранце. Механика как в Aviator: множитель растёт, нужно забрать до краша. RTP 97%, провабли-фэйр.',
    features: ['RTP 97%', 'До ×200', '2 ставки одновременно', 'Авто-вывод', 'Статистика раундов'],
    maxWin: '200x',
    minBet: '1 ₽',
    casinoSlugs: ['1win'],
    popular: true,
    faqs: [
      { q: 'Чем Lucky Jet отличается от Aviator?', a: 'Lucky Jet эксклюзивна для 1Win. Другой визуал, максимум ×200 вместо ×1000 у Aviator.' },
    ],
  },

  // ── EVOLUTION GAMING ──
  {
    slug: 'crazy-time',
    name: 'Crazy Time',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.08%',
    type: 'live',
    icon: '🎡',
    color: '#4ade80',
    volatility: 'high',
    description: 'Колесо фортуны с 4 бонусными играми. Ведущий в прямом эфире, выигрыши до 20 000×.',
    metaDesc: 'Crazy Time играть онлайн 2026. Казино с Крейзи Тайм. Evolution Gaming live шоу.',
    longDesc: 'Crazy Time — флагманское live-шоу Evolution Gaming. Колесо 54 сегмента, 4 бонусные игры: Cash Hunt, Pachinko, Coin Flip, Crazy Time. В бонусе Crazy Time ×20 000.',
    features: ['RTP 96.08%', '4 бонус-игры', 'HD трансляция', 'Макс. 20 000×', 'Живой ведущий'],
    maxWin: '20 000x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как попасть в Crazy Time бонус?', a: 'Нужно угадать сегмент "Crazy Time" (1 из 54). Вероятность 1/54 ≈ 1.85%.' },
    ],
  },
  {
    slug: 'lightning-roulette',
    name: 'Lightning Roulette',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '97.3%',
    type: 'live',
    icon: '⚡',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Рулетка с молниями — случайные числа получают множитель ×50–×500.',
    metaDesc: 'Lightning Roulette играть онлайн 2026. Казино с Лайтнинг Рулетка. Evolution RTP 97.3%.',
    longDesc: 'Lightning Roulette — инновационная европейская рулетка от Evolution. Перед каждым спином 1–5 чисел получают "молнию" с множителем ×50, ×100, ×200, ×300, ×400 или ×500.',
    features: ['RTP 97.3%', 'Множители ×50–×500', 'HD трансляция', 'Живой ведущий', 'Европейская рулетка'],
    maxWin: '500x',
    minBet: '20 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    popular: true,
    faqs: [
      { q: 'Чем Lightning Roulette лучше обычной?', a: 'На числа с молнией можно получить до 500× вместо обычных 35×. Подходит любителям крупных выигрышей.' },
    ],
  },
  {
    slug: 'monopoly-live',
    name: 'Monopoly Live',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.23%',
    type: 'live',
    icon: '🎩',
    color: '#22c55e',
    volatility: 'high',
    description: 'Колесо Монополии + 3D бонус-раунд. Мистер Монополия ходит по доске и множит призы.',
    metaDesc: 'Monopoly Live играть онлайн 2026. Казино с Монополи Лайв. Evolution Gaming.',
    longDesc: 'Monopoly Live объединяет колесо фортуны и 3D-бонус на доске Монополии. Попадите в Chance или 2-Rolls/4-Rolls чтобы запустить бонус, где Mr. Monopoly ходит по доске и собирает выигрыши.',
    features: ['RTP 96.23%', '3D бонус-раунд', 'Живой ведущий', 'Авто-ставка', 'Макс. 1500×'],
    maxWin: '1 500x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },

  // ── NOVOMATIC ──
  {
    slug: 'book-of-ra',
    name: 'Book of Ra',
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.1%',
    type: 'slot',
    icon: '📚',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Легендарный египетский слот. Книга = Wild и Scatter. Расширяющийся символ в бонусе.',
    metaDesc: 'Book of Ra играть онлайн 2026. Казино с Книгой Ра. Novomatic, RTP 95.1%.',
    longDesc: 'Book of Ra — один из первых классических слотов. 5 барабанов, 9 линий. Книга работает и как Wild, и как Scatter. 3+ книги = 10 бесплатных спинов с расширяющимся символом.',
    features: ['RTP 95.1%', '5×3, 9 линий', 'Wild+Scatter', '10 фриспинов', 'Гамбл-функция'],
    maxWin: '5 000x',
    minBet: '1 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Book of Ra Deluxe или Classic — что лучше?', a: 'Deluxe имеет 10 линий вместо 9 и чуть лучший RTP. Большинство игроков предпочитают Deluxe.' },
    ],
  },
  {
    slug: 'book-of-ra-deluxe',
    name: 'Book of Ra Deluxe',
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.5%',
    type: 'slot',
    icon: '📖',
    color: '#f97316',
    volatility: 'high',
    description: 'Улучшенная версия классики — 10 линий, чуть лучший RTP и обновлённая графика.',
    metaDesc: 'Book of Ra Deluxe играть онлайн 2026. RTP 95.5%, 10 линий, лучшая версия Книги Ра.',
    longDesc: 'Book of Ra Deluxe — улучшенная редакция 2008 года. 5×3, 10 активных линий (против 9 в Classic). Та же механика с книгой-Wild/Scatter, 10 бесплатных спинов.',
    features: ['RTP 95.5%', '10 линий', 'Wild+Scatter', '10 фриспинов', 'HD графика'],
    maxWin: '5 000x',
    minBet: '1 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    popular: true,
    faqs: [],
  },

  // ── HACKSAW ──
  {
    slug: 'tower-rush',
    name: 'Tower Rush',
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '97%',
    type: 'crash',
    icon: '🏗️',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Строй башню как можно выше — каждый этаж увеличивает выигрыш. Опасайся обрушения!',
    metaDesc: 'Tower Rush играть онлайн 2026. Казино с Тауэр Раш. RTP 97%, Hacksaw Gaming.',
    longDesc: 'Tower Rush от Hacksaw Gaming — краш-игра с механикой строительства башни. Каждый добавленный этаж увеличивает множитель. Заберите выигрыш до обрушения. Чем выше башня — тем больше риск.',
    features: ['RTP 97%', 'Накопительный множитель', 'Авто-стоп', 'Провабли фэйр', 'Мгновенная игра'],
    maxWin: '500x',
    minBet: '1 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    isNew: true,
    popular: true,
    faqs: [
      { q: 'Чем Tower Rush отличается от Aviator?', a: 'Механика башни вместо самолёта. Другая динамика нарастания риска.' },
    ],
  },
  {
    slug: 'squealin-riches',
    name: 'Squealin\' Riches',
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '96%',
    type: 'slot',
    icon: '🐷',
    color: '#e879f9',
    volatility: 'very-high',
    description: 'Свинки-богачи с денежными призами и прогрессивными джекпотами.',
    metaDesc: 'Squealin Riches играть онлайн. Hacksaw Gaming, денежные свинки, прогрессив.',
    longDesc: 'Squealin\' Riches — уникальный слот Hacksaw с денежными призами внутри символов. Во время бонуса свиньи копят монеты, которые затем выплачиваются.',
    features: ['RTP 96%', 'Денежные символы', 'Прогрессив', 'Бонусный раунд', 'Макс. 10 000×'],
    maxWin: '10 000x',
    minBet: '0.20 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    faqs: [],
  },

  // ── BGAMING ──
  {
    slug: 'banana-party',
    name: 'Banana Party',
    provider: 'BGaming',
    providerSlug: 'bgaming',
    rtp: '97%',
    type: 'slot',
    icon: '🍌',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Банановая вечеринка с обезьянами — фиксированные джекпоты и множители в бонусе.',
    metaDesc: 'Banana Party играть онлайн 2026. Казино с Банана Пати. BGaming, RTP 97%.',
    longDesc: 'Banana Party от BGaming — весёлый слот с обезьянами. 5×3, 20 линий. Scatter запускает бесплатные спины с накопительными джекпотами. Один из самых высоких RTP среди слотов.',
    features: ['RTP 97%', 'Фиксированные джекпоты', 'Бесплатные спины', '20 линий', 'Авто-игра'],
    maxWin: '2 000x',
    minBet: '0.20 ₽',
    casinoSlugs: BGAMING_CASINOS,
    popular: true,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'cash-or-crash',
    name: 'Cash or Crash',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '97%',
    type: 'live',
    icon: '💸',
    color: '#22c55e',
    volatility: 'medium',
    description: 'Live-игра с воздушным шаром. Собирай деньги или рискни ради большего приза.',
    metaDesc: 'Cash or Crash играть онлайн. Evolution Gaming, RTP 97%, live-игра с шаром.',
    longDesc: 'Cash or Crash — live-игра Evolution в стиле карточной. Воздушный шар поднимается, денежные шары добавляют призы. В любой момент можно "Cash" — забрать деньги, или "Crash" — продолжить.',
    features: ['RTP 97%', 'Живой ведущий', 'Cash или Crash решение', 'Зелёный/красный шар', 'До ×10 000'],
    maxWin: '10 000x',
    minBet: '5 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },
  {
    slug: 'starburst',
    name: 'Starburst',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '96.1%',
    type: 'slot',
    icon: '💎',
    color: '#6366f1',
    volatility: 'low',
    description: 'Классический неоновый слот с Expanding Wilds. Низкая волатильность, частые выигрыши.',
    metaDesc: 'Starburst играть онлайн 2026. Казино со Старбёрст NetEnt. RTP 96.1%, Expanding Wilds.',
    longDesc: 'Starburst — один из самых популярных слотов в истории. 5×3, 10 линий, выигрыши в обе стороны. Wild расширяется на весь барабан и запускает до 3 респ.инов. Идеален для отыгрыша бонусов.',
    features: ['RTP 96.1%', 'Expanding Wild', '3 бесплатных респ.ина', 'Выигрыши в 2 стороны', 'Низкая дисперсия'],
    maxWin: '500x',
    minBet: '0.10 ₽',
    casinoSlugs: NETENT_CASINOS,
    popular: true,
    faqs: [
      { q: 'Почему Starburst используют для отыгрыша бонусов?', a: 'Низкая волатильность обеспечивает стабильные небольшие выигрыши, что позволяет медленно отыгрывать вейджер.' },
    ],
  },
  {
    slug: 'gonzo-quest',
    name: 'Gonzo\'s Quest',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '95.97%',
    type: 'slot',
    icon: '🗿',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Конкистадор ищет Эльдорадо. Механика Avalanche, множители до ×15 в бесплатных спинах.',
    metaDesc: 'Gonzo\'s Quest играть онлайн 2026. NetEnt, RTP 95.97%, Avalanche механика.',
    longDesc: 'Gonzo\'s Quest — революционный слот NetEnt с механикой Avalanche (предшественник Tumble). 5×3, 20 линий. Последовательные победы увеличивают множитель до ×5 в обычной игре и ×15 в бонусе.',
    features: ['RTP 95.97%', 'Avalanche механика', 'Множители ×1–×15', '10 бесплатных спинов', '20 линий'],
    maxWin: '2 500x',
    minBet: '0.20 ₽',
    casinoSlugs: NETENT_CASINOS,
    faqs: [],
  },

  // ── PUSH GAMING ──
  {
    slug: 'jammin-jars',
    name: 'Jammin\' Jars',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.83%',
    type: 'slot',
    icon: '🍓',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Фруктовый слот 8×8 с Cluster Pays. Rainbow Feature и Wild Multipliers — до 20 000×.',
    metaDesc: 'Jammin Jars играть онлайн 2026. Push Gaming, RTP 96.83%, Cluster Pays, до 20000x.',
    longDesc: 'Jammin\' Jars — культовый слот Push Gaming. Сетка 8×8, кластерные выигрыши. В бонусе джемы-Wilds движутся по барабанам, собирая множители. Максимальный выигрыш 20 000×.',
    features: ['RTP 96.83%', 'Cluster Pays 8×8', 'Wild Multipliers', 'Rainbow Feature', 'Макс. 20 000×'],
    maxWin: '20 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как работает Rainbow Feature?', a: 'Радуга добавляет дополнительные Wild на поле перед бонусными спинами, увеличивая потенциал.' },
    ],
  },
  {
    slug: 'fat-santa',
    name: 'Fat Santa',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.56%',
    type: 'slot',
    icon: '🎅',
    color: '#ef4444',
    volatility: 'high',
    description: 'Новогодний слот с толстым Сантой. Wild Multipliers и бесплатные спины — до 10 000×.',
    metaDesc: 'Fat Santa играть онлайн 2026. Push Gaming, RTP 96.56%, новогодний слот.',
    longDesc: 'Fat Santa — рождественский слот Push Gaming. 6×4, 4096 способов выиграть. Санта-Wild множит выигрыши. В бонусе Санта становится больше с каждым спином.',
    features: ['RTP 96.56%', '6×4 сетка', 'Wild Multipliers', 'Expanding Santa', '4096 линий'],
    maxWin: '10 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    faqs: [],
  },
  {
    slug: 'wild-swarm',
    name: 'Wild Swarm',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.48%',
    type: 'slot',
    icon: '🐝',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Пчелиный слот с уникальной механикой роя. Wilds заполняют целые барабаны.',
    metaDesc: 'Wild Swarm играть онлайн 2026. Push Gaming, рой диких символов, RTP 96.48%.',
    longDesc: 'Wild Swarm — слот Push Gaming с механикой пчелиного роя. 5×3, 243 линии. Wild могут образовывать рой и заполнять весь барабан. Уникальная бонусная система с ульями.',
    features: ['RTP 96.48%', 'Swarm механика', 'Full Reel Wilds', 'Honey Pot бонус', '243 линии'],
    maxWin: '6 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    faqs: [],
  },

  // ── NOLIMIT CITY ──
  {
    slug: 'san-quentin',
    name: 'San Quentin xWays',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.43%',
    type: 'slot',
    icon: '🔒',
    color: '#64748b',
    volatility: 'very-high',
    description: 'Самый суровый слот в истории. Тюремная тематика, xWays механика, потенциал 150 000×.',
    metaDesc: 'San Quentin играть онлайн 2026. Nolimit City, xWays, максимум 150000x.',
    longDesc: 'San Quentin xWays от Nolimit City — один из самых высоковолатильных слотов. Тюремная тема, механики xWays (символы с несколькими иконками) и xNudge (Wild с множителем). RTP 96.43%, потенциал до 150 000×.',
    features: ['RTP 96.43%', 'xWays механика', 'xNudge Wilds', 'Макс. 150 000×', 'Экстремальная дисперсия'],
    maxWin: '150 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    popular: true,
    faqs: [
      { q: 'Что такое xWays?', a: 'Символ xWays раскрывается в 2–6 обычных символов, резко увеличивая число линий и выигрыш.' },
    ],
  },
  {
    slug: 'mental',
    name: 'Mental',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.3%',
    type: 'slot',
    icon: '🧠',
    color: '#a855f7',
    volatility: 'very-high',
    description: 'Психиатрическая тема, безумные механики. xBomb, xSplit — потенциал 43 200×.',
    metaDesc: 'Mental играть онлайн 2026. Nolimit City, xBomb, xSplit, до 43200x.',
    longDesc: 'Mental — слот Nolimit City с психиатрической тематикой. xBomb уничтожает соседние символы и добавляет множитель. xSplit дублирует символы. Очень высокая волатильность.',
    features: ['RTP 96.3%', 'xBomb механика', 'xSplit символы', 'Макс. 43 200×', 'Высочайшая дисперсия'],
    maxWin: '43 200x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'tombstone-rip',
    name: 'Tombstone R.I.P.',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.08%',
    type: 'slot',
    icon: '🪦',
    color: '#475569',
    volatility: 'very-high',
    description: 'Дикий Запад и кладбище. xNudge и xWays механики, 200 000× максимальный выигрыш.',
    metaDesc: 'Tombstone RIP играть онлайн 2026. Nolimit City, Дикий Запад, до 200000x.',
    longDesc: 'Tombstone R.I.P. — сиквел Tombstone. Дикий Запад, могильная тема. xNudge Wilds накапливают множители с каждым нажатием. Максимальный потенциал 200 000× — один из самых высоких в индустрии.',
    features: ['RTP 96.08%', 'xNudge Wilds', 'Макс. 200 000×', 'Shoot Out бонус', 'xWays механика'],
    maxWin: '200 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── PLAY'N GO ──
  {
    slug: 'book-of-dead',
    name: 'Book of Dead',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.21%',
    type: 'slot',
    icon: '☀️',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетский слот — духовный наследник Book of Ra. Расширяющийся символ в 10 фриспинах.',
    metaDesc: 'Book of Dead играть онлайн 2026. Play\'n GO, RTP 96.21%, казино с Book of Dead.',
    longDesc: 'Book of Dead от Play\'n GO — один из самых популярных слотов Европы. 5×3, 10 линий. Книга — Wild и Scatter одновременно. 3+ Scatter = 10 бесплатных спинов с расширяющимся символом. Схожа с Book of Ra, но лучший RTP.',
    features: ['RTP 96.21%', '10 фриспинов', 'Расширяющийся символ', 'Wild+Scatter', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.01 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [
      { q: 'Book of Dead или Book of Ra — что лучше?', a: 'Book of Dead имеет лучший RTP (96.21% vs 95.1%) и более современную графику. Механика идентична.' },
    ],
  },
  {
    slug: 'reactoonz',
    name: 'Reactoonz',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.51%',
    type: 'slot',
    icon: '👾',
    color: '#22c55e',
    volatility: 'high',
    description: 'Инопланетяне в сетке 7×7, Cluster Pays. Quantum механика с 4 типами бонусов.',
    metaDesc: 'Reactoonz играть онлайн 2026. Play\'n GO, RTP 96.51%, Cluster Pays, Quantum бонусы.',
    longDesc: 'Reactoonz — уникальный слот 7×7 с Cluster Pays. Cute-инопланетяне заполняют поле. Quantum Wilds, Blooming Wilds, Chain Reaction, Implosion — 4 типа бонусных механик. Gargantoon Wild — огромный символ 3×3.',
    features: ['RTP 96.51%', 'Cluster Pays 7×7', '4 Quantum механики', 'Gargantoon Wild', 'Макс. 4 570×'],
    maxWin: '4 570x',
    minBet: '0.20 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'legacy-of-egypt',
    name: 'Legacy of Egypt',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.5%',
    type: 'slot',
    icon: '🏛️',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетский слот с колесом фортуны в бонусе. Множители и джекпоты.',
    metaDesc: 'Legacy of Egypt играть онлайн 2026. Play\'n GO, колесо бонусов, до 10000x.',
    longDesc: 'Legacy of Egypt от Play\'n GO — египетский слот с уникальным колесом в бонусе. 5×3, 10 линий. Wild-скараб. В бонусном колесе разыгрываются множители, мини-джекпоты и бесплатные спины.',
    features: ['RTP 96.5%', 'Колесо бонусов', 'Wild-скараб', 'Прогрессивные джекпоты', 'Макс. 10 000×'],
    maxWin: '10 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    faqs: [],
  },

  // ── RED TIGER ──
  {
    slug: 'gonzos-gold',
    name: "Gonzo's Gold",
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '95.99%',
    type: 'slot',
    icon: '🏺',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Новый Гонсо от Red Tiger с механикой Cluster Pays и Avalanche.',
    metaDesc: "Gonzo's Gold играть онлайн 2026. Red Tiger, RTP 95.99%, Cluster Pays.",
    longDesc: "Gonzo's Gold — современная интерпретация Gonzo's Quest от Red Tiger. Cluster Pays, Avalanche механика. В бонусе Gonzo находит сокровища Эльдорадо с нарастающими множителями.",
    features: ['RTP 95.99%', 'Cluster Pays', 'Avalanche механика', 'Дикие множители', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'dragons-luck',
    name: "Dragon's Luck",
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '96.72%',
    type: 'slot',
    icon: '🐉',
    color: '#ef4444',
    volatility: 'medium',
    description: 'Азиатский слот с удачей дракона. Прогрессивные суперпризы и дикие расширения.',
    metaDesc: "Dragon's Luck играть онлайн 2026. Red Tiger, RTP 96.72%, азиатская тема.",
    longDesc: "Dragon's Luck — элегантный азиатский слот Red Tiger. 5×3, 10 линий. Особый символ Super Prize Dragon активирует прогрессивный джекпот. Wild расширяется на весь барабан.",
    features: ['RTP 96.72%', 'Super Prize Dragon', 'Expanding Wild', 'Daily Jackpot', '10 линий'],
    maxWin: '3 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    popular: true,
    faqs: [],
  },

  // ── YGGDRASIL ──
  {
    slug: 'vikings-go-berzerk',
    name: 'Vikings Go Berzerk',
    provider: 'Yggdrasil',
    providerSlug: 'yggdrasil',
    rtp: '96.1%',
    type: 'slot',
    icon: '⚔️',
    color: '#6366f1',
    volatility: 'high',
    description: 'Викинги сражаются с морскими чудищами. Берсерк-режим и накопительные спины.',
    metaDesc: 'Vikings Go Berzerk играть онлайн 2026. Yggdrasil, RTP 96.1%, берсерки.',
    longDesc: 'Vikings Go Berzerk — культовый слот Yggdrasil. 5 барабанов, 25 линий. Каждый викинг накапливает ярость и уходит в Berzerk-режим с множителями. Сражение с морским змеем в бонусе.',
    features: ['RTP 96.1%', 'Berzerk режим', '4 викинга с накопителями', 'Rage-метр', 'Макс. 4 425×'],
    maxWin: '4 425x',
    minBet: '0.25 ₽',
    casinoSlugs: YGGDRASIL_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'valley-of-the-gods',
    name: 'Valley of the Gods',
    provider: 'Yggdrasil',
    providerSlug: 'yggdrasil',
    rtp: '96.1%',
    type: 'slot',
    icon: '🌅',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетские боги и скарабеи. Заблокированные позиции открываются символами скарабея.',
    metaDesc: 'Valley of the Gods играть онлайн 2026. Yggdrasil, RTP 96.1%, египетская тема.',
    longDesc: 'Valley of the Gods — египетский слот Yggdrasil с уникальной механикой. Часть позиций заблокирована скарабеями. Каждый проигрышный спин открывает позиции. Когда все разблокированы — активируется Multiplier Mode.',
    features: ['RTP 96.1%', 'Scarab механика', 'Multiplier Mode', 'Re-spin система', 'Макс. 3 600×'],
    maxWin: '3 600x',
    minBet: '0.25 ₽',
    casinoSlugs: YGGDRASIL_CASINOS,
    faqs: [],
  },
]

// Получить игру по слагу
export function getGameBySlug(slug: string): Game | undefined {
  return games.find(g => g.slug === slug)
}

// Получить казино где доступна игра
export function getCasinosForGame(slug: string) {
  const game = getGameBySlug(slug)
  if (!game) return []
  return game.casinoSlugs
}
