export interface Game {
  slug: string
  name: string
  provider: string
  providerSlug: string
  rtp: string
  type: 'slot' | 'crash' | 'live' | 'card' | 'instant'
  icon: string
  color: string
  volatility: 'low' | 'medium' | 'high' | 'very-high'
  description: string
  metaDesc: string
  longDesc: string
  features: string[]
  maxWin: string
  minBet: string
  casinoSlugs: string[] // казино где есть эта игра
  faqs: { q: string; a: string }[]
  popular?: boolean
  isNew?: boolean
}

// Казино где доступны игры провайдеров
const ALL_CASINO = ['1win', 'vavada', 'stake', 'jozz', 'booi', 'playfortuna', 'ramenbet', 'casino-x', 'joycasino', 'winity', 'monro', 'starda', 'jet', 'rox', 'martin']
const PRAGMATIC_CASINOS = ['1win', 'vavada', 'jozz', 'booi', 'playfortuna', 'joycasino', 'casino-x', 'starda', 'rox', 'martin']
const EVOLUTION_CASINOS = ['1win', 'vavada', 'joycasino', 'stake', 'playfortuna', 'winity', 'jet']
const SPRIBE_CASINOS = ['1win', 'vavada', 'booi', 'joycasino', 'ramenbet', 'starda', 'jet', 'rox']
const NOVOMATIC_CASINOS = ['joycasino', 'casino-x', 'rox', 'monro', 'martin']
const NETENT_CASINOS = ['joycasino', 'vavada', 'casino-x', 'playfortuna', 'starda', 'winity']
const HACKSAW_CASINOS = ['1win', 'vavada', 'joycasino', 'jet', 'rox']
const BGAMING_CASINOS = ['1win', 'vavada', 'joycasino', 'playfortuna', 'booi']
const PUSH_CASINOS = ['1win', 'vavada', 'joycasino', 'starda', 'jet', 'winity']
const NOLIMIT_CASINOS = ['vavada', 'joycasino', 'rox', 'jet', 'stake']
const PLAYNGO_CASINOS = ['1win', 'vavada', 'joycasino', 'playfortuna', 'casino-x', 'booi', 'monro']
const REDTIGER_CASINOS = ['1win', 'vavada', 'joycasino', 'starda', 'ramenbet']
const YGGDRASIL_CASINOS = ['vavada', 'joycasino', 'casino-x', 'riobet']
const RELAX_CASINOS = ['vavada', 'joycasino', 'jet', 'rox', 'stake', 'starda']
const BTG_CASINOS = ['vavada', 'joycasino', 'rox', 'jet', 'stake', '1win']
const MICROGAMING_CASINOS = ['joycasino', 'casino-x', 'vavada', 'monro']
const WAZDAN_CASINOS = ['vavada', 'joycasino', 'booi', 'starda', 'ramenbet']
const ELK_CASINOS = ['vavada', 'joycasino', 'jet', 'starda']
const QUICKSPIN_CASINOS = ['vavada', 'joycasino', 'casino-x', 'riobet']
const ENDORPHINA_CASINOS = ['joycasino', 'ramenbet', 'booi', 'casino-x', 'monro']
const SMARTSOFT_CASINOS = ['1win', 'vavada', 'joycasino', 'ramenbet', 'starda', 'fugu']
const AMATIC_CASINOS = ['joycasino', 'casino-x', 'rox', 'monro', 'martin', 'ramenbet']
const PLAYSON_CASINOS = ['vavada', 'joycasino', 'booi', 'starda', 'ramenbet', 'fugu']

export const games: Game[] = [
  // ── PRAGMATIC PLAY ──
  {
    slug: 'gates-of-olympus',
    name: 'Gates of Olympus',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.5%',
    type: 'slot',
    icon: '⚡',
    color: '#a855f7',
    volatility: 'very-high',
    description: 'Слот с Зевсом, множителями до x500 и механикой Tumble. Максимальный выигрыш 5 000x.',
    metaDesc: 'Gates of Olympus играть онлайн 2026. Казино с Гейтс оф Олимпус. RTP 96.5%, макс. выигрыш 5000x.',
    longDesc: 'Gates of Olympus от Pragmatic Play — один из самых популярных слотов 2021–2026. Решётка 6×5, без линий — победные кластеры от 8 символов. Множители накапливаются при бесплатных спинах, достигая x500. Buy Feature стоит 100x ставки.',
    features: ['RTP 96.5%', 'Tumble механика', 'Множители до ×500', 'Buy Feature', '15 бесплатных спинов'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Что такое Buy Feature в Gates of Olympus?', a: 'Покупка 15 бесплатных спинов за 100x ставки. RTP вырастает до 98.2%.' },
      { q: 'Как получить максимальный выигрыш?', a: 'Нужно накопить множители x500 во время бесплатных спинов при полном выигрышном кластере.' },
    ],
  },
  {
    slug: 'sweet-bonanza',
    name: 'Sweet Bonanza',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '🍭',
    color: '#e879f9',
    volatility: 'very-high',
    description: 'Сладкий слот с конфетами и бомбами-множителями. Tumble механика, бесплатные спины.',
    metaDesc: 'Sweet Bonanza играть онлайн 2026. Казино со Sweet Bonanza. RTP 96.51%, макс. выигрыш 21175x.',
    longDesc: 'Sweet Bonanza — яркий слот 6×5 без линий. Tumble: выигрышные символы исчезают, новые падают сверху. В бонусных спинах появляются бомбы-множители ×2 до ×100. Максимальный выигрыш 21 175x ставки.',
    features: ['RTP 96.51%', 'Tumble механика', 'Бомбы ×2–×100', 'Buy Bonus', 'Макс. 21 175×'],
    maxWin: '21 175x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Сколько стоит Buy Bonus в Sweet Bonanza?', a: '100× ставки. При ставке 10₽ покупка бонуса = 1000₽.' },
      { q: 'Какой символ самый ценный?', a: 'Сердечко — самый дорогой символ. 8+ сердечек дают 50× ставки.' },
    ],
  },
  {
    slug: 'dog-house',
    name: 'The Dog House',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '🐕',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Слот с собаками, Sticky Wilds и мультиплаерами до ×3 в бесплатных спинах.',
    metaDesc: 'The Dog House играть онлайн 2026. Казино с Дог Хаус. RTP 96.51%, Sticky Wilds, фриспины.',
    longDesc: 'The Dog House — популярный слот 5×3, 20 линий. Во время фриспинов Wilds становятся "липкими" и накапливают множители ×2 или ×3. При полном экране Wilds выигрыш достигает 6 750× ставки.',
    features: ['RTP 96.51%', 'Sticky Wilds', 'Множители ×2–×3', '7 бесплатных спинов', 'Макс. 6 750×'],
    maxWin: '6 750x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Чем Dog House отличается от Dog House Megaways?', a: 'Megaways версия имеет до 117 649 линий и более высокую волатильность.' },
      { q: 'Как увеличить выигрыш в бесплатных спинах?', a: 'Все Wilds накапливают множители. Чем больше Wilds на экране — тем выше умножение.' },
    ],
  },
  {
    slug: 'big-bass-bonanza',
    name: 'Big Bass Bonanza',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.71%',
    type: 'slot',
    icon: '🎣',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Рыбалка и большие выигрыши! Рыбак-Wild собирает деньги с экрана в бесплатных спинах.',
    metaDesc: 'Big Bass Bonanza играть онлайн 2026. Казино с Биг Басс. RTP 96.71%, макс. выигрыш 2 100x.',
    longDesc: 'Big Bass Bonanza — рыболовный слот 5×3, 10 линий. Рыбак-Wild в бонусе собирает денежные призы со всех рыб на экране. Чем больше рыбаков — тем больше собранная сумма.',
    features: ['RTP 96.71%', 'Рыбак-Wild', '10 бесплатных спинов', 'Денежные символы', 'Макс. 2 100×'],
    maxWin: '2 100x',
    minBet: '0.10 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    faqs: [
      { q: 'Что делает рыбак в бесплатных спинах?', a: 'Рыбак-Wild собирает все денежные символы (рыбы) на экране и суммирует их стоимость.' },
      { q: 'Есть ли Buy Bonus?', a: 'Да, стоит 100× ставки и сразу запускает бонусные спины.' },
    ],
  },
  {
    slug: 'starlight-princess',
    name: 'Starlight Princess',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.5%',
    type: 'slot',
    icon: '⭐',
    color: '#f472b6',
    volatility: 'very-high',
    description: 'Аниме-принцесса и множители до ×500. Механика аналогична Gates of Olympus.',
    metaDesc: 'Starlight Princess играть онлайн 2026. Казино с Старлайт Принцесс. RTP 96.5%, макс. 5000x.',
    longDesc: 'Starlight Princess от Pragmatic Play — аниме-слот 6×5, кластерные выигрыши. Механика почти идентична Gates of Olympus, но с другой тематикой. Множители до ×500, Buy Feature, 15 фриспинов.',
    features: ['RTP 96.5%', 'Кластеры 8+', 'Множители до ×500', 'Buy Feature', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [
      { q: 'Чем Starlight Princess отличается от Gates of Olympus?', a: 'Та же механика, другая тема. У Starlight чуть другие частоты попадания бонуса.' },
    ],
  },
  {
    slug: 'sugar-rush',
    name: 'Sugar Rush 1000',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.53%',
    type: 'slot',
    icon: '🍬',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Конфетный слот 7×7 с множителями во всём поле. Максимум 5 000x.',
    metaDesc: 'Sugar Rush 1000 играть онлайн 2026. RTP 96.53%, решётка 7×7, множители везде.',
    longDesc: 'Sugar Rush 1000 — расширенная версия Sugar Rush. Решётка 7×7, множители могут появиться на любой ячейке. В бонусе множители накапливаются и суммируются.',
    features: ['RTP 96.53%', 'Решётка 7×7', 'Множители везде', 'Авто-множитель 1000x', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── SPRIBE ──
  {
    slug: 'aviator',
    name: 'Aviator',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'crash',
    icon: '✈️',
    color: '#ef4444',
    volatility: 'high',
    description: 'Самолёт взлетает, коэффициент растёт — успей забрать до крэша. RTP 97%.',
    metaDesc: 'Aviator играть онлайн 2026. Казино с Авиатор от Spribe. RTP 97%, стратегии, лучшие казино.',
    longDesc: 'Aviator от Spribe — краш-игра нового поколения. Самолёт взлетает, множитель растёт от 1.00×. Нужно успеть нажать "Вывести" до крэша. RTP 97%, провабли фэйр. Можно ставить 2 ставки одновременно.',
    features: ['RTP 97%', 'Множители до 1000×', 'Авто-вывод', 'Чат игроков', '2 ставки одновременно'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Какова лучшая стратегия в Aviator?', a: 'Стратегия двойной ставки: одна на ×1.5 (безопасная), вторая на ×5–×10 (рисковая). Но результаты случайны.' },
      { q: 'Можно ли обмануть Aviator?', a: 'Нет. Игра использует провабли-фэйр алгоритм — каждый раунд случаен и верифицирован.' },
    ],
  },
  {
    slug: 'mines',
    name: 'Mines',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '💣',
    color: '#f97316',
    volatility: 'medium',
    description: 'Поле с минами — открывай клетки и забирай выигрыш. Чем дальше — тем выше множитель.',
    metaDesc: 'Mines игра 2026. Казино с Майнс от Spribe. Играть в мины онлайн. RTP 97%.',
    longDesc: 'Mines — простая но захватывающая игра. Выберите количество мин (1–24) и открывайте клетки 5×5. Каждая безопасная клетка увеличивает множитель. В любой момент можно забрать выигрыш.',
    features: ['RTP 97%', '1–24 мины', 'Авто-пик', 'Провабли фэйр', 'Настраиваемый риск'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Сколько мин лучше ставить?', a: '3 мины — хороший баланс риска и награды. При 1 мине низкие множители, при 24 — почти невозможно.' },
    ],
  },
  {
    slug: 'plinko',
    name: 'Plinko',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '🎯',
    color: '#22c55e',
    volatility: 'medium',
    description: 'Шарик падает по пирамиде пинов — куда упадёт, такой множитель получите.',
    metaDesc: 'Plinko играть онлайн 2026. Казино с Плинко. Spribe Plinko RTP 97%.',
    longDesc: 'Plinko — виральная игра по мотивам известного шоу. Шарик падает через пирамиду из штырьков и попадает в одну из ячеек с множителями. Можно настроить риск (низкий/средний/высокий) и количество рядов.',
    features: ['RTP 97%', '8–16 рядов', '3 уровня риска', 'Авто-игра', 'До 1000×'],
    maxWin: '1 000x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как увеличить шанс на большой выигрыш?', a: 'Высокий риск + больше рядов = редкие, но огромные выигрыши. Низкий риск = стабильные небольшие призы.' },
    ],
  },
  {
    slug: 'dice',
    name: 'Dice',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '🎲',
    color: '#6366f1',
    volatility: 'medium',
    description: 'Классический кубик с настраиваемыми шансами. Ставь выше или ниже определённого числа.',
    metaDesc: 'Dice игра онлайн 2026. Spribe Dice — настраиваемые ставки, RTP 97%.',
    longDesc: 'Dice — минималистичная игра с кубиком. Вы сами выбираете диапазон победы: чем меньше шанс — тем выше множитель. Мгновенные результаты, провабли-фэйр.',
    features: ['RTP 97%', 'Настраиваемый шанс', 'Авто-игра', 'Провабли фэйр', 'Моментальный результат'],
    maxWin: '9 900x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    faqs: [],
  },

  // ── 1WIN GAMES ──
  {
    slug: 'lucky-jet',
    name: 'Lucky Jet',
    provider: '1Win Games',
    providerSlug: '1win-games',
    rtp: '97%',
    type: 'crash',
    icon: '🚀',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Лаки взлетает на реактивном ранце — множитель растёт, успей забрать!',
    metaDesc: 'Lucky Jet играть онлайн 2026. Казино с Лаки Джет. RTP 97%, стратегии и советы.',
    longDesc: 'Lucky Jet — краш-игра от 1Win Games. Персонаж Лаки летит на ракетном ранце. Механика как в Aviator: множитель растёт, нужно забрать до краша. RTP 97%, провабли-фэйр.',
    features: ['RTP 97%', 'До ×200', '2 ставки одновременно', 'Авто-вывод', 'Статистика раундов'],
    maxWin: '200x',
    minBet: '1 ₽',
    casinoSlugs: ['1win'],
    popular: true,
    faqs: [
      { q: 'Чем Lucky Jet отличается от Aviator?', a: 'Lucky Jet эксклюзивна для 1Win. Другой визуал, максимум ×200 вместо ×1000 у Aviator.' },
    ],
  },

  // ── EVOLUTION GAMING ──
  {
    slug: 'crazy-time',
    name: 'Crazy Time',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.08%',
    type: 'live',
    icon: '🎡',
    color: '#4ade80',
    volatility: 'high',
    description: 'Колесо фортуны с 4 бонусными играми. Ведущий в прямом эфире, выигрыши до 20 000×.',
    metaDesc: 'Crazy Time играть онлайн 2026. Казино с Крейзи Тайм. Evolution Gaming live шоу.',
    longDesc: 'Crazy Time — флагманское live-шоу Evolution Gaming. Колесо 54 сегмента, 4 бонусные игры: Cash Hunt, Pachinko, Coin Flip, Crazy Time. В бонусе Crazy Time ×20 000.',
    features: ['RTP 96.08%', '4 бонус-игры', 'HD трансляция', 'Макс. 20 000×', 'Живой ведущий'],
    maxWin: '20 000x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как попасть в Crazy Time бонус?', a: 'Нужно угадать сегмент "Crazy Time" (1 из 54). Вероятность 1/54 ≈ 1.85%.' },
    ],
  },
  {
    slug: 'lightning-roulette',
    name: 'Lightning Roulette',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '97.3%',
    type: 'live',
    icon: '⚡',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Рулетка с молниями — случайные числа получают множитель ×50–×500.',
    metaDesc: 'Lightning Roulette играть онлайн 2026. Казино с Лайтнинг Рулетка. Evolution RTP 97.3%.',
    longDesc: 'Lightning Roulette — инновационная европейская рулетка от Evolution. Перед каждым спином 1–5 чисел получают "молнию" с множителем ×50, ×100, ×200, ×300, ×400 или ×500.',
    features: ['RTP 97.3%', 'Множители ×50–×500', 'HD трансляция', 'Живой ведущий', 'Европейская рулетка'],
    maxWin: '500x',
    minBet: '20 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    popular: true,
    faqs: [
      { q: 'Чем Lightning Roulette лучше обычной?', a: 'На числа с молнией можно получить до 500× вместо обычных 35×. Подходит любителям крупных выигрышей.' },
    ],
  },
  {
    slug: 'monopoly-live',
    name: 'Monopoly Live',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.23%',
    type: 'live',
    icon: '🎩',
    color: '#22c55e',
    volatility: 'high',
    description: 'Колесо Монополии + 3D бонус-раунд. Мистер Монополия ходит по доске и множит призы.',
    metaDesc: 'Monopoly Live играть онлайн 2026. Казино с Монополи Лайв. Evolution Gaming.',
    longDesc: 'Monopoly Live объединяет колесо фортуны и 3D-бонус на доске Монополии. Попадите в Chance или 2-Rolls/4-Rolls чтобы запустить бонус, где Mr. Monopoly ходит по доске и собирает выигрыши.',
    features: ['RTP 96.23%', '3D бонус-раунд', 'Живой ведущий', 'Авто-ставка', 'Макс. 1500×'],
    maxWin: '1 500x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },

  // ── NOVOMATIC ──
  {
    slug: 'book-of-ra',
    name: 'Book of Ra',
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.1%',
    type: 'slot',
    icon: '📚',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Легендарный египетский слот. Книга = Wild и Scatter. Расширяющийся символ в бонусе.',
    metaDesc: 'Book of Ra играть онлайн 2026. Казино с Книгой Ра. Novomatic, RTP 95.1%.',
    longDesc: 'Book of Ra — один из первых классических слотов. 5 барабанов, 9 линий. Книга работает и как Wild, и как Scatter. 3+ книги = 10 бесплатных спинов с расширяющимся символом.',
    features: ['RTP 95.1%', '5×3, 9 линий', 'Wild+Scatter', '10 фриспинов', 'Гамбл-функция'],
    maxWin: '5 000x',
    minBet: '1 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Book of Ra Deluxe или Classic — что лучше?', a: 'Deluxe имеет 10 линий вместо 9 и чуть лучший RTP. Большинство игроков предпочитают Deluxe.' },
    ],
  },
  {
    slug: 'book-of-ra-deluxe',
    name: 'Book of Ra Deluxe',
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.5%',
    type: 'slot',
    icon: '📖',
    color: '#f97316',
    volatility: 'high',
    description: 'Улучшенная версия классики — 10 линий, чуть лучший RTP и обновлённая графика.',
    metaDesc: 'Book of Ra Deluxe играть онлайн 2026. RTP 95.5%, 10 линий, лучшая версия Книги Ра.',
    longDesc: 'Book of Ra Deluxe — улучшенная редакция 2008 года. 5×3, 10 активных линий (против 9 в Classic). Та же механика с книгой-Wild/Scatter, 10 бесплатных спинов.',
    features: ['RTP 95.5%', '10 линий', 'Wild+Scatter', '10 фриспинов', 'HD графика'],
    maxWin: '5 000x',
    minBet: '1 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    popular: true,
    faqs: [],
  },

  // ── HACKSAW ──
  {
    slug: 'tower-rush',
    name: 'Tower Rush',
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '97%',
    type: 'crash',
    icon: '🏗️',
    color: '#38bdf8',
    volatility: 'high',
    description: 'Строй башню как можно выше — каждый этаж увеличивает выигрыш. Опасайся обрушения!',
    metaDesc: 'Tower Rush играть онлайн 2026. Казино с Тауэр Раш. RTP 97%, Hacksaw Gaming.',
    longDesc: 'Tower Rush от Hacksaw Gaming — краш-игра с механикой строительства башни. Каждый добавленный этаж увеличивает множитель. Заберите выигрыш до обрушения. Чем выше башня — тем больше риск.',
    features: ['RTP 97%', 'Накопительный множитель', 'Авто-стоп', 'Провабли фэйр', 'Мгновенная игра'],
    maxWin: '500x',
    minBet: '1 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    isNew: true,
    popular: true,
    faqs: [
      { q: 'Чем Tower Rush отличается от Aviator?', a: 'Механика башни вместо самолёта. Другая динамика нарастания риска.' },
    ],
  },
  {
    slug: 'squealin-riches',
    name: 'Squealin\' Riches',
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '96%',
    type: 'slot',
    icon: '🐷',
    color: '#e879f9',
    volatility: 'very-high',
    description: 'Свинки-богачи с денежными призами и прогрессивными джекпотами.',
    metaDesc: 'Squealin Riches играть онлайн. Hacksaw Gaming, денежные свинки, прогрессив.',
    longDesc: 'Squealin\' Riches — уникальный слот Hacksaw с денежными призами внутри символов. Во время бонуса свиньи копят монеты, которые затем выплачиваются.',
    features: ['RTP 96%', 'Денежные символы', 'Прогрессив', 'Бонусный раунд', 'Макс. 10 000×'],
    maxWin: '10 000x',
    minBet: '0.20 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    faqs: [],
  },

  // ── BGAMING ──
  {
    slug: 'banana-party',
    name: 'Banana Party',
    provider: 'BGaming',
    providerSlug: 'bgaming',
    rtp: '97%',
    type: 'slot',
    icon: '🍌',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Банановая вечеринка с обезьянами — фиксированные джекпоты и множители в бонусе.',
    metaDesc: 'Banana Party играть онлайн 2026. Казино с Банана Пати. BGaming, RTP 97%.',
    longDesc: 'Banana Party от BGaming — весёлый слот с обезьянами. 5×3, 20 линий. Scatter запускает бесплатные спины с накопительными джекпотами. Один из самых высоких RTP среди слотов.',
    features: ['RTP 97%', 'Фиксированные джекпоты', 'Бесплатные спины', '20 линий', 'Авто-игра'],
    maxWin: '2 000x',
    minBet: '0.20 ₽',
    casinoSlugs: BGAMING_CASINOS,
    popular: true,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'cash-or-crash',
    name: 'Cash or Crash',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '97%',
    type: 'live',
    icon: '💸',
    color: '#22c55e',
    volatility: 'medium',
    description: 'Live-игра с воздушным шаром. Собирай деньги или рискни ради большего приза.',
    metaDesc: 'Cash or Crash играть онлайн. Evolution Gaming, RTP 97%, live-игра с шаром.',
    longDesc: 'Cash or Crash — live-игра Evolution в стиле карточной. Воздушный шар поднимается, денежные шары добавляют призы. В любой момент можно "Cash" — забрать деньги, или "Crash" — продолжить.',
    features: ['RTP 97%', 'Живой ведущий', 'Cash или Crash решение', 'Зелёный/красный шар', 'До ×10 000'],
    maxWin: '10 000x',
    minBet: '5 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },
  {
    slug: 'starburst',
    name: 'Starburst',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '96.1%',
    type: 'slot',
    icon: '💎',
    color: '#6366f1',
    volatility: 'low',
    description: 'Классический неоновый слот с Expanding Wilds. Низкая волатильность, частые выигрыши.',
    metaDesc: 'Starburst играть онлайн 2026. Казино со Старбёрст NetEnt. RTP 96.1%, Expanding Wilds.',
    longDesc: 'Starburst — один из самых популярных слотов в истории. 5×3, 10 линий, выигрыши в обе стороны. Wild расширяется на весь барабан и запускает до 3 респ.инов. Идеален для отыгрыша бонусов.',
    features: ['RTP 96.1%', 'Expanding Wild', '3 бесплатных респ.ина', 'Выигрыши в 2 стороны', 'Низкая дисперсия'],
    maxWin: '500x',
    minBet: '0.10 ₽',
    casinoSlugs: NETENT_CASINOS,
    popular: true,
    faqs: [
      { q: 'Почему Starburst используют для отыгрыша бонусов?', a: 'Низкая волатильность обеспечивает стабильные небольшие выигрыши, что позволяет медленно отыгрывать вейджер.' },
    ],
  },
  {
    slug: 'gonzo-quest',
    name: 'Gonzo\'s Quest',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '95.97%',
    type: 'slot',
    icon: '🗿',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Конкистадор ищет Эльдорадо. Механика Avalanche, множители до ×15 в бесплатных спинах.',
    metaDesc: 'Gonzo\'s Quest играть онлайн 2026. NetEnt, RTP 95.97%, Avalanche механика.',
    longDesc: 'Gonzo\'s Quest — революционный слот NetEnt с механикой Avalanche (предшественник Tumble). 5×3, 20 линий. Последовательные победы увеличивают множитель до ×5 в обычной игре и ×15 в бонусе.',
    features: ['RTP 95.97%', 'Avalanche механика', 'Множители ×1–×15', '10 бесплатных спинов', '20 линий'],
    maxWin: '2 500x',
    minBet: '0.20 ₽',
    casinoSlugs: NETENT_CASINOS,
    faqs: [],
  },

  // ── PUSH GAMING ──
  {
    slug: 'jammin-jars',
    name: 'Jammin\' Jars',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.83%',
    type: 'slot',
    icon: '🍓',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Фруктовый слот 8×8 с Cluster Pays. Rainbow Feature и Wild Multipliers — до 20 000×.',
    metaDesc: 'Jammin Jars играть онлайн 2026. Push Gaming, RTP 96.83%, Cluster Pays, до 20000x.',
    longDesc: 'Jammin\' Jars — культовый слот Push Gaming. Сетка 8×8, кластерные выигрыши. В бонусе джемы-Wilds движутся по барабанам, собирая множители. Максимальный выигрыш 20 000×.',
    features: ['RTP 96.83%', 'Cluster Pays 8×8', 'Wild Multipliers', 'Rainbow Feature', 'Макс. 20 000×'],
    maxWin: '20 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как работает Rainbow Feature?', a: 'Радуга добавляет дополнительные Wild на поле перед бонусными спинами, увеличивая потенциал.' },
    ],
  },
  {
    slug: 'fat-santa',
    name: 'Fat Santa',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.56%',
    type: 'slot',
    icon: '🎅',
    color: '#ef4444',
    volatility: 'high',
    description: 'Новогодний слот с толстым Сантой. Wild Multipliers и бесплатные спины — до 10 000×.',
    metaDesc: 'Fat Santa играть онлайн 2026. Push Gaming, RTP 96.56%, новогодний слот.',
    longDesc: 'Fat Santa — рождественский слот Push Gaming. 6×4, 4096 способов выиграть. Санта-Wild множит выигрыши. В бонусе Санта становится больше с каждым спином.',
    features: ['RTP 96.56%', '6×4 сетка', 'Wild Multipliers', 'Expanding Santa', '4096 линий'],
    maxWin: '10 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    faqs: [],
  },
  {
    slug: 'wild-swarm',
    name: 'Wild Swarm',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.48%',
    type: 'slot',
    icon: '🐝',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Пчелиный слот с уникальной механикой роя. Wilds заполняют целые барабаны.',
    metaDesc: 'Wild Swarm играть онлайн 2026. Push Gaming, рой диких символов, RTP 96.48%.',
    longDesc: 'Wild Swarm — слот Push Gaming с механикой пчелиного роя. 5×3, 243 линии. Wild могут образовывать рой и заполнять весь барабан. Уникальная бонусная система с ульями.',
    features: ['RTP 96.48%', 'Swarm механика', 'Full Reel Wilds', 'Honey Pot бонус', '243 линии'],
    maxWin: '6 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    faqs: [],
  },

  // ── NOLIMIT CITY ──
  {
    slug: 'san-quentin',
    name: 'San Quentin xWays',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.43%',
    type: 'slot',
    icon: '🔒',
    color: '#64748b',
    volatility: 'very-high',
    description: 'Самый суровый слот в истории. Тюремная тематика, xWays механика, потенциал 150 000×.',
    metaDesc: 'San Quentin играть онлайн 2026. Nolimit City, xWays, максимум 150000x.',
    longDesc: 'San Quentin xWays от Nolimit City — один из самых высоковолатильных слотов. Тюремная тема, механики xWays (символы с несколькими иконками) и xNudge (Wild с множителем). RTP 96.43%, потенциал до 150 000×.',
    features: ['RTP 96.43%', 'xWays механика', 'xNudge Wilds', 'Макс. 150 000×', 'Экстремальная дисперсия'],
    maxWin: '150 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    popular: true,
    faqs: [
      { q: 'Что такое xWays?', a: 'Символ xWays раскрывается в 2–6 обычных символов, резко увеличивая число линий и выигрыш.' },
    ],
  },
  {
    slug: 'mental',
    name: 'Mental',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.3%',
    type: 'slot',
    icon: '🧠',
    color: '#a855f7',
    volatility: 'very-high',
    description: 'Психиатрическая тема, безумные механики. xBomb, xSplit — потенциал 43 200×.',
    metaDesc: 'Mental играть онлайн 2026. Nolimit City, xBomb, xSplit, до 43200x.',
    longDesc: 'Mental — слот Nolimit City с психиатрической тематикой. xBomb уничтожает соседние символы и добавляет множитель. xSplit дублирует символы. Очень высокая волатильность.',
    features: ['RTP 96.3%', 'xBomb механика', 'xSplit символы', 'Макс. 43 200×', 'Высочайшая дисперсия'],
    maxWin: '43 200x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'tombstone-rip',
    name: 'Tombstone R.I.P.',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.08%',
    type: 'slot',
    icon: '🪦',
    color: '#475569',
    volatility: 'very-high',
    description: 'Дикий Запад и кладбище. xNudge и xWays механики, 200 000× максимальный выигрыш.',
    metaDesc: 'Tombstone RIP играть онлайн 2026. Nolimit City, Дикий Запад, до 200000x.',
    longDesc: 'Tombstone R.I.P. — сиквел Tombstone. Дикий Запад, могильная тема. xNudge Wilds накапливают множители с каждым нажатием. Максимальный потенциал 200 000× — один из самых высоких в индустрии.',
    features: ['RTP 96.08%', 'xNudge Wilds', 'Макс. 200 000×', 'Shoot Out бонус', 'xWays механика'],
    maxWin: '200 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── PLAY'N GO ──
  {
    slug: 'book-of-dead',
    name: 'Book of Dead',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.21%',
    type: 'slot',
    icon: '☀️',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетский слот — духовный наследник Book of Ra. Расширяющийся символ в 10 фриспинах.',
    metaDesc: 'Book of Dead играть онлайн 2026. Play\'n GO, RTP 96.21%, казино с Book of Dead.',
    longDesc: 'Book of Dead от Play\'n GO — один из самых популярных слотов Европы. 5×3, 10 линий. Книга — Wild и Scatter одновременно. 3+ Scatter = 10 бесплатных спинов с расширяющимся символом. Схожа с Book of Ra, но лучший RTP.',
    features: ['RTP 96.21%', '10 фриспинов', 'Расширяющийся символ', 'Wild+Scatter', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.01 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [
      { q: 'Book of Dead или Book of Ra — что лучше?', a: 'Book of Dead имеет лучший RTP (96.21% vs 95.1%) и более современную графику. Механика идентична.' },
    ],
  },
  {
    slug: 'reactoonz',
    name: 'Reactoonz',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.51%',
    type: 'slot',
    icon: '👾',
    color: '#22c55e',
    volatility: 'high',
    description: 'Инопланетяне в сетке 7×7, Cluster Pays. Quantum механика с 4 типами бонусов.',
    metaDesc: 'Reactoonz играть онлайн 2026. Play\'n GO, RTP 96.51%, Cluster Pays, Quantum бонусы.',
    longDesc: 'Reactoonz — уникальный слот 7×7 с Cluster Pays. Cute-инопланетяне заполняют поле. Quantum Wilds, Blooming Wilds, Chain Reaction, Implosion — 4 типа бонусных механик. Gargantoon Wild — огромный символ 3×3.',
    features: ['RTP 96.51%', 'Cluster Pays 7×7', '4 Quantum механики', 'Gargantoon Wild', 'Макс. 4 570×'],
    maxWin: '4 570x',
    minBet: '0.20 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'legacy-of-egypt',
    name: 'Legacy of Egypt',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.5%',
    type: 'slot',
    icon: '🏛️',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетский слот с колесом фортуны в бонусе. Множители и джекпоты.',
    metaDesc: 'Legacy of Egypt играть онлайн 2026. Play\'n GO, колесо бонусов, до 10000x.',
    longDesc: 'Legacy of Egypt от Play\'n GO — египетский слот с уникальным колесом в бонусе. 5×3, 10 линий. Wild-скараб. В бонусном колесе разыгрываются множители, мини-джекпоты и бесплатные спины.',
    features: ['RTP 96.5%', 'Колесо бонусов', 'Wild-скараб', 'Прогрессивные джекпоты', 'Макс. 10 000×'],
    maxWin: '10 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    faqs: [],
  },

  // ── RED TIGER ──
  {
    slug: 'gonzos-gold',
    name: "Gonzo's Gold",
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '95.99%',
    type: 'slot',
    icon: '🏺',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Новый Гонсо от Red Tiger с механикой Cluster Pays и Avalanche.',
    metaDesc: "Gonzo's Gold играть онлайн 2026. Red Tiger, RTP 95.99%, Cluster Pays.",
    longDesc: "Gonzo's Gold — современная интерпретация Gonzo's Quest от Red Tiger. Cluster Pays, Avalanche механика. В бонусе Gonzo находит сокровища Эльдорадо с нарастающими множителями.",
    features: ['RTP 95.99%', 'Cluster Pays', 'Avalanche механика', 'Дикие множители', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'dragons-luck',
    name: "Dragon's Luck",
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '96.72%',
    type: 'slot',
    icon: '🐉',
    color: '#ef4444',
    volatility: 'medium',
    description: 'Азиатский слот с удачей дракона. Прогрессивные суперпризы и дикие расширения.',
    metaDesc: "Dragon's Luck играть онлайн 2026. Red Tiger, RTP 96.72%, азиатская тема.",
    longDesc: "Dragon's Luck — элегантный азиатский слот Red Tiger. 5×3, 10 линий. Особый символ Super Prize Dragon активирует прогрессивный джекпот. Wild расширяется на весь барабан.",
    features: ['RTP 96.72%', 'Super Prize Dragon', 'Expanding Wild', 'Daily Jackpot', '10 линий'],
    maxWin: '3 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    popular: true,
    faqs: [],
  },

  // ── YGGDRASIL ──
  {
    slug: 'vikings-go-berzerk',
    name: 'Vikings Go Berzerk',
    provider: 'Yggdrasil',
    providerSlug: 'yggdrasil',
    rtp: '96.1%',
    type: 'slot',
    icon: '⚔️',
    color: '#6366f1',
    volatility: 'high',
    description: 'Викинги сражаются с морскими чудищами. Берсерк-режим и накопительные спины.',
    metaDesc: 'Vikings Go Berzerk играть онлайн 2026. Yggdrasil, RTP 96.1%, берсерки.',
    longDesc: 'Vikings Go Berzerk — культовый слот Yggdrasil. 5 барабанов, 25 линий. Каждый викинг накапливает ярость и уходит в Berzerk-режим с множителями. Сражение с морским змеем в бонусе.',
    features: ['RTP 96.1%', 'Berzerk режим', '4 викинга с накопителями', 'Rage-метр', 'Макс. 4 425×'],
    maxWin: '4 425x',
    minBet: '0.25 ₽',
    casinoSlugs: YGGDRASIL_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'valley-of-the-gods',
    name: 'Valley of the Gods',
    provider: 'Yggdrasil',
    providerSlug: 'yggdrasil',
    rtp: '96.1%',
    type: 'slot',
    icon: '🌅',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетские боги и скарабеи. Заблокированные позиции открываются символами скарабея.',
    metaDesc: 'Valley of the Gods играть онлайн 2026. Yggdrasil, RTP 96.1%, египетская тема.',
    longDesc: 'Valley of the Gods — египетский слот Yggdrasil с уникальной механикой. Часть позиций заблокирована скарабеями. Каждый проигрышный спин открывает позиции. Когда все разблокированы — активируется Multiplier Mode.',
    features: ['RTP 96.1%', 'Scarab механика', 'Multiplier Mode', 'Re-spin система', 'Макс. 3 600×'],
    maxWin: '3 600x',
    minBet: '0.25 ₽',
    casinoSlugs: YGGDRASIL_CASINOS,
    faqs: [],
  },

  // ── PRAGMATIC PLAY (дополнительно) ──
  {
    slug: 'wolf-gold',
    name: 'Wolf Gold',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.01%',
    type: 'slot',
    icon: '🐺',
    color: '#1d4ed8',
    volatility: 'high',
    description: 'Волк, бизон и орёл в прерии. Три джекпота, Money Respin и бонусные спины.',
    metaDesc: 'Wolf Gold играть онлайн 2026. Pragmatic Play, RTP 96%, джекпот, Money Respin.',
    longDesc: 'Wolf Gold — один из самых популярных слотов Pragmatic Play. 5×3, 25 линий. Три джекпота: Mini, Major, Mega. Money Respin: дополнительные спины при 6+ денежных символах на экране.',
    features: ['RTP 96.01%', '3 Джекпота', 'Money Respin', '25 линий', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.25 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как выиграть джекпот в Wolf Gold?', a: 'Нужно заполнить весь экран Money символами в режиме Money Respin.' },
    ],
  },
  {
    slug: 'wild-west-gold',
    name: 'Wild West Gold',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '🤠',
    color: '#92400e',
    volatility: 'very-high',
    description: 'Ковбои Дикого Запада со Sticky Wilds и множителями до ×5 в бесплатных спинах.',
    metaDesc: 'Wild West Gold играть онлайн 2026. Pragmatic Play, ковбои, Sticky Wild, RTP 96.51%.',
    longDesc: 'Wild West Gold — вестерн-слот 5×4, 40 линий. Sticky Wild с множителем ×2 или ×3. В бесплатных спинах Wilds остаются на месте и накапливают множители до ×5. Buy Feature 100× ставки.',
    features: ['RTP 96.51%', 'Sticky Wild ×2–×3', '40 линий', '8 фриспинов', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'fruit-party',
    name: 'Fruit Party',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.5%',
    type: 'slot',
    icon: '🍇',
    color: '#7c3aed',
    volatility: 'very-high',
    description: 'Фруктовый кластерный слот 7×7 с Tumble и случайными множителями.',
    metaDesc: 'Fruit Party играть онлайн 2026. Pragmatic Play, кластеры 7×7, RTP 96.5%.',
    longDesc: 'Fruit Party от Pragmatic Play — кластерный слот 7×7. Победные кластеры от 5 символов. Случайные множители появляются на поле перед каждым спином. В бонусе гарантированные множители.',
    features: ['RTP 96.5%', 'Cluster Pays 7×7', 'Случайные множители', 'Buy Bonus', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    faqs: [],
  },
  {
    slug: 'the-hand-of-midas',
    name: 'The Hand of Midas',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.54%',
    type: 'slot',
    icon: '🤲',
    color: '#ca8a04',
    volatility: 'very-high',
    description: 'Золотая рука Мидаса превращает символы в Wild. Sticky Wilds и цепочки трансформаций.',
    metaDesc: 'The Hand of Midas играть онлайн 2026. Pragmatic Play, золотая рука, RTP 96.54%.',
    longDesc: 'The Hand of Midas — мифологический слот 5×3 с механикой Midas Touch. Специальный символ руки превращает случайные символы в Wild. В бонусном режиме рука активируется каждый спин.',
    features: ['RTP 96.54%', 'Midas Touch', 'Wild трансформация', 'Gamble Feature', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'floating-dragon',
    name: 'Floating Dragon',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.49%',
    type: 'slot',
    icon: '🐲',
    color: '#dc2626',
    volatility: 'very-high',
    description: 'Азиатский дракон с Tumble механикой и плавающим Wild. Новогодняя азиатская эстетика.',
    metaDesc: 'Floating Dragon играть онлайн 2026. Pragmatic Play, азиатский слот, Tumble, RTP 96.49%.',
    longDesc: 'Floating Dragon — азиатский слот 6×5 с Tumble механикой. Дракон-Wild плавает по экрану. В бонусе дракон собирает множители с каждым Tumble. Гарантированные выигрыши в бонусных спинах.',
    features: ['RTP 96.49%', 'Tumble механика', 'Плавающий Wild', 'Гарантированный бонус', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'gems-bonanza',
    name: 'Gems Bonanza',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.51%',
    type: 'slot',
    icon: '💎',
    color: '#0ea5e9',
    volatility: 'very-high',
    description: 'Драгоценные камни в сетке 8×8 с Cluster Pays. Tumble и накопительные множители.',
    metaDesc: 'Gems Bonanza играть онлайн 2026. Pragmatic Play, 8×8, кластеры, RTP 96.51%.',
    longDesc: 'Gems Bonanza — слот 8×8 с кластерными выигрышами от 5 символов. Tumble механика. В бонусе каждый уровень Tumble добавляет множитель. Максимальный потенциал при полном поле драгоценностей.',
    features: ['RTP 96.51%', 'Cluster Pays 8×8', 'Tumble механика', 'Нарастающие множители', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    faqs: [],
  },
  {
    slug: 'big-bass-splash',
    name: 'Big Bass Splash',
    provider: 'Pragmatic Play',
    providerSlug: 'pragmatic-play',
    rtp: '96.71%',
    type: 'slot',
    icon: '🐠',
    color: '#0284c7',
    volatility: 'high',
    description: 'Продолжение Big Bass Bonanza — подводная рыбалка. Рыбак собирает денежные символы.',
    metaDesc: 'Big Bass Splash играть онлайн 2026. Pragmatic Play, рыбалка, RTP 96.71%.',
    longDesc: 'Big Bass Splash — подводная версия Big Bass Bonanza. Та же механика с рыбаком-Wild, но новые символы и расширенное поле. Дополнительные денежные символы увеличивают потенциал бонуса.',
    features: ['RTP 96.71%', 'Рыбак-Wild', '10 фриспинов', 'Денежные символы', 'Макс. 2 100×'],
    maxWin: '2 100x',
    minBet: '0.10 ₽',
    casinoSlugs: PRAGMATIC_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── EVOLUTION (дополнительно) ──
  {
    slug: 'dream-catcher',
    name: 'Dream Catcher',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.58%',
    type: 'live',
    icon: '🌀',
    color: '#8b5cf6',
    volatility: 'medium',
    description: 'Колесо фортуны с живым ведущим. Первое live-шоу Evolution — простое и захватывающее.',
    metaDesc: 'Dream Catcher играть онлайн 2026. Evolution Gaming, колесо фортуны, live шоу.',
    longDesc: 'Dream Catcher — классическое колесо фортуны от Evolution. 54 сегмента: 1, 2, 5, 10, 20, 40 и множители ×2/×7. Простые правила, живой ведущий и потенциал до 500×.',
    features: ['RTP 96.58%', 'Колесо 54 сегмента', 'Множители ×2 и ×7', 'Живой ведущий', 'HD трансляция'],
    maxWin: '500x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },
  {
    slug: 'mega-ball',
    name: 'Mega Ball',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '95.4%',
    type: 'live',
    icon: '🎱',
    color: '#2563eb',
    volatility: 'high',
    description: 'Live-лото с карточками и Mega Ball множителем до ×1000. Огромные выигрыши — редко, но реально.',
    metaDesc: 'Mega Ball играть онлайн 2026. Evolution Gaming, live лото, Mega Ball ×1000.',
    longDesc: 'Mega Ball — live-игра в стиле лото от Evolution. 24 шара на 1–4 карточках. Mega Ball умножает выигрыши на ×5–×1000. Чем больше карточек — тем выше шанс на крупный выигрыш.',
    features: ['RTP 95.4%', 'До 200 карточек', 'Mega Ball ×5–×1000', 'Живой ведущий', 'Макс. ~1000×'],
    maxWin: '1 000x',
    minBet: '5 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [
      { q: 'Сколько карточек брать в Mega Ball?', a: 'Чем больше карточек — тем выше математическое ожидание. Максимум 200 карточек за один раунд.' },
    ],
  },
  {
    slug: 'deal-or-no-deal-live',
    name: 'Deal or No Deal Live',
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '95.42%',
    type: 'live',
    icon: '💼',
    color: '#0369a1',
    volatility: 'high',
    description: 'Телешоу в прямом эфире. Откройте свой кейс — получите джекпот или договоритесь с банком.',
    metaDesc: 'Deal or No Deal Live играть 2026. Evolution Gaming, телешоу онлайн, кейсы с призами.',
    longDesc: 'Deal or No Deal Live — адаптация знаменитого ТВ-шоу от Evolution. Три раунда квалификации, затем финальная игра с чемоданами. Банкир делает предложение на основе оставшихся призов.',
    features: ['RTP 95.42%', 'Финальная игра с кейсами', 'Случайный джекпот', 'Живой ведущий', 'Квалификация'],
    maxWin: '500 000x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    faqs: [],
  },
  {
    slug: 'gonzos-treasure-hunt',
    name: "Gonzo's Treasure Hunt",
    provider: 'Evolution',
    providerSlug: 'evolution',
    rtp: '96.56%',
    type: 'live',
    icon: '🗺️',
    color: '#d97706',
    volatility: 'high',
    description: 'Live-игра с Гонсо — выбирай камни на стене сокровищ. Multiplier Stone до ×2000.',
    metaDesc: "Gonzo's Treasure Hunt играть онлайн 2026. Evolution Gaming, Гонсо live, до 2000x.",
    longDesc: "Gonzo's Treasure Hunt — инновационная live-игра с AR-технологиями. Стена сокровищ 6×8 = 48 камней. Выберите от 1 до 20 камней. Скрытые призы и Multiplier Stone увеличивают выигрыш до ×2000.",
    features: ['RTP 96.56%', 'Стена сокровищ 6×8', 'Multiplier Stone до ×2000', 'AR технологии', 'Live Gonzo'],
    maxWin: '2 000x',
    minBet: '10 ₽',
    casinoSlugs: EVOLUTION_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── NOVOMATIC (дополнительно) ──
  {
    slug: 'sizzling-hot-deluxe',
    name: 'Sizzling Hot Deluxe',
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.66%',
    type: 'slot',
    icon: '🍋',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Классические фрукты — лимон, вишня, арбуз, семёрки. Легендарный слот от Novomatic.',
    metaDesc: 'Sizzling Hot Deluxe играть онлайн 2026. Novomatic, классические фрукты, RTP 95.66%.',
    longDesc: 'Sizzling Hot Deluxe — культовый фруктовый слот Novomatic. 5 барабанов, 5 линий. Никаких бонусов — чистая классика. Семёрки и бары дают крупные выплаты. Гамбл-функция для удвоения.',
    features: ['RTP 95.66%', '5×3, 5 линий', 'Гамбл-функция', 'Классические символы', 'Без бонусов'],
    maxWin: '50 000x',
    minBet: '0.40 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'lucky-ladys-charm',
    name: "Lucky Lady's Charm Deluxe",
    provider: 'Novomatic',
    providerSlug: 'novomatic',
    rtp: '95.13%',
    type: 'slot',
    icon: '🍀',
    color: '#22c55e',
    volatility: 'medium',
    description: 'Четырёхлистный клевер и удача. 15 бесплатных спинов со случайным Wild-символом.',
    metaDesc: 'Lucky Lady Charm играть онлайн 2026. Novomatic, клевер удачи, RTP 95.13%.',
    longDesc: "Lucky Lady's Charm Deluxe — романтический слот Novomatic. 5×3, 10 линий. Хрустальный шар — Scatter. 3+ Scatter = 15 бесплатных спинов со случайным Wild-символом.",
    features: ['RTP 95.13%', '15 фриспинов', 'Случайный Wild', 'Гамбл-функция', '10 линий'],
    maxWin: '9 000x',
    minBet: '0.40 ₽',
    casinoSlugs: NOVOMATIC_CASINOS,
    faqs: [],
  },

  // ── RELAX GAMING ──
  {
    slug: 'money-train-2',
    name: 'Money Train 2',
    provider: 'Relax Gaming',
    providerSlug: 'relax-gaming',
    rtp: '96.4%',
    type: 'slot',
    icon: '🚂',
    color: '#ef4444',
    volatility: 'very-high',
    description: 'Ограбление поезда с Persistent Symbols и потенциалом 50 000×. Легенда высоковолатильных слотов.',
    metaDesc: 'Money Train 2 играть онлайн 2026. Relax Gaming, RTP 96.4%, до 50000x.',
    longDesc: 'Money Train 2 — сиквел культового слота. 5×4, 40 линий. Persistent Payer и Collector символы в бонусе. Спины с нарастающими множителями. Потенциал 50 000× при максимальных множителях.',
    features: ['RTP 96.4%', 'Persistent Symbols', 'Бонус Respin', 'Макс. 50 000×', 'Buy Feature'],
    maxWin: '50 000x',
    minBet: '0.20 ₽',
    casinoSlugs: RELAX_CASINOS,
    popular: true,
    faqs: [
      { q: 'Чем Money Train 2 лучше оригинала?', a: 'Новые Persistent Symbols (Collector, Payer, Necromancer) и увеличенный потенциал до 50 000×.' },
    ],
  },
  {
    slug: 'money-train-3',
    name: 'Money Train 3',
    provider: 'Relax Gaming',
    providerSlug: 'relax-gaming',
    rtp: '96.31%',
    type: 'slot',
    icon: '🚄',
    color: '#dc2626',
    volatility: 'very-high',
    description: 'Третья часть легенды — новые символы Buffer, Sniper, Gambler и потенциал 100 000×.',
    metaDesc: 'Money Train 3 играть онлайн 2026. Relax Gaming, новые символы, до 100000x.',
    longDesc: 'Money Train 3 — самая жёсткая версия серии. Новые Persistent Symbols: Buffer, Sniper, Gambler. Потенциал 100 000×. Улучшенная Bonus Buy с фиксированным количеством спинов.',
    features: ['RTP 96.31%', 'Buffer символ', 'Макс. 100 000×', 'Buy Feature', 'Новые Persistent Symbols'],
    maxWin: '100 000x',
    minBet: '0.20 ₽',
    casinoSlugs: RELAX_CASINOS,
    popular: true,
    isNew: true,
    faqs: [
      { q: 'Что такое Buffer в Money Train 3?', a: 'Buffer сохраняет текущий множитель для следующего спина, удваивая потенциал выигрыша.' },
    ],
  },
  {
    slug: 'deadwood',
    name: 'Deadwood xNudge',
    provider: 'Relax Gaming',
    providerSlug: 'relax-gaming',
    rtp: '96.81%',
    type: 'slot',
    icon: '🤠',
    color: '#78350f',
    volatility: 'very-high',
    description: 'Дикий Запад с xNudge механикой. Wild скользит на позицию с накопительным множителем.',
    metaDesc: 'Deadwood xNudge играть онлайн 2026. Relax Gaming, xNudge Wilds, до 100000x.',
    longDesc: 'Deadwood xNudge — вестерн-слот в коллаборации Relax Gaming и Nolimit City. xNudge Wild: Wild скользит на позицию с накопительным множителем. В бонусе до 5 Wilds одновременно.',
    features: ['RTP 96.81%', 'xNudge Wild', 'Накопительный множитель', '5 Wild в бонусе', 'Макс. 100 000×'],
    maxWin: '100 000x',
    minBet: '0.20 ₽',
    casinoSlugs: RELAX_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'snake-arena',
    name: 'Snake Arena',
    provider: 'Relax Gaming',
    providerSlug: 'relax-gaming',
    rtp: '96%',
    type: 'crash',
    icon: '🐍',
    color: '#16a34a',
    volatility: 'high',
    description: 'Змея движется по арене — ставь на длину маршрута и забирай до гибели.',
    metaDesc: 'Snake Arena играть онлайн 2026. Relax Gaming, краш со змеёй, провабли фэйр.',
    longDesc: 'Snake Arena — оригинальная краш-игра от Relax Gaming. Змея ползёт по сетке, множитель растёт. Чем длиннее маршрут — тем больше выигрыш. Мгновенный вывод в любой момент.',
    features: ['RTP 96%', 'Уникальная механика', 'Авто-вывод', 'Провабли фэйр', 'Мгновенная игра'],
    maxWin: '100x',
    minBet: '1 ₽',
    casinoSlugs: RELAX_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── BIG TIME GAMING ──
  {
    slug: 'bonanza-megaways',
    name: 'Bonanza Megaways',
    provider: 'Big Time Gaming',
    providerSlug: 'big-time-gaming',
    rtp: '96%',
    type: 'slot',
    icon: '💣',
    color: '#7c3aed',
    volatility: 'very-high',
    description: 'Изобретатель Megaways — до 117 649 способов выиграть. Каскады и неограниченные множители.',
    metaDesc: 'Bonanza Megaways играть онлайн 2026. BTG, RTP 96%, 117649 линий, неограниченный множитель.',
    longDesc: 'Bonanza Megaways — слот-революция, изменивший индустрию. До 117 649 Megaways. Cascades: выигрышные символы взрываются, падают новые. В Free Spins каждый каскад добавляет ×1 к множителю без ограничений.',
    features: ['RTP 96%', 'До 117 649 Megaways', 'Неограниченный множитель', 'Cascade', 'Макс. ~50 000×'],
    maxWin: '50 000x',
    minBet: '0.20 ₽',
    casinoSlugs: BTG_CASINOS,
    popular: true,
    faqs: [
      { q: 'Что такое Megaways?', a: 'Запатентованная BTG механика: количество символов на каждом барабане меняется каждый спин, создавая от 324 до 117 649 способов выиграть.' },
    ],
  },
  {
    slug: 'extra-chilli',
    name: 'Extra Chilli Megaways',
    provider: 'Big Time Gaming',
    providerSlug: 'big-time-gaming',
    rtp: '96.79%',
    type: 'slot',
    icon: '🌶️',
    color: '#dc2626',
    volatility: 'very-high',
    description: 'Мексиканский перец и острые выигрыши. Megaways, Gamble Bonus и неограниченный множитель.',
    metaDesc: 'Extra Chilli Megaways играть онлайн 2026. BTG, острый слот, неограниченный множитель.',
    longDesc: 'Extra Chilli Megaways — горячий слот BTG. Megaways до 117 649. Gamble Bonus: можно делать ставку на бесплатные спины, увеличивая их количество. Unlimited Multiplier в бонусе.',
    features: ['RTP 96.79%', 'Megaways до 117 649', 'Gamble Bonus', 'Unlimited Multiplier', 'Cascade'],
    maxWin: '50 000x',
    minBet: '0.10 ₽',
    casinoSlugs: BTG_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'white-rabbit',
    name: 'White Rabbit Megaways',
    provider: 'Big Time Gaming',
    providerSlug: 'big-time-gaming',
    rtp: '97.72%',
    type: 'slot',
    icon: '🐰',
    color: '#7dd3fc',
    volatility: 'very-high',
    description: 'Алиса в стране чудес — Megaways до 248 832. Расширяющиеся барабаны. RTP 97.72%.',
    metaDesc: 'White Rabbit Megaways играть онлайн 2026. BTG, RTP 97.72%, 248832 линий.',
    longDesc: 'White Rabbit — слот BTG с максимальным количеством Megaways (248 832). В бонусе каждый разрыв заполняется Feeder символами, расширяя барабаны до 12 символов. RTP 97.72% — один из лучших.',
    features: ['RTP 97.72%', 'До 248 832 Megaways', 'Feeder механика', 'Расширяющиеся барабаны', 'Макс. 13 000×'],
    maxWin: '13 000x',
    minBet: '0.10 ₽',
    casinoSlugs: BTG_CASINOS,
    faqs: [],
  },

  // ── MICROGAMING ──
  {
    slug: 'mega-moolah',
    name: 'Mega Moolah',
    provider: 'Microgaming',
    providerSlug: 'microgaming',
    rtp: '88.12%',
    type: 'slot',
    icon: '🦁',
    color: '#ca8a04',
    volatility: 'medium',
    description: 'Рекордный прогрессивный джекпот в истории онлайн-казино. Старт от $1 000 000!',
    metaDesc: 'Mega Moolah играть онлайн 2026. Microgaming, прогрессивный джекпот от $1 млн.',
    longDesc: 'Mega Moolah — легенда онлайн-гемблинга. Прогрессивный джекпот начинается от $1 000 000. Рекорд — €23 600 000. 4 джекпота: Mini, Minor, Major, Mega. 5×3, 25 линий, африканская тема.',
    features: ['RTP 88.12%', 'Прогрессив от $1 млн', '4 уровня джекпота', '25 линий', 'Колесо джекпота'],
    maxWin: '∞ (прогрессив)',
    minBet: '0.25 ₽',
    casinoSlugs: MICROGAMING_CASINOS,
    popular: true,
    faqs: [
      { q: 'Каков рекорд Mega Moolah?', a: 'Рекорд — €23 600 000, выигранных в 2021 году. Один из крупнейших выигрышей в истории онлайн-казино.' },
    ],
  },
  {
    slug: 'thunderstruck-2',
    name: 'Thunderstruck II',
    provider: 'Microgaming',
    providerSlug: 'microgaming',
    rtp: '96.65%',
    type: 'slot',
    icon: '🔨',
    color: '#1d4ed8',
    volatility: 'medium',
    description: 'Тор, Один, Локи и Валькирия. 4 уровня бонусов с нарастающим потенциалом.',
    metaDesc: 'Thunderstruck 2 играть онлайн 2026. Microgaming, norse боги, RTP 96.65%.',
    longDesc: 'Thunderstruck II — культовый слот Microgaming. 5×3, 243 линии. Great Hall of Spins: 4 уровня бонусов (Валькирия, Локи, Один, Тор) разблокируются последовательно с каждым посещением.',
    features: ['RTP 96.65%', 'Hall of Spins', '4 бонусных режима', '243 линии', 'Макс. 2 400×'],
    maxWin: '2 400x',
    minBet: '0.30 ₽',
    casinoSlugs: MICROGAMING_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'immortal-romance',
    name: 'Immortal Romance',
    provider: 'Microgaming',
    providerSlug: 'microgaming',
    rtp: '96.86%',
    type: 'slot',
    icon: '🧛',
    color: '#7c3aed',
    volatility: 'high',
    description: 'Вампирская история любви. 4 персонажа с уникальными бонусами. Wild Desire.',
    metaDesc: 'Immortal Romance играть онлайн 2026. Microgaming, вампиры, RTP 96.86%.',
    longDesc: 'Immortal Romance — вампирский слот Microgaming с сюжетом. 5×3, 243 линии. Chamber of Spins: 4 персонажа (Amber, Troy, Michael, Sarah) с разными бонусами. Нарастающие Wild Desire.',
    features: ['RTP 96.86%', 'Chamber of Spins', '4 персонажа', 'Wild Desire', '243 линии'],
    maxWin: '3 645x',
    minBet: '0.30 ₽',
    casinoSlugs: MICROGAMING_CASINOS,
    popular: true,
    faqs: [],
  },

  // ── WAZDAN ──
  {
    slug: '9-lions',
    name: '9 Lions',
    provider: 'Wazdan',
    providerSlug: 'wazdan',
    rtp: '96.36%',
    type: 'slot',
    icon: '🦁',
    color: '#ca8a04',
    volatility: 'high',
    description: 'Девять золотых львов с настраиваемой дисперсией. Уникальная функция Volatility Levels.',
    metaDesc: '9 Lions играть онлайн 2026. Wazdan, настраиваемая дисперсия, RTP 96.36%.',
    longDesc: '9 Lions от Wazdan — азиатский слот 5×3. Уникальная функция Volatility Levels позволяет выбрать режим риска. Energy Saving режим снижает нагрузку на устройство. 9 бесплатных спинов.',
    features: ['RTP 96.36%', 'Volatility Levels', '9 бесплатных спинов', 'Gamble Feature', 'Energy Saving'],
    maxWin: '6 250x',
    minBet: '0.09 ₽',
    casinoSlugs: WAZDAN_CASINOS,
    faqs: [],
  },
  {
    slug: 'power-of-gods',
    name: 'Power of Gods: Egypt',
    provider: 'Wazdan',
    providerSlug: 'wazdan',
    rtp: '96.53%',
    type: 'slot',
    icon: '⚡',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Египетские боги и сила Ра. Heart Wilds с накопителем и All Ways в бесплатных спинах.',
    metaDesc: 'Power of Gods Egypt играть онлайн 2026. Wazdan, египетский слот, RTP 96.53%.',
    longDesc: 'Power of Gods: Egypt — мощный египетский слот Wazdan. 5×3, 20 линий. Heart Wilds накапливают сердца для бонуса. В бесплатных спинах All Ways win активируется автоматически.',
    features: ['RTP 96.53%', 'Heart Wilds', '10 фриспинов', 'All Ways', 'Volatility Levels'],
    maxWin: '6 250x',
    minBet: '0.09 ₽',
    casinoSlugs: WAZDAN_CASINOS,
    faqs: [],
  },
  {
    slug: 'magic-stars-9',
    name: 'Magic Stars 9',
    provider: 'Wazdan',
    providerSlug: 'wazdan',
    rtp: '96.5%',
    type: 'slot',
    icon: '⭐',
    color: '#6366f1',
    volatility: 'medium',
    description: 'Классический звёздный слот 9×3 с фруктами. Простые правила, высокий RTP.',
    metaDesc: 'Magic Stars 9 играть онлайн 2026. Wazdan, 9 барабанов, фрукты, RTP 96.5%.',
    longDesc: 'Magic Stars 9 — расширенная версия классики Wazdan. Девять барабанов, фруктовые символы и звёзды. Sticky Wild с множителем. Простые правила — идеально для новичков.',
    features: ['RTP 96.5%', '9 барабанов', 'Sticky Wild', 'Gamble Feature', 'Классические символы'],
    maxWin: '2 000x',
    minBet: '0.09 ₽',
    casinoSlugs: WAZDAN_CASINOS,
    faqs: [],
  },

  // ── ELK STUDIOS ──
  {
    slug: 'wild-toro',
    name: 'Wild Toro',
    provider: 'ELK Studios',
    providerSlug: 'elk-studios',
    rtp: '96.4%',
    type: 'slot',
    icon: '🐂',
    color: '#dc2626',
    volatility: 'high',
    description: 'Матадор vs бык — бешеный бык сметает символы и становится Wild. Испанская страсть.',
    metaDesc: 'Wild Toro играть онлайн 2026. ELK Studios, бык и матадор, RTP 96.4%.',
    longDesc: 'Wild Toro — испанский слот ELK Studios. 5×4, 178 линий. Toro-бык движется по барабанам и становится Wild, сметая символы. El Toro Wild = бык-мегасимвол 2×2.',
    features: ['RTP 96.4%', 'Toro Wild', 'El Toro 2×2', '178 линий', 'Стратегии ставок ELK'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: ELK_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'sam-on-the-beach',
    name: 'Sam on the Beach',
    provider: 'ELK Studios',
    providerSlug: 'elk-studios',
    rtp: '96.2%',
    type: 'slot',
    icon: '🏖️',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Пляжная вечеринка с Сэмом. Surfin\' Sam Expanding Wild и Beach Party бонус.',
    metaDesc: 'Sam on the Beach играть онлайн 2026. ELK Studios, пляж, RTP 96.2%.',
    longDesc: "Sam on the Beach — летний слот ELK Studios. 5×3, 243 линии. Surfin' Sam Wild расширяется на весь барабан. Beach Party Bonus: 10 бесплатных спинов с Expanding Wild на каждом барабане.",
    features: ['RTP 96.2%', 'Surfin\' Sam Wild', 'Expanding Wild', '10 фриспинов', '243 линии'],
    maxWin: '2 500x',
    minBet: '0.20 ₽',
    casinoSlugs: ELK_CASINOS,
    faqs: [],
  },

  // ── QUICKSPIN ──
  {
    slug: 'big-bad-wolf',
    name: 'Big Bad Wolf',
    provider: 'Quickspin',
    providerSlug: 'quickspin',
    rtp: '97.34%',
    type: 'slot',
    icon: '🐺',
    color: '#334155',
    volatility: 'high',
    description: 'Три поросёнка и злой волк. Символы сдуваются, открывая Wild-поросят. RTP 97.34%.',
    metaDesc: 'Big Bad Wolf играть онлайн 2026. Quickspin, три поросёнка, RTP 97.34%.',
    longDesc: 'Big Bad Wolf — сказочный слот Quickspin с высочайшим RTP. 5×3, 25 линий. Волк дует и сдувает дома: Pigs Turn Wild — поросята превращаются в Wilds. Moon Wilds в бесплатных спинах.',
    features: ['RTP 97.34%', 'Pigs Turn Wild', 'Moon Wilds', '10 фриспинов', '25 линий'],
    maxWin: '3 500x',
    minBet: '0.25 ₽',
    casinoSlugs: QUICKSPIN_CASINOS,
    faqs: [
      { q: 'Почему Big Bad Wolf популярен для отыгрыша?', a: 'RTP 97.34% — один из лучших среди слотов. Стабильные выигрыши снижают потери при вейджере.' },
    ],
  },
  {
    slug: 'sakura-fortune',
    name: 'Sakura Fortune',
    provider: 'Quickspin',
    providerSlug: 'quickspin',
    rtp: '96.55%',
    type: 'slot',
    icon: '🌸',
    color: '#f472b6',
    volatility: 'high',
    description: 'Японская принцесса-воин. Re-spins с нарастающими Sticky Wilds и зеркальными Wild.',
    metaDesc: 'Sakura Fortune играть онлайн 2026. Quickspin, японская принцесса, RTP 96.55%.',
    longDesc: 'Sakura Fortune — японский слот Quickspin. 5×4, 40 линий. При Wild на барабане 3 триггеруются Re-spins. Mirror Wild создаёт зеркальные Wild на барабанах 1 и 5 одновременно.',
    features: ['RTP 96.55%', 'Re-spins', 'Mirror Wild', 'Sticky Wild', '40 линий'],
    maxWin: '3 200x',
    minBet: '0.20 ₽',
    casinoSlugs: QUICKSPIN_CASINOS,
    faqs: [],
  },

  // ── ENDORPHINA ──
  {
    slug: 'book-of-santa',
    name: 'Book of Santa',
    provider: 'Endorphina',
    providerSlug: 'endorphina',
    rtp: '96%',
    type: 'slot',
    icon: '🎅',
    color: '#dc2626',
    volatility: 'high',
    description: 'Новогодняя версия книжного слота. Книга Санты = Wild+Scatter. 10 фриспинов.',
    metaDesc: 'Book of Santa играть онлайн 2026. Endorphina, новогодний слот, RTP 96%.',
    longDesc: 'Book of Santa от Endorphina — рождественский книжный слот. 5×3, 10 линий. Классическая механика: книга Wild и Scatter. 10 бесплатных спинов с расширяющимся символом. Популярен в СНГ казино.',
    features: ['RTP 96%', 'Wild+Scatter', '10 фриспинов', 'Расширяющийся символ', '10 линий'],
    maxWin: '5 000x',
    minBet: '0.01 ₽',
    casinoSlugs: ENDORPHINA_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'hit-slot-2021',
    name: '2021 Hit Slot',
    provider: 'Endorphina',
    providerSlug: 'endorphina',
    rtp: '96%',
    type: 'slot',
    icon: '🎰',
    color: '#f59e0b',
    volatility: 'medium',
    description: 'Классический однорукий бандит с Hold & Spin и накопительными призами.',
    metaDesc: '2021 Hit Slot играть онлайн 2026. Endorphina, классический слот, Hold & Spin, RTP 96%.',
    longDesc: '2021 Hit Slot — дань уважения классическим игровым автоматам. Барабаны, колокола, 7 и BAR. С современными фишками: Hold & Spin, накопительные призы. Ностальгия для ветеранов гемблинга.',
    features: ['RTP 96%', 'Hold & Spin', 'Классические символы', 'Накопительные призы', 'Ретро дизайн'],
    maxWin: '5 000x',
    minBet: '0.01 ₽',
    casinoSlugs: ENDORPHINA_CASINOS,
    faqs: [],
  },

  // ── SMARTSOFT GAMING ──
  {
    slug: 'jetx',
    name: 'JetX',
    provider: 'Smartsoft Gaming',
    providerSlug: 'smartsoft-gaming',
    rtp: '97%',
    type: 'crash',
    icon: '✈️',
    color: '#0ea5e9',
    volatility: 'high',
    description: 'Реактивный самолёт разгоняется — успей забрать до взрыва. Второй по популярности краш после Aviator.',
    metaDesc: 'JetX играть онлайн 2026. Smartsoft, реактивный краш, RTP 97%, казино с JetX.',
    longDesc: 'JetX от Smartsoft Gaming — популярная краш-игра, альтернатива Aviator. Самолёт взлетает, множитель растёт. Активный чат игроков и лидерборд ставок. Доступен во многих СНГ казино.',
    features: ['RTP 97%', 'Чат игроков', 'Лидерборд', 'Авто-вывод', 'Провабли фэйр'],
    maxWin: '25 000x',
    minBet: '0.10 ₽',
    casinoSlugs: SMARTSOFT_CASINOS,
    popular: true,
    faqs: [
      { q: 'JetX или Aviator — что выбрать?', a: 'Aviator от Spribe — лидер рынка, доступен в большинстве казино. JetX — хорошая альтернатива с лидербордом и активным чатом.' },
    ],
  },

  // ── AMATIC ──
  {
    slug: 'book-of-aztec',
    name: 'Book of Aztec',
    provider: 'Amatic Industries',
    providerSlug: 'amatic',
    rtp: '95.66%',
    type: 'slot',
    icon: '🏺',
    color: '#d97706',
    volatility: 'high',
    description: 'Ацтекская версия Book of Ra от австрийского классика. Та же механика, экзотическая тема.',
    metaDesc: 'Book of Aztec играть онлайн 2026. Amatic, ацтекский слот, RTP 95.66%.',
    longDesc: 'Book of Aztec от Amatic — популярная альтернатива Book of Ra с ацтекской тематикой. 5×3, 10 линий. Книга = Wild+Scatter. 10 бесплатных спинов с расширяющимся символом.',
    features: ['RTP 95.66%', 'Wild+Scatter', '10 фриспинов', 'Расширяющийся символ', 'Гамбл-функция'],
    maxWin: '5 000x',
    minBet: '0.04 ₽',
    casinoSlugs: AMATIC_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'fruit-cocktail',
    name: 'Fruit Cocktail',
    provider: 'Amatic Industries',
    providerSlug: 'amatic',
    rtp: '95.5%',
    type: 'slot',
    icon: '🍹',
    color: '#ec4899',
    volatility: 'medium',
    description: 'Легендарный «Резак» — один из самых известных слотов 2000-х в СНГ игровых залах.',
    metaDesc: 'Fruit Cocktail Резак играть онлайн 2026. Amatic, ностальгия СНГ, клубничный слот.',
    longDesc: 'Fruit Cocktail (Резак) — культовый слот, известный в СНГ с игровых залов. 5×3. Клубника — дикий символ. Бонус-игра: угадай цвет карты для удвоения. Ностальгия для игроков СНГ.',
    features: ['RTP 95.5%', 'Клубника-Wild', 'Гамбл по цвету', 'Бонус-игра', 'Классический дизайн'],
    maxWin: '1 200x',
    minBet: '0.04 ₽',
    casinoSlugs: AMATIC_CASINOS,
    popular: true,
    faqs: [
      { q: 'Fruit Cocktail — тот самый «Резак»?', a: 'Да, это онлайн-версия легендарного автомата из игровых залов 2000-х. Та же клубника и гамбл.' },
    ],
  },

  // ── PLAYSON ──
  {
    slug: 'solar-queen',
    name: 'Solar Queen',
    provider: 'Playson',
    providerSlug: 'playson',
    rtp: '95.93%',
    type: 'slot',
    icon: '☀️',
    color: '#f59e0b',
    volatility: 'high',
    description: 'Солнечная королева с Wild Wave — волна Wilds прокатывается по барабанам.',
    metaDesc: 'Solar Queen играть онлайн 2026. Playson, Hold & Link, Wild Wave, RTP 95.93%.',
    longDesc: 'Solar Queen от Playson — египетский слот с солнечной тематикой. 5×3, 10 линий. Wild Wave: Wild разливается по барабанам. Respin механика при 6+ Scatter. Популярен в СНГ казино.',
    features: ['RTP 95.93%', 'Wild Wave', 'Respin 6+ Scatter', 'Hold & Link', '10 линий'],
    maxWin: '5 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PLAYSON_CASINOS,
    faqs: [],
  },
  {
    slug: 'book-of-gold',
    name: 'Book of Gold: Classic',
    provider: 'Playson',
    providerSlug: 'playson',
    rtp: '95.8%',
    type: 'slot',
    icon: '📕',
    color: '#ca8a04',
    volatility: 'high',
    description: 'Золотая книга — ещё один книжный слот для любителей жанра. Wild+Scatter, 10 фриспинов.',
    metaDesc: 'Book of Gold Classic играть онлайн 2026. Playson, книжный слот, RTP 95.8%.',
    longDesc: 'Book of Gold: Classic — представитель жанра книжных слотов от Playson. 5×3, 10 линий. Книга Wild и Scatter. 10 фриспинов с расширяющимся символом.',
    features: ['RTP 95.8%', 'Wild+Scatter', '10 фриспинов', 'Расширяющийся символ', '10 линий'],
    maxWin: '5 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PLAYSON_CASINOS,
    faqs: [],
  },

  // ── NETENT (дополнительно) ──
  {
    slug: 'dead-or-alive-2',
    name: 'Dead or Alive 2',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '96.8%',
    type: 'slot',
    icon: '🔫',
    color: '#78350f',
    volatility: 'very-high',
    description: 'Дикий Запад в стиле 5×3. Sticky Wild в бонусе и до 100 фриспинов. Потенциал 100 000×.',
    metaDesc: 'Dead or Alive 2 играть онлайн 2026. NetEnt, RTP 96.8%, Sticky Wilds, до 100000x.',
    longDesc: 'Dead or Alive 2 — легендарный высоковолатильный слот NetEnt. 5×3, 9 линий. 3 режима бонуса: Train Heist (5 спинов), High Noon Saloon (12 спинов), Old Saloon (12 спинов). Все Wilds липкие.',
    features: ['RTP 96.8%', '3 режима бонуса', 'Sticky Wilds', 'До 100 фриспинов', 'Макс. 100 000×'],
    maxWin: '100 000x',
    minBet: '0.09 ₽',
    casinoSlugs: NETENT_CASINOS,
    popular: true,
    faqs: [
      { q: 'Какой режим Dead or Alive 2 лучший?', a: 'Train Heist (5 спинов) — максимальный потенциал. Old Saloon — до 100 спинов с ретриггером. High Noon — средний баланс.' },
    ],
  },
  {
    slug: 'narcos',
    name: 'Narcos',
    provider: 'NetEnt',
    providerSlug: 'netent',
    rtp: '96.23%',
    type: 'slot',
    icon: '🌿',
    color: '#16a34a',
    volatility: 'high',
    description: 'По мотивам культового сериала Netflix. Drive-by Feature, Locked Up и Walking Wilds.',
    metaDesc: 'Narcos играть онлайн 2026. NetEnt, сериал Netflix, Drive-by Feature, RTP 96.23%.',
    longDesc: 'Narcos — официальный слот по мотивам сериала Netflix. 5×3, 243 линии. Drive-by Feature: случайная стрельба добавляет Wild на экран. Locked Up Wilds и Walking Wilds в бесплатных спинах.',
    features: ['RTP 96.23%', 'Drive-by Feature', 'Locked Up Wilds', 'Walking Wilds', '243 линии'],
    maxWin: '2 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NETENT_CASINOS,
    faqs: [],
  },

  // ── PLAY'N GO (дополнительно) ──
  {
    slug: 'moon-princess',
    name: 'Moon Princess',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.51%',
    type: 'slot',
    icon: '🌙',
    color: '#a855f7',
    volatility: 'very-high',
    description: 'Аниме-принцессы в бою. Trinity Bonus и Power сбросы с потенциалом 5 000×.',
    metaDesc: 'Moon Princess играть онлайн 2026. Play\'n GO, аниме, RTP 96.51%, Trinity бонус.',
    longDesc: "Moon Princess — яркий аниме-слот Play'n GO. 5×5, кластеры. 3 принцессы (Star, Love, Storm) с уникальными способностями. Trinity Bonus: совместная атака всех трёх принцесс.",
    features: ['RTP 96.51%', 'Trinity Bonus', '3 принцессы', 'Cluster Pays 5×5', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'rise-of-olympus',
    name: 'Rise of Olympus',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.5%',
    type: 'slot',
    icon: '🌩️',
    color: '#7c3aed',
    volatility: 'very-high',
    description: 'Зевс, Аид и Посейдон на Олимпе. Уникальные способности богов и Hand of God.',
    metaDesc: 'Rise of Olympus играть онлайн 2026. Play\'n GO, греческие боги, RTP 96.5%.',
    longDesc: "Rise of Olympus — мощный мифологический слот Play'n GO. 5×5, кластеры. Зевс, Аид и Посейдон — три бога с разными способностями. Hand of God активируется при наличии двух Wild-символов.",
    features: ['RTP 96.5%', '3 бога', 'Hand of God', 'Cluster Pays', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    popular: true,
    faqs: [],
  },
  {
    slug: 'tome-of-madness',
    name: 'Tome of Madness',
    provider: "Play'n GO",
    providerSlug: 'playn-go',
    rtp: '96.52%',
    type: 'slot',
    icon: '📓',
    color: '#1e293b',
    volatility: 'very-high',
    description: 'Тёмная магия и безумие. Portal и Wild Collection механики. Сиквел Rich Wilde.',
    metaDesc: 'Tome of Madness играть онлайн 2026. Play\'n GO, Rich Wilde, тёмная магия, RTP 96.52%.',
    longDesc: "Rich Wilde and the Tome of Madness — хоррор-продолжение серии Play'n GO. 5×5, кластеры. Portal: случайно собирает выигрышные символы в одну точку. Wild Collection: 3 Wild = бонус Portal.",
    features: ['RTP 96.52%', 'Portal механика', 'Wild Collection', 'Cluster Pays', 'Макс. 5 000×'],
    maxWin: '5 000x',
    minBet: '0.20 ₽',
    casinoSlugs: PLAYNGO_CASINOS,
    faqs: [],
  },

  // ── HACKSAW (дополнительно) ──
  {
    slug: 'stick-em',
    name: "Stick 'Em",
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '96.95%',
    type: 'slot',
    icon: '🍬',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Конфеты прилипают к барабанам. Sticky re-spins с нарастающими Wild. Потенциал 12 500×.',
    metaDesc: "Stick Em играть онлайн 2026. Hacksaw Gaming, sticky символы, RTP 96.95%.",
    longDesc: "Stick 'Em от Hacksaw Gaming — слот 5×4 со Sticky символами. Высокооплачиваемые символы прилипают к барабану при попадании. Re-spin запускается автоматически. Потенциал 12 500×.",
    features: ['RTP 96.95%', 'Sticky символы', 'Re-spins', '4 уровня фриспинов', 'Макс. 12 500×'],
    maxWin: '12 500x',
    minBet: '0.20 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'road-rage',
    name: 'Road Rage',
    provider: 'Hacksaw Gaming',
    providerSlug: 'hacksaw-gaming',
    rtp: '96%',
    type: 'slot',
    icon: '🏎️',
    color: '#ef4444',
    volatility: 'very-high',
    description: 'Уличные гонки и экстремальный риск. Cash Collect механика, потенциал 10 000×.',
    metaDesc: 'Road Rage играть онлайн 2026. Hacksaw Gaming, гоночный слот, до 10000x.',
    longDesc: 'Road Rage от Hacksaw Gaming — гоночный слот с экстремальной динамикой. Cash Collect: специальные символы суммируют значения денежных призов. Bonus Buy с несколькими режимами риска.',
    features: ['RTP 96%', 'Cash Collect', 'Bonus Buy', 'Режимы риска', 'Макс. 10 000×'],
    maxWin: '10 000x',
    minBet: '0.20 ₽',
    casinoSlugs: HACKSAW_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── PUSH GAMING (дополнительно) ──
  {
    slug: 'razor-shark',
    name: 'Razor Shark',
    provider: 'Push Gaming',
    providerSlug: 'push-gaming',
    rtp: '96.7%',
    type: 'slot',
    icon: '🦈',
    color: '#0369a1',
    volatility: 'very-high',
    description: 'Акула в глубинах океана. Mystery Stacks и Push Feature — потенциал 50 000×.',
    metaDesc: 'Razor Shark играть онлайн 2026. Push Gaming, акула, RTP 96.7%, до 50000x.',
    longDesc: 'Razor Shark — подводный слот Push Gaming с Mystery Stacks. 5×4, 20 линий. Mystery символы открываются случайно. Push Feature: Акула-Wild проваливается вниз, генерируя множители.',
    features: ['RTP 96.7%', 'Mystery Stacks', 'Push Feature', 'Shark Wild', 'Макс. 50 000×'],
    maxWin: '50 000x',
    minBet: '0.10 ₽',
    casinoSlugs: PUSH_CASINOS,
    popular: true,
    faqs: [
      { q: 'Как работает Push Feature?', a: 'Акула-Wild уходит вниз с экрана, генерируя случайный множитель ×2–×20 для следующего спина.' },
    ],
  },

  // ── NOLIMIT CITY (дополнительно) ──
  {
    slug: 'fire-in-the-hole',
    name: 'Fire in the Hole xBomb',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.33%',
    type: 'slot',
    icon: '💥',
    color: '#f97316',
    volatility: 'very-high',
    description: 'Горная шахта и взрывчатка. xBomb уничтожает символы и добавляет множитель. До 50 000×.',
    metaDesc: 'Fire in the Hole xBomb играть 2026. Nolimit City, взрывной слот, до 50000x.',
    longDesc: 'Fire in the Hole xBomb — шахтёрский слот Nolimit City. xBomb Wild взрывается: убирает соседние символы и увеличивает общий множитель. В бонусе каждый взрыв суммируется.',
    features: ['RTP 96.33%', 'xBomb механика', 'Накопительный множитель', 'Buy Bonus', 'Макс. 50 000×'],
    maxWin: '50 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    isNew: true,
    faqs: [],
  },
  {
    slug: 'folsom-prison',
    name: 'Folsom Prison',
    provider: 'Nolimit City',
    providerSlug: 'nolimit-city',
    rtp: '96.45%',
    type: 'slot',
    icon: '🎸',
    color: '#1e293b',
    volatility: 'very-high',
    description: 'Рок-н-ролл в тюрьме. xNudge и xWays механики, кантри-эстетика. Потенциал 30 000×.',
    metaDesc: 'Folsom Prison играть онлайн 2026. Nolimit City, тюрьма, xNudge, до 30000x.',
    longDesc: 'Folsom Prison — вдохновлённый Джонни Кэшем слот Nolimit City. Тюремная тема с кантри-музыкой. xWays и xNudge механики создают огромные комбинации при максимальных выигрышах.',
    features: ['RTP 96.45%', 'xWays механика', 'xNudge Wilds', 'Кантри-тема', 'Макс. 30 000×'],
    maxWin: '30 000x',
    minBet: '0.20 ₽',
    casinoSlugs: NOLIMIT_CASINOS,
    faqs: [],
  },

  // ── RED TIGER (дополнительно) ──
  {
    slug: 'lucky-wizard',
    name: 'Lucky Wizard',
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '96.22%',
    type: 'slot',
    icon: '🧙',
    color: '#7c3aed',
    volatility: 'medium',
    description: 'Волшебник с магическими зельями. Expanding Wild и зелья-бонусы.',
    metaDesc: 'Lucky Wizard играть онлайн 2026. Red Tiger, волшебник, RTP 96.22%.',
    longDesc: 'Lucky Wizard от Red Tiger — магический слот 5×3. Волшебник-Wild расширяется. Зелья-символы запускают различные бонусы: бесплатные спины, множители или денежные призы.',
    features: ['RTP 96.22%', 'Expanding Wizard Wild', 'Зелья-бонусы', 'Random Features', '20 линий'],
    maxWin: '3 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    faqs: [],
  },
  {
    slug: 'piggy-riches-megaways',
    name: 'Piggy Riches Megaways',
    provider: 'Red Tiger',
    providerSlug: 'red-tiger',
    rtp: '96.62%',
    type: 'slot',
    icon: '🐷',
    color: '#ec4899',
    volatility: 'very-high',
    description: 'Богатые свиньи в Megaways. До 117 649 линий и Unlimited Win Multiplier в бонусе.',
    metaDesc: 'Piggy Riches Megaways играть 2026. Red Tiger, Megaways, RTP 96.62%, свиньи.',
    longDesc: 'Piggy Riches Megaways — роскошный Megaways-слот Red Tiger. До 117 649 способов выиграть. Mrs. Piggy Wild с множителем ×2 в бонусе. Unlimited Win Multiplier в бесплатных спинах.',
    features: ['RTP 96.62%', 'До 117 649 Megaways', 'Mrs. Piggy Wild ×2', 'Unlimited Multiplier', 'Cascade'],
    maxWin: '10 000x',
    minBet: '0.10 ₽',
    casinoSlugs: REDTIGER_CASINOS,
    isNew: true,
    faqs: [],
  },

  // ── YGGDRASIL (дополнительно) ──
  {
    slug: 'cazino-cosmos',
    name: 'Cazino Cosmos',
    provider: 'Yggdrasil',
    providerSlug: 'yggdrasil',
    rtp: '96.0%',
    type: 'slot',
    icon: '🌌',
    color: '#312e81',
    volatility: 'high',
    description: 'Космическое казино со Sticky Wilds. Заполни экран Wild-символами для максимального выигрыша.',
    metaDesc: 'Cazino Cosmos играть онлайн 2026. Yggdrasil, космос, Sticky Wilds, RTP 96%.',
    longDesc: 'Cazino Cosmos — космический слот Yggdrasil. 5×3, 20 линий. Wild остаётся на экране до конца бонуса (Sticky Wild). Чем больше Wilds накоплено — тем выше потенциал последующих спинов.',
    features: ['RTP 96.0%', 'Sticky Wilds', 'Нарастающие Wilds', '10 фриспинов', 'Макс. 3 000×'],
    maxWin: '3 000x',
    minBet: '0.25 ₽',
    casinoSlugs: YGGDRASIL_CASINOS,
    faqs: [],
  },

  // ── SPRIBE (дополнительно) ──
  {
    slug: 'hilo',
    name: 'HiLo',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '🃏',
    color: '#7c3aed',
    volatility: 'medium',
    description: 'Угадай — следующая карта выше или ниже. Простая карточная игра с нарастающим выигрышем.',
    metaDesc: 'HiLo играть онлайн 2026. Spribe, карточная игра, RTP 97%, выше или ниже.',
    longDesc: 'HiLo от Spribe — карточная игра с простыми правилами. Каждое угаданное значение увеличивает множитель. Выберите: следующая карта выше (Hi) или ниже (Lo) текущей. Забирайте в любой момент.',
    features: ['RTP 97%', 'Простые правила', 'Авто-угадывание', 'Провабли фэйр', 'Мгновенный результат'],
    maxWin: '500x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    faqs: [],
  },
  {
    slug: 'goal',
    name: 'Goal',
    provider: 'Spribe',
    providerSlug: 'spribe',
    rtp: '97%',
    type: 'instant',
    icon: '⚽',
    color: '#16a34a',
    volatility: 'medium',
    description: 'Футбольная игра — выбирай направление удара и проходи уровни для максимального приза.',
    metaDesc: 'Goal играть онлайн 2026. Spribe, футбол, угадай направление, RTP 97%.',
    longDesc: 'Goal от Spribe — футбольная моментальная игра. Три ворот с разными секторами. Выбери направление: левый, центр, правый. Каждый гол увеличивает множитель. Забирай или продолжай.',
    features: ['RTP 97%', 'Футбольная тема', '3 направления', 'Нарастающий множитель', 'Провабли фэйр'],
    maxWin: '700x',
    minBet: '1 ₽',
    casinoSlugs: SPRIBE_CASINOS,
    faqs: [],
  },
]

// Получить игру по слагу
export function getGameBySlug(slug: string): Game | undefined {
  return games.find(g => g.slug === slug)
}

// Получить казино где доступна игра
export function getCasinosForGame(slug: string) {
  const game = getGameBySlug(slug)
  if (!game) return []
  return game.casinoSlugs
}
