// Clearbit Logo API — бесплатно, без API ключа, возвращает реальный логотип по домену
export function getLogo(domain: string, size = 64): string {
  return `https://logo.clearbit.com/${domain}?size=${size}`
}

// Реальные домены для каждого бренда
export const brandLogos: Record<string, string> = {
  '1xbet':        getLogo('1xbet.com'),
  '1win':         getLogo('1win.com'),
  'melbet':       getLogo('melbet.com'),
  'pari':         getLogo('pari.ru'),
  'betcity':      getLogo('betcity.ru'),
  'olimpbet':     getLogo('olimpbet.ru'),
  'marathon':     getLogo('marathonbet.ru'),
  'liga-stavok':  getLogo('ligastavok.ru'),
  'tennisi':      getLogo('tennisi.com'),
  'baltbet':      getLogo('baltbet.ru'),
  'zenit':        getLogo('zenit.bet'),
  'bettery':      getLogo('bettery.ru'),
  'sportbet':     getLogo('sportbet.ru'),
  '1xstavka':     getLogo('1xstavka.ru'),
  'bet-m':        getLogo('bet-m.ru'),
  'vulkan-russia':getLogo('vulkan-russia.com'),
  'joycasino':    getLogo('joycasino.com'),
  'frank-casino': getLogo('frank.casino'),
  'slotv':        getLogo('slotv.com'),
  'casino-x':     getLogo('casino-x.com'),
  'pin-up':       getLogo('pinup.com'),
  'vavada':       getLogo('vavada.com'),
  'cat-casino':   getLogo('cat.casino'),
  'loki-casino':  getLogo('loki.casino'),
  'fresh-casino': getLogo('fresh.casino'),
  'riobet':       getLogo('riobet.com'),
  'bet365':       getLogo('bet365.com'),
  'betway':       getLogo('betway.com'),
  'william-hill': getLogo('williamhill.com'),
  'bwin':         getLogo('bwin.com'),
  'betfair':      getLogo('betfair.com'),
  'unibet':       getLogo('unibet.com'),
  'parimatch-int':getLogo('parimatch.com'),
  'ggbet':        getLogo('ggbet.com'),
  'sportsbet-io': getLogo('sportsbet.io'),
  'stake':        getLogo('stake.com'),
  'bc-game':      getLogo('bc.game'),
  'cazino-kosmos':getLogo('casinokosmos.com'),
  'legzo':        getLogo('legzo.casino'),
  'brillx':       getLogo('brillx.casino'),
  'goxbet':       getLogo('goxbet.com'),
  'casinooon':    getLogo('casinooon.com'),
  'hotslots':     getLogo('hotslots.com'),
  'bitstarz':     getLogo('bitstarz.com'),
  'spribe-aviator':getLogo('spribe.co'),
  'pokerdom':     getLogo('pokerdom.com'),
  'ggpoker':      getLogo('ggpoker.com'),
}

// Скриншоты главной страницы через URLbox
export const brandScreenshots: Record<string, string[]> = {
  '1xbet':        ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://1xbet.com&width=1280&height=720&format=webp&fresh=false'],
  '1win':         ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://1win.com&width=1280&height=720'],
  'bet365':       ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://bet365.com&width=1280&height=720'],
  'stake':        ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://stake.com&width=1280&height=720'],
  'bitstarz':     ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://bitstarz.com&width=1280&height=720'],
  'vavada':       ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://vavada.com&width=1280&height=720'],
  'pin-up':       ['https://api.apiflash.com/v1/urltoimage?access_key=free&url=https://pinup.com&width=1280&height=720'],
}
